{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1203.0 (24.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"BlobStorage\",\"QueryString\",\"Drives - Time Tracking\",\"Drives - Financials\",\"Drives - Title Application Errors\",\"SnapEngage\",\"SQLServerDB\",\"SQLServerName\",\"mdm MVTypeCategory\",\"Datalake\",\"Call Manager - App Summary\",\"Parameter App Summary\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Call Manager - Agent Call Summary\",\"Parameter AgentSummary\",\"Transform Sample File (2)\",\"Sample AgentSummary\",\"Transform File (2)\",\"Call Manager - Common Skill CSQ\",\"Parameter CSQ\",\"Transform Sample File (3)\",\"Sample CSQ\",\"Transform File (3)\",\"Qmatic - File List\",\"Qmatic - Branch\",\"Qmatic - End Time\",\"Qmatic - Entered Queue Time\",\"Qmatic - Entry Point\",\"Qmatic - Queue\",\"Qmatic - Queue Type\",\"Qmatic - Service Point\",\"Qmatic - Service\",\"Qmatic - Staff\",\"Qmatic - Visit Call Type\",\"Qmatic - Visit\",\"Qmatic - Visit Transaction Outcome\",\"Qmatic - Work Profile\",\"Qmatic - Visit Transaction\",\"DC - Closure\",\"DC - Drives Goals\",\"DC - Location\",\"Drives - Fee Statistics\",\"Drives - Fee Waiver Tracking\",\"Drives - Title Application Errors Castle Rock\",\"Drives - Title Application Errors Highlands Ranch\",\"DC - Division\",\"DC - Time\",\"Qmatic - Staff Group by\",\"_Measures\",\"MDS - SnapEngage Chat Agent Id\",\"Staff Stats - File Table List\",\"Staff Stats - Mail Rejects\",\"Staff Stats - Salvage Rejects\",\"Staff Stats - Staff Sheets\",\"Staff Stats - Physical Mail Data\",\"Transform Staff Stats Sheet 2022\",\"Transform Staff Stats Sheet 2021\",\"SnapFileMain\",\"SnapBinarytoText\",\"SnapEngageChat\",\"SnapFileChats\",\"Qmatic - Appointment\",\"Qmatic - AppointmentArrivalStatus\",\"Qmatic - AppointmentService\",\"Qmatic - AppointmentStatus\",\"Qmatic - StaffSession\",\"Qmatic - StaffSessionOutcome\",\"Drives - DL Fee Waiver Tracking\",\"DC - User\",\"YFM - Your_Feedback_Matters_v3\",\"YFM - Your_Feedback_Matters_v4\",\"YFM - Your Feedback Matters\",\"Feedback_V3_Path\",\"Sample V3\",\"Transform_Your_Feedback_Matters_V3\",\"YFM - SearchForTerm\",\"YFM - StopWords\",\"Feedback_V4_Path\",\"Sample File v4\",\"Transform_Your_Feedback_Matters_V4\",\"Pay Type JDE\",\"Persion Time Sample File\",\"Personal File Parameter\",\"Transform Personal File\",\"Transform Personal File Sample\",\"Pay Type JDE Latest Status\",\"Audit and UAT Stats Sheets\",\"Audit and UAT Stats\",\"Audit and UAT Stats Headers\",\"Audit and UAT Stats Data\",\"datapath\",\"Transform Staff Stats CO\",\"Staff Stats - Physical Mail\",\"Staff Stats - CO Salvages\",\"Staff Stats - CO Renewals\",\"Staff Stats - CO Mortgage Mail\",\"Staff Stats - CO Business\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "BlobStorage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "\"https://dldmvprwestus3.blob.core.windows.net/datalake\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "732259f8-5cb9-4fc4-8e37-4a2b487a31c2"
      },
      {
        "name": "QueryString",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"?sv=2021-04-10&st=2022-07-06T18%3A01%3A00Z&se=2023-07-07T18%3A01%3A00Z&sr=c&sp=rl&sig=dTEhF%2FNQkjIQLa4iuxEPg%2BmIt8S4YpmrPLumd0x15J4%3D\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "e1183435-cb0e-4eae-89e3-d42edc03c1ff"
      },
      {
        "name": "SQLServerName",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"PRDCETL-MST01.dcgov.douglas.co.us\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "5621010b-d0aa-440e-979b-849c9c55934e",
        "queryGroup": "MDS"
      },
      {
        "name": "SQLServerDB",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"MDS\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c704fd96-3ccc-4023-9e08-67bc79ea9593",
        "queryGroup": "MDS"
      },
      {
        "name": "Datalake",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://dldmvprwestus3.dfs.core.windows.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2ebd0bc9-40a8-4e24-a46d-7919aeff9c98"
      },
      {
        "name": "Parameter App Summary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d97b94ed-6483-447a-94e7-b754017352b7",
        "queryGroup": "Transform File from App Summary\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(#\"Parameter App Summary\", null, true),",
          "    #\"MV-Application Summary Report -_Sheet\" = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"MV-Application Summary Report -_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Promoted Headers\", each ([Called Number] <> \"\")),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Date\", each if Text.Contains([Application Name],\"[Starting At]:\")",
          "then",
          "Text.Start(",
          "    Text.AfterDelimiter([Application Name],\"[Starting At]: \")",
          "    ,10",
          ")",
          "else null),",
          "    #\"Filled Up\" = Table.FillUp(#\"Added Custom\",{\"Date\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filled Up\", each [Called Number] <> null)",
          "in",
          "    #\"Filtered Rows1\""
        ],
        "kind": "m",
        "lineageTag": "6aa7093a-6700-4ef9-a4c3-28490783a447",
        "queryGroup": "Transform File from App Summary"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = AzureStorage.DataLake(\"https://dldmvprwestus3.dfs.core.windows.net/datalake/consumer/callmanager/applicationSummary/\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "1352c13b-53e1-4171-81c5-49c207e69d19",
        "queryGroup": "Transform File from App Summary\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Parameter App Summary\" as binary) => let",
          "    Source = Excel.Workbook(#\"Parameter App Summary\", null, true),",
          "    #\"MV-Application Summary Report -_Sheet\" = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"MV-Application Summary Report -_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Promoted Headers\", each ([Called Number] <> \"\")),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows\", \"Date\", each if Text.Contains([Application Name],\"[Starting At]:\")",
          "then",
          "Text.Start(",
          "    Text.AfterDelimiter([Application Name],\"[Starting At]: \")",
          "    ,10",
          ")",
          "else null),",
          "    #\"Filled Up\" = Table.FillUp(#\"Added Custom\",{\"Date\"}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filled Up\", each [Called Number] <> null)",
          "in",
          "    #\"Filtered Rows1\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "d5e24932-100c-454d-9074-42a96d25653d",
        "queryGroup": "Transform File from App Summary\\Helper Queries"
      },
      {
        "name": "Parameter AgentSummary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample AgentSummary\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample AgentSummary\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "48feae8b-a8fa-420a-8882-28c7d73b21f8",
        "queryGroup": "Transform File from Agent Summary\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(#\"Parameter AgentSummary\", null, true),",
          "    #\"MV-Agent Call Summary Report - _Sheet\" = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"MV-Agent Call Summary Report - _Sheet\", each ([Column2] <> \"\")),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",null,\"\",Replacer.ReplaceValue,{\"Column1\"}),",
          "    #\"Transposed Table2\" = Table.Transpose(#\"Replaced Value\"),",
          "    #\"Merged Columns1\" = Table.CombineColumns(#\"Transposed Table2\",{\"Column1\", \"Column2\"},Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None),\"Columns\"),",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Merged Columns1\",{{\"Columns\", Text.Trim, type text}}),",
          "    #\"Transposed Table\" = Table.Transpose(#\"Trimmed Text\"),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Transposed Table\", [PromoteAllScalars=true]),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Promoted Headers\", \"Date\", each if Text.Contains([Agent Name],\"[Starting At]:\")",
          "then",
          "Text.Start(",
          "    Text.AfterDelimiter([Agent Name],\"[Starting At]: \")",
          "    ,10",
          ")",
          "else null),",
          "    #\"Filled Up\" = Table.FillUp(#\"Added Custom\",{\"Date\"}),",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filled Up\", each [Agent ID] <> null),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows2\",{{\"Date\", type date}, {\"Conference\", Int64.Type}, {\"Transfer Out\", Int64.Type}, {\"ACD Transfer In\", Int64.Type}, {\"Outbound On Non-IPCC Total\", Int64.Type}, {\"Avg Talk Time_4\", Int64.Type}, {\"Max Talk Time_5\", Int64.Type}, {\"Max Call Time_3\", type number}, {\"Avg Call Time_2\", type number}, {\"Outbound On IPCC Total\", Int64.Type}, {\"Max Call Time\", Int64.Type}, {\"Avg Call Time\", Int64.Type}, {\"Inbound Non-ACD On Non-IPCC Total\", Int64.Type}, {\"Max Talk Time\", type number}, {\"Avg Talk Time_1\", type number}, {\"Inbound Non-ACD On IPCC Total\", Int64.Type}, {\"Avg Work Time\", type number}, {\"Avg Hold Time\", type number}, {\"Avg Talk Time\", type number}, {\"Inbound ACD Total\", Int64.Type}, {\"Total Inbound\", Int64.Type}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "f2677191-0dac-423b-8dd4-10d5711485c9",
        "queryGroup": "Transform File from Agent Summary"
      },
      {
        "name": "Sample AgentSummary",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = AzureStorage.DataLake(\"https://dldmvprwestus3.dfs.core.windows.net/datalake/consumer/callmanager/agentCallSummary\"),",
          "    Navigation1 = Source{0}[Content]",
          "    //#\"Imported Excel Workbook\" = Excel.Workbook(Navigation1)",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "4c557e87-b66c-48d5-899f-84a7fa639fab",
        "queryGroup": "Transform File from Agent Summary\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Parameter AgentSummary\" as binary) => let",
          "    Source = Excel.Workbook(#\"Parameter AgentSummary\", null, true),",
          "    #\"MV-Agent Call Summary Report - _Sheet\" = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"MV-Agent Call Summary Report - _Sheet\", each ([Column2] <> \"\")),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",null,\"\",Replacer.ReplaceValue,{\"Column1\"}),",
          "    #\"Transposed Table2\" = Table.Transpose(#\"Replaced Value\"),",
          "    #\"Merged Columns1\" = Table.CombineColumns(#\"Transposed Table2\",{\"Column1\", \"Column2\"},Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None),\"Columns\"),",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Merged Columns1\",{{\"Columns\", Text.Trim, type text}}),",
          "    #\"Transposed Table\" = Table.Transpose(#\"Trimmed Text\"),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Transposed Table\", [PromoteAllScalars=true]),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Promoted Headers\", \"Date\", each if Text.Contains([Agent Name],\"[Starting At]:\")",
          "then",
          "Text.Start(",
          "    Text.AfterDelimiter([Agent Name],\"[Starting At]: \")",
          "    ,10",
          ")",
          "else null),",
          "    #\"Filled Up\" = Table.FillUp(#\"Added Custom\",{\"Date\"}),",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filled Up\", each [Agent ID] <> null),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows2\",{{\"Date\", type date}, {\"Conference\", Int64.Type}, {\"Transfer Out\", Int64.Type}, {\"ACD Transfer In\", Int64.Type}, {\"Outbound On Non-IPCC Total\", Int64.Type}, {\"Avg Talk Time_4\", Int64.Type}, {\"Max Talk Time_5\", Int64.Type}, {\"Max Call Time_3\", type number}, {\"Avg Call Time_2\", type number}, {\"Outbound On IPCC Total\", Int64.Type}, {\"Max Call Time\", Int64.Type}, {\"Avg Call Time\", Int64.Type}, {\"Inbound Non-ACD On Non-IPCC Total\", Int64.Type}, {\"Max Talk Time\", type number}, {\"Avg Talk Time_1\", type number}, {\"Inbound Non-ACD On IPCC Total\", Int64.Type}, {\"Avg Work Time\", type number}, {\"Avg Hold Time\", type number}, {\"Avg Talk Time\", type number}, {\"Inbound ACD Total\", Int64.Type}, {\"Total Inbound\", Int64.Type}})",
          "in",
          "    #\"Changed Type\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "8a77c425-f2f1-4735-92c3-76156ede4356",
        "queryGroup": "Transform File from Agent Summary\\Helper Queries"
      },
      {
        "name": "Parameter CSQ",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample CSQ\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample CSQ\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9eeee9a4-f5aa-47c8-9236-899af9762307",
        "queryGroup": "Transform File from Query1\\Helper Queries"
      },
      {
        "name": "Transform Sample File (3)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(#\"Parameter CSQ\", null, true),",
          "    #\"MV - Common Skill CSQ Activity _Sheet\" = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"MV - Common Skill CSQ Activity _Sheet\", each ([Column2] <> \"\")),",
          "    #\"Filled Up\" = Table.FillUp(#\"Filtered Rows\",{\"Column6\", \"Column7\", \"Column9\", \"Column10\", \"Column12\", \"Column13\"}),",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filled Up\", each ([Column2] <> null)),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Filtered Rows2\", [PromoteAllScalars=true]),",
          "    #\"Filled Down\" = Table.FillDown(#\"Promoted Headers\",{\"Skills\"})",
          "in",
          "    #\"Filled Down\""
        ],
        "kind": "m",
        "lineageTag": "256dc8c7-245f-4e1f-9596-0674196a58ed",
        "queryGroup": "Transform File from Query1"
      },
      {
        "name": "Sample CSQ",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = AzureStorage.DataLake(\"https://dldmvprwestus3.dfs.core.windows.net/datalake/consumer/callmanager/commonSkillCSQ\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "ca559dd0-0256-48d6-afcf-0e67d464c38e",
        "queryGroup": "Transform File from Query1\\Helper Queries"
      },
      {
        "name": "Transform File (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Parameter CSQ\" as binary) => let",
          "    Source = Excel.Workbook(#\"Parameter CSQ\", null, true),",
          "    #\"MV - Common Skill CSQ Activity _Sheet\" = Source{[Item=Source{0}[Item],Kind=\"Sheet\"]}[Data],",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"MV - Common Skill CSQ Activity _Sheet\", each ([Column2] <> \"\")),",
          "    #\"Filled Up\" = Table.FillUp(#\"Filtered Rows\",{\"Column6\", \"Column7\", \"Column9\", \"Column10\", \"Column12\", \"Column13\"}),",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filled Up\", each ([Column2] <> null)),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Filtered Rows2\", [PromoteAllScalars=true]),",
          "    #\"Filled Down\" = Table.FillDown(#\"Promoted Headers\",{\"Skills\"})",
          "in",
          "    #\"Filled Down\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "0504aff4-b686-4a87-89aa-cff626eaad01",
        "queryGroup": "Transform File from Query1\\Helper Queries"
      },
      {
        "name": "Qmatic - Branch",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"Qmatic - File List\",",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"Branch.pq\")),",
          "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
          "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
          "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
          "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
          "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(Underscore,{\"Id\", \"Country\", \"City\", \"Latitude\", \"Time Zone\", \"Branch\", \"Longitude\"})",
          "in",
          "    #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "e5f7a57a-4938-4858-b21c-51a9e4ab34d9",
        "queryGroup": "Qmatic"
      },
      {
        "name": "Transform Staff Stats Sheet 2022",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Data\" as table, #\"SheetName\" as text) => let",
          "    //Source = Excel.Workbook(#\"Data\", null, true),",
          "    //#\"Sheet\" = Source{[Item=#\"SheetName\",Kind=\"Sheet\"]}[Data],",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Data\", each ([Column2] <> \"Totals\")),",
          "    #\"Filled Down\" = Table.FillDown(#\"Filtered Rows\",{\"Column1\"}),",
          "    #\"Removed Top Rows\" = Table.Skip(#\"Filled Down\",3),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Top Rows\", each ([Column2] <> null and [Column2] <> \"C/O\")),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"})",
          "in",
          "    #\"Removed Other Columns\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "2fa426f9-f29b-42cc-8e8a-c1eea78d02ff",
        "queryGroup": "Staff Stats\\Staff Stats Function\\Transform Staff Stats Sheet"
      },
      {
        "name": "Transform Staff Stats Sheet 2021",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Data\" as table, #\"SheetName\" as text) => let",
          "    //Source = Excel.Workbook(#\"Data\", null, true),",
          "    //#\"Sheet\" = Source{[Item=#\"SheetName\",Kind=\"Sheet\"]}[Data],",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Data\", each ([Column2] <> \"Totals\")),",
          "    #\"Filled Down\" = Table.FillDown(#\"Filtered Rows\",{\"Column1\"}),",
          "    #\"Removed Top Rows\" = Table.Skip(#\"Filled Down\",3),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Top Rows\", each ([Column2] <> null and [Column2] <> \"C/O\"))//,",
          "    //#\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"})",
          "in",
          "    #\"Filtered Rows1\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "3a6ad025-3df5-4461-ab69-3fcff89ccef5",
        "queryGroup": "Staff Stats\\Staff Stats Function\\Transform Staff Stats Sheet"
      },
      {
        "name": "SnapFileMain",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(file as text) =>",
          "",
          "let",
          "",
          "    #\"Imported JSON\" = Json.Document(file,1252),",
          "    cases = #\"Imported JSON\"[cases],",
          "    #\"Converted to Table\" = Table.FromList(cases, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"url\", \"type\", \"requested_by\", \"description\", \"created_at_date\", \"created_at_seconds\", \"created_at_milliseconds\", \"proactive_chat\", \"page_url\", \"referrer_url\", \"entry_url\", \"ip_address\", \"user_agent\", \"browser\", \"os\", \"country_code\", \"country\", \"region\", \"city\", \"latitude\", \"longitude\", \"source_id\", \"chat_waittime\", \"chat_duration\", \"chat_responded\", \"chat_agent_id\", \"chat_agent_alias\", \"survey_score\", \"survey_comments\", \"language_code\", \"transcripts\", \"operator_variables\", \"labels\", \"destination_url\"}, {\"id\", \"url\", \"type\", \"requested_by\", \"description\", \"created_at_date\", \"created_at_seconds\", \"created_at_milliseconds\", \"proactive_chat\", \"page_url\", \"referrer_url\", \"entry_url\", \"ip_address\", \"user_agent\", \"browser\", \"os\", \"country_code\", \"country\", \"region\", \"city\", \"latitude\", \"longitude\", \"source_id\", \"chat_waittime\", \"chat_duration\", \"chat_responded\", \"chat_agent_id\", \"chat_agent_alias\", \"survey_score\", \"survey_comments\", \"language_code\", \"transcripts\", \"operator_variables\", \"labels\", \"destination_url\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded Column1\",{\"transcripts\", \"operator_variables\", \"labels\"})",
          "in",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "dbaebe73-03b3-4ffa-af62-f1058810e30b",
        "queryGroup": "SnapEngage"
      },
      {
        "name": "SnapBinarytoText",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(Content as binary) =>",
          "",
          "let",
          "    Source = Table.FromColumns({Lines.FromBinary(Content,null,null,1252)})",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "9675f84c-1d84-4d62-b2b4-9e27aa10af18",
        "queryGroup": "SnapEngage"
      },
      {
        "name": "SnapFileChats",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (file as text) =>",
          "",
          "    let",
          "        #\"Imported JSON\" = Json.Document(file,1252),",
          "        cases = #\"Imported JSON\"[cases],",
          "        #\"Converted to Table\" = Table.FromList(cases, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "        #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"id\", \"url\", \"type\", \"requested_by\", \"description\", \"created_at_date\", \"created_at_seconds\", \"created_at_milliseconds\", \"proactive_chat\", \"page_url\", \"referrer_url\", \"entry_url\", \"ip_address\", \"user_agent\", \"browser\", \"os\", \"country_code\", \"country\", \"region\", \"city\", \"latitude\", \"longitude\", \"source_id\", \"chat_waittime\", \"chat_duration\", \"chat_responded\", \"chat_agent_id\", \"chat_agent_alias\", \"language_code\", \"transcripts\", \"operator_variables\", \"labels\", \"destination_url\"}, {\"id\", \"url\", \"type\", \"requested_by\", \"description\", \"created_at_date\", \"created_at_seconds\", \"created_at_milliseconds\", \"proactive_chat\", \"page_url\", \"referrer_url\", \"entry_url\", \"ip_address\", \"user_agent\", \"browser\", \"os\", \"country_code\", \"country\", \"region\", \"city\", \"latitude\", \"longitude\", \"source_id\", \"chat_waittime\", \"chat_duration\", \"chat_responded\", \"chat_agent_id\", \"chat_agent_alias\", \"language_code\", \"transcripts\", \"operator_variables\", \"labels\", \"destination_url\"}),",
          "        #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded Column1\",{\"url\", \"type\", \"requested_by\", \"description\", \"created_at_date\", \"created_at_seconds\", \"created_at_milliseconds\", \"proactive_chat\", \"page_url\", \"referrer_url\", \"entry_url\", \"ip_address\", \"user_agent\", \"browser\", \"os\", \"country_code\", \"country\", \"region\", \"city\", \"latitude\", \"longitude\", \"source_id\", \"chat_waittime\", \"chat_duration\", \"chat_responded\", \"chat_agent_id\", \"chat_agent_alias\", \"language_code\", \"operator_variables\", \"labels\", \"destination_url\"}),",
          "        #\"Expanded transcripts\" = Table.ExpandListColumn(#\"Removed Columns\", \"transcripts\"),",
          "        #\"Expanded transcripts1\" = Table.ExpandRecordColumn(#\"Expanded transcripts\", \"transcripts\", {\"id\", \"date\", \"date_seconds\", \"date_milliseconds\", \"alias\", \"message\", \"sender\", \"whisperMessage\"}, {\"id.1\", \"date\", \"date_seconds\", \"date_milliseconds\", \"alias\", \"message\", \"sender\", \"whisperMessage\"})",
          "    in",
          "        #\"Expanded transcripts1\"",
          "in ",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "a54aaafd-2fc4-4a31-923c-551a712dd094",
        "queryGroup": "SnapEngage"
      },
      {
        "name": "Feedback_V3_Path",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"\\\\prfsdept\\common\\CLERK & RECORDER\\0Your_Feedback_Matters\\\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2281cca5-cbf0-4382-a75b-95240de5f390",
        "queryGroup": "Your Feedback Matters\\v3"
      },
      {
        "name": "Sample V3",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(Feedback_V3_Path & \"data_v3\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "699908bb-997c-48f0-b739-aa9bb69fa067",
        "queryGroup": "Your Feedback Matters\\v3"
      },
      {
        "name": "Transform_Your_Feedback_Matters_V3",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Feedback_V3 as binary) => let",
          "    Source = Csv.Document(Feedback_V3,[Delimiter=\",\", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "761cae92-071d-4990-ac82-cae2964a25fb",
        "queryGroup": "Your Feedback Matters\\v3"
      },
      {
        "name": "Feedback_V4_Path",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"\\\\prfsdept\\common\\CLERK & RECORDER\\0Your_Feedback_Matters\\\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "4835223a-39c9-4aac-9df6-f9e97d90fe58",
        "queryGroup": "Your Feedback Matters\\v4"
      },
      {
        "name": "Sample File v4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(Feedback_V4_Path & \"data_v4\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "0a4a2c7a-dd7f-4548-9007-65cdc66278ce",
        "queryGroup": "Your Feedback Matters\\v4"
      },
      {
        "name": "Transform_Your_Feedback_Matters_V4",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter4 as binary) => let",
          "    Source = Csv.Document(Parameter4,[Delimiter=\",\", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b88f8bae-a4ef-4444-a7e5-b34fed9a1746",
        "queryGroup": "Your Feedback Matters\\v4"
      },
      {
        "name": "Persion Time Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = AzureStorage.DataLake(Datalake & \"/datalake/consumer/HourlyPayReport/\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "0d3838d5-d6f6-4ac2-93ef-67b1ce682f07",
        "queryGroup": "Personal Time\\Transform Personal Time"
      },
      {
        "name": "Personal File Parameter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Persion Time Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Persion Time Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "862b9304-f416-4281-acd0-4ef2e483ac12",
        "queryGroup": "Personal Time\\Transform Personal Time"
      },
      {
        "name": "Transform Personal File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Personal File Parameter\" as binary) => let",
          "    Source = Excel.Workbook(#\"Personal File Parameter\", null, true),",
          "    Sheet1_Sheet = Source{0}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Hours \", type number}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Pay Check Date\", \"Check Date\"}}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Check Date\", type date}})",
          "in",
          "    #\"Changed Type1\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "a3029e30-0bc6-4fc7-aad7-66b8ce671238",
        "queryGroup": "Personal Time\\Transform Personal Time"
      },
      {
        "name": "Transform Personal File Sample",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(#\"Personal File Parameter\", null, true),",
          "    Sheet1_Sheet = Source{0}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Hours \", type number}}),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Pay Check Date\", \"Check Date\"}}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Check Date\", type date}})",
          "in",
          "    #\"Changed Type1\""
        ],
        "kind": "m",
        "lineageTag": "1fb48be5-474f-4a73-a204-9a19cb7dd8d1",
        "queryGroup": "Personal Time\\Transform Personal Time"
      },
      {
        "name": "Qmatic - File List",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/qmatic/\")",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "c26b48ae-f906-4a19-a00c-5b326ef776a5",
        "queryGroup": "Qmatic"
      },
      {
        "name": "datapath",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"dv/\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "736e438e-b8a2-4f80-bb1e-bae27ff8985f"
      },
      {
        "name": "Transform Staff Stats CO",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (#\"Data\" as table, #\"SheetName\" as text) => let",
          "    //Source = Excel.Workbook(#\"Data\", null, true),",
          "    //#\"Sheet\" = Source{[Item=#\"SheetName\",Kind=\"Sheet\"]}[Data],",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Data\", each ([Column2] <> \"Totals\")),",
          "    #\"Filled Down\" = Table.FillDown(#\"Filtered Rows\",{\"Column1\"}),",
          "    #\"Removed Top Rows\" = Table.Skip(#\"Filled Down\",3),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Removed Top Rows\", each ([Column2] <> null and [Column2] = \"C/O\")),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows1\",{\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"})",
          "in",
          "    #\"Removed Other Columns\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "ef325541-f0ea-4b53-88d2-20cc67f92e7b",
        "queryGroup": "Staff Stats\\Staff Stats Function\\Transform Staff Stats Sheet"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from App Summary"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from App Summary\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Transform File from Agent Summary"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Agent Summary\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transform File from Query1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from Query1\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Qmatic"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Drives"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "Call Manager"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "DC"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "9"
          }
        ],
        "folder": "MDS"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "7"
          }
        ],
        "folder": "Staff Stats"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "11"
          }
        ],
        "folder": "SnapEngage"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "12"
          }
        ],
        "folder": "Your Feedback Matters"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Your Feedback Matters\\v3"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Your Feedback Matters\\v4"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "13"
          }
        ],
        "folder": "Personal Time"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Personal Time\\Transform Personal Time"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Staff Stats\\Staff Stats Function"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Staff Stats\\Staff Stats Function\\Transform Staff Stats Sheet"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "24"
          }
        ],
        "folder": "Audit and UAT Stats"
      }
    ],
    "relationships": [
      {
        "name": "f69ba663-a698-4cc5-9380-7c3c203fd546",
        "fromColumn": "Type",
        "fromTable": "Drives - Time Tracking",
        "toColumn": "TypeCode",
        "toTable": "mdm MVTypeCategory"
      },
      {
        "name": "a2a94eda-9572-474b-87ef-18f97e783697",
        "fromColumn": "Entry Point Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Entry Point"
      },
      {
        "name": "99158522-4d3b-45e3-9e14-8829f8f1c9b8",
        "fromColumn": "Queue Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Queue"
      },
      {
        "name": "c56f9772-2f24-4034-9b00-a618a358e713",
        "fromColumn": "Queue Type Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Queue Type"
      },
      {
        "name": "5c3ebccf-7e94-439a-b344-948fa7931e12",
        "fromColumn": "Service Point Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Service Point"
      },
      {
        "name": "45c48c77-024d-4078-8d46-5db0ac3039b7",
        "fromColumn": "Staff Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Staff"
      },
      {
        "name": "569ee4df-7c7d-49ce-83b8-d41b8271e8b5",
        "fromColumn": "Visit Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Visit"
      },
      {
        "name": "9457be51-e184-4f1d-a63b-64a9d0a09e55",
        "fromColumn": "End Time Key",
        "fromTable": "Qmatic - Visit Transaction",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - End Time"
      },
      {
        "name": "cd196a3a-671c-49f6-9c4d-ca0dacbb5324",
        "fromColumn": "Entered Queue Time Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Entered Queue Time"
      },
      {
        "name": "16eabe34-7773-4f17-a35c-4e7c40cc2317",
        "fromColumn": "Visit Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Visit Call Type"
      },
      {
        "name": "60b9e4a1-5f84-4db0-95b4-4649082c51c7",
        "fromColumn": "Visit Outcome Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Visit Transaction Outcome"
      },
      {
        "name": "01be0653-c7f3-4e0c-b47c-be7b0a2ec507",
        "fromColumn": "Service Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "Id",
        "toTable": "Qmatic - Service"
      },
      {
        "name": "1ab5c529-23b6-4e02-a14a-61ce98a2583d",
        "fromColumn": "LocationId",
        "fromTable": "Drives - Financials",
        "toColumn": "LocationId",
        "toTable": "DC - Location"
      },
      {
        "name": "c22754f9-86ec-413a-a61f-f23bdc479b09",
        "fromColumn": "LocationId",
        "fromTable": "Drives - Title Application Errors",
        "toColumn": "LocationId",
        "toTable": "DC - Location"
      },
      {
        "name": "5efc3af6-7058-4762-8d5e-e8efa03a48c9",
        "fromColumn": "LocationId",
        "fromTable": "Drives - Fee Waiver Tracking",
        "toColumn": "LocationId",
        "toTable": "DC - Location"
      },
      {
        "name": "28fdc063-cdd0-4f84-953f-9b6a933e5abe",
        "fromColumn": "OrgId",
        "fromTable": "Drives - Time Tracking",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "811db17c-1b58-4d66-b5e3-61aebc88deff",
        "fromColumn": "OrgId",
        "fromTable": "Drives - Title Application Errors",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "3efa9edf-04bb-44e9-9528-fc17d4ce62ec",
        "fromColumn": "OrgId",
        "fromTable": "Drives - Fee Statistics",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "809f5068-d132-424e-bf67-ce7f29255f0b",
        "fromColumn": "OrgId",
        "fromTable": "Drives - Financials",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "5fa947eb-7e92-43c2-b281-58880bba37d9",
        "fromColumn": "OrgId",
        "fromTable": "Drives - Fee Waiver Tracking",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "3e3b1f5d-6d32-45a9-9073-9d53db7ef515",
        "fromColumn": "OrgId",
        "fromTable": "Call Manager - Common Skill CSQ",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "b7b8b142-eff6-4398-b362-28ee9d09c80c",
        "fromColumn": "Staff",
        "fromTable": "Qmatic - Staff",
        "toColumn": "Staff",
        "toTable": "Qmatic - Staff Group by"
      },
      {
        "name": "0a087787-a586-4c62-acf8-b93d711ba369",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Code",
        "fromTable": "MDS - SnapEngage Chat Agent Id",
        "toColumn": "Code",
        "toTable": "DC - User"
      },
      {
        "name": "0dd82ad5-4015-4069-b881-e9aeef3f2289",
        "fromColumn": "Agent ID",
        "fromTable": "Call Manager - Agent Call Summary",
        "toColumn": "CallManagerAgentId",
        "toTable": "DC - User"
      },
      {
        "name": "31d3247e-3215-47ac-91f1-b485dd824017",
        "fromColumn": "DCUserId",
        "fromTable": "Qmatic - Staff",
        "toColumn": "QmaticUserId",
        "toTable": "DC - User"
      },
      {
        "name": "3bc51b17-335e-434e-8c4c-a5eabb550e75",
        "fromColumn": "User",
        "fromTable": "Drives - Time Tracking",
        "toColumn": "DrivesUserId",
        "toTable": "DC - User"
      },
      {
        "name": "65a36bf6-142a-4236-b500-70c2441e729e",
        "fromColumn": "Original User Id",
        "fromTable": "Drives - Title Application Errors",
        "toColumn": "DrivesUserId",
        "toTable": "DC - User"
      },
      {
        "name": "e4e7ff0a-6198-49be-b3b1-f9a27cb6fe25",
        "fromColumn": "Cashier",
        "fromTable": "Drives - Fee Waiver Tracking",
        "toColumn": "DrivesUserId",
        "toTable": "DC - User"
      },
      {
        "name": "38203352-6c99-4f38-a425-f027a91a4132",
        "fromColumn": "Cashier",
        "fromTable": "Drives - Financials",
        "toColumn": "DrivesFinancialsUserId",
        "toTable": "DC - User"
      },
      {
        "name": "3b3fb3e8-77b6-4e52-aa1e-591991eb7255",
        "fromColumn": "LocationId",
        "fromTable": "Drives - Time Tracking",
        "toColumn": "LocationId",
        "toTable": "DC - Location"
      },
      {
        "name": "60450c54-44e2-4a78-be2b-20d421b4b910",
        "fromColumn": "LocationId",
        "fromTable": "Drives - Fee Statistics",
        "toColumn": "LocationId",
        "toTable": "DC - Location"
      },
      {
        "name": "2281ef1c-90f5-47fb-9ce8-0596e8ccaf21",
        "fromColumn": "Id",
        "fromTable": "SnapEngageChat",
        "toColumn": "Id",
        "toTable": "SnapEngage"
      },
      {
        "name": "aac6e759-6257-4aef-8748-467807aa50b9",
        "fromColumn": "Branch Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "QmaticBranchId",
        "toTable": "DC - Location"
      },
      {
        "name": "50c55391-b82d-4498-8d37-9232ca2d5419",
        "fromColumn": "OrgId",
        "fromTable": "Qmatic - Service",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "b0209c63-9928-4cb9-974e-7c84013fb681",
        "fromColumn": "Appointment Status Key",
        "fromTable": "Qmatic - Appointment",
        "toColumn": "Id",
        "toTable": "Qmatic - AppointmentStatus"
      },
      {
        "name": "f5b508e8-5c49-4c52-8645-83bc52f0752b",
        "fromColumn": "Arrival Status Key",
        "fromTable": "Qmatic - Appointment",
        "toColumn": "Id",
        "toTable": "Qmatic - AppointmentArrivalStatus"
      },
      {
        "name": "641115b5-430f-4569-9980-fba9df4a5424",
        "fromColumn": "Service Key",
        "fromTable": "Qmatic - AppointmentService",
        "toColumn": "Id",
        "toTable": "Qmatic - Service"
      },
      {
        "name": "f1d4dd5b-3f42-44a6-b60c-a0c0b35c99ac",
        "fromColumn": "Appointment Id",
        "fromTable": "Qmatic - AppointmentService",
        "toColumn": "Id",
        "toTable": "Qmatic - Appointment"
      },
      {
        "name": "76440a0d-0a12-4924-9f09-df09b5a3f7f4",
        "fromColumn": "Branch Key",
        "fromTable": "Qmatic - Appointment",
        "toColumn": "QmaticBranchId",
        "toTable": "DC - Location"
      },
      {
        "name": "9123b754-515c-402c-8e3a-a8f0309313a5",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - StaffSessionOutcome",
        "toColumn": "Id",
        "toTable": "Qmatic - AppointmentStatus"
      },
      {
        "name": "9c8be609-96e9-4786-99f7-951132c36b43",
        "fromColumn": "Branch Key",
        "fromTable": "Qmatic - StaffSession",
        "toColumn": "QmaticBranchId",
        "toTable": "DC - Location"
      },
      {
        "name": "452b9f1e-7bad-4eb4-bba4-f28b1c066e99",
        "fromColumn": "Session Outcome Key",
        "fromTable": "Qmatic - StaffSession",
        "toColumn": "Id",
        "toTable": "Qmatic - StaffSessionOutcome"
      },
      {
        "name": "482d37a3-e694-4738-baa9-8181b48515db",
        "fromColumn": "Staff Key",
        "fromTable": "Qmatic - StaffSession",
        "toColumn": "QmaticUserId",
        "toTable": "DC - User"
      },
      {
        "name": "e288cf39-1383-41db-b543-74fe26e79d2b",
        "fromColumn": "OrgId",
        "fromTable": "Drives - DL Fee Waiver Tracking",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "99f28583-b861-48d4-af02-b9319137cf6a",
        "fromColumn": "Chat Agent Id",
        "fromTable": "SnapEngage",
        "toColumn": "SnapengageAgentId",
        "toTable": "DC - User"
      },
      {
        "name": "294145ab-b866-4476-878d-711eb16383c4",
        "fromColumn": "OrgId",
        "fromTable": "SnapEngage",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "58b908e3-a7cc-4d59-aa77-93d27480047d",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "toColumn": "Id",
        "toTable": "Qmatic - Staff"
      },
      {
        "name": "b8617445-df84-485b-b049-f4e9c110ac1e",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - Queue"
      },
      {
        "name": "8045f09c-4413-4bd3-a0e6-27c8587bf4b5",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - Service Point"
      },
      {
        "name": "d985f8cb-8635-4671-ab3a-5be66f6eea85",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - Service"
      },
      {
        "name": "dfd63b72-d5bd-41af-a66b-cfb3962a0ac6",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - Entry Point"
      },
      {
        "name": "80d0c72a-29be-411c-b87c-c479a1594320",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - Visit Transaction Outcome"
      },
      {
        "name": "008df12a-d77c-442d-bd0d-9971bcdcb7a0",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "toColumn": "Id",
        "toTable": "Qmatic - AppointmentStatus"
      },
      {
        "name": "96e0e69d-e95f-42e6-8387-73cc24360d22",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - Queue Type"
      },
      {
        "name": "4c364af2-e192-498b-a095-30885260aac5",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "toColumn": "Id",
        "toTable": "Qmatic - AppointmentArrivalStatus"
      },
      {
        "name": "04706d69-1568-4131-9e5c-ad012d490425",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Id",
        "fromTable": "Qmatic - Work Profile",
        "isActive": false,
        "toColumn": "Id",
        "toTable": "Qmatic - Visit Call Type"
      },
      {
        "name": "592716ee-ffd1-41e4-92ab-f85a6b71c781",
        "fromColumn": "OrgId",
        "fromTable": "YFM - Your Feedback Matters",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "aa63dec3-e961-49f3-a22e-bed638e5bd56",
        "fromColumn": "OrgId",
        "fromTable": "Pay Type JDE",
        "toColumn": "OrgId",
        "toTable": "DC - Division"
      },
      {
        "name": "e3db51ac-dc38-4c61-adf8-76970f721683",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "FeedbackId",
        "fromTable": "YFM - Your_Feedback_Matters_v4",
        "toColumn": "FeedbackId",
        "toTable": "YFM - Your_Feedback_Matters_v3"
      },
      {
        "name": "573ed7dd-e9f7-4d68-83c6-87610d924f3a",
        "fromColumn": "Email Address",
        "fromTable": "Pay Type JDE",
        "toColumn": "Code",
        "toTable": "DC - User"
      },
      {
        "name": "938f7529-46e0-b193-6d71-11e4bae10fda",
        "fromColumn": "Staff",
        "fromTable": "Audit and UAT Stats",
        "toColumn": "Code",
        "toTable": "DC - User"
      },
      {
        "name": "02ac2873-71f6-8546-54c7-0c1d617e020a",
        "fromColumn": "Clerk",
        "fromTable": "Staff Stats - Physical Mail",
        "toColumn": "DrivesUserId",
        "toTable": "DC - User"
      },
      {
        "name": "b290bdbc-bdfc-a348-867c-262466ea3edf",
        "fromColumn": "Date",
        "fromTable": "Date",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "DC - Closure"
      },
      {
        "name": "484c29f8-1ea0-4849-88f2-48ec8ba8d29a",
        "fromColumn": "Transaction Date",
        "fromTable": "Drives - Time Tracking",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "5f98f425-c293-482a-8921-ae87c60e41f2",
        "fromColumn": "Drawer Date",
        "fromTable": "Drives - Financials",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "d0a73430-ca10-44b1-8983-71a2b6df4623",
        "fromColumn": "Date",
        "fromTable": "Drives - Title Application Errors",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "997d9cca-19d8-475c-8acb-a986740f2d1e",
        "fromColumn": "Date",
        "fromTable": "Call Manager - App Summary",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "f783041a-361a-4661-b07a-e50d0b8aa509",
        "fromColumn": "Date",
        "fromTable": "Call Manager - Agent Call Summary",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "544c1f6c-30db-4703-9870-4e44d0c41c44",
        "fromColumn": "Interval Date",
        "fromTable": "Call Manager - Common Skill CSQ",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "d6d4618a-f181-405c-9271-fde39202f436",
        "fromColumn": "Transaction Date",
        "fromTable": "Drives - Fee Statistics",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "da9ba6b1-86f7-4713-b664-b0edbe5b7e9b",
        "fromColumn": "Date Of Transaction",
        "fromTable": "Drives - Fee Waiver Tracking",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "9549c503-9704-4c8e-b5f1-237573cfe1f9",
        "fromColumn": "Date Recieved",
        "fromTable": "Staff Stats - Mail Rejects",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "4aec8fa3-789b-4b42-877b-0d488225c810",
        "fromColumn": "FeedbackDate",
        "fromTable": "YFM - Your Feedback Matters",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "1e4ca7bd-d183-4255-8b20-b6977a0a36bc",
        "fromColumn": "Check Date",
        "fromTable": "Pay Type JDE",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "f394cd45-0c3f-769e-5371-d4fcc69bc19c",
        "fromColumn": "Date",
        "fromTable": "Audit and UAT Stats",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "67a837ba-9cef-b726-b9e5-965b10e66077",
        "fromColumn": "Date Recieved",
        "fromTable": "Staff Stats - Salvage Rejects",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "9bd0abb9-35ad-5f8b-cfe3-ecbf0a482340",
        "fromColumn": "Date",
        "fromTable": "Staff Stats - CO Salvages",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "36a885c6-5aaf-2533-b6d9-4a85155002c7",
        "fromColumn": "Date",
        "fromTable": "Staff Stats - CO Business",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "aa27962e-2d8b-53b1-2f49-acbc5020a7aa",
        "fromColumn": "Date",
        "fromTable": "Staff Stats - CO Renewals",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "eae75370-b907-1b79-f87e-2c228cdb2e02",
        "fromColumn": "Date",
        "fromTable": "Staff Stats - CO Mortgage Mail",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "95174907-db66-46c4-8b3d-4982b13b095b",
        "fromColumn": "Date Key",
        "fromTable": "Qmatic - Visit Transaction",
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "c468139f-508e-4a44-8c6c-63fb336e260c",
        "fromColumn": "DateKey",
        "fromTable": "SnapEngage",
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "06e360d5-3ca3-4868-a8ab-40e0a0f71626",
        "fromColumn": "Created Date Key",
        "fromTable": "Qmatic - Appointment",
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "56008736-5779-4e6f-b98b-dd1901dcd764",
        "fromColumn": "Date Key",
        "fromTable": "Qmatic - StaffSession",
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "fdf09249-ba6f-1041-86db-d6162aef51a8",
        "fromColumn": "DateKey",
        "fromTable": "Staff Stats - Physical Mail",
        "toColumn": "DateKey",
        "toTable": "Date"
      },
      {
        "name": "0869b78e-f425-7a52-8f07-f1ccdc78631d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "FakeJoin",
        "fromTable": "YFM - StopWords",
        "toCardinality": "many",
        "toColumn": "FakeJoin",
        "toTable": "YFM - Your Feedback Matters"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9310aad1276a46dea2666302fa5eedbf"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "6ae7272a-8bd4-4c72-9e78-e901ffaa5676",
            "sortByColumn": "DateKey",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "58dbf822-91aa-4160-9077-c4c789d32d3f",
            "sourceColumn": "[DateKey]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is This Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "Year(Today()) = Year('Date'[Date]) && Month(Today()) = Month('Date'[Date])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f467a66e-0df1-47c1-84ad-110ccf58980b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Is This Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "Year(Today()) = 'Date'[Year]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c6db8995-d3de-4faf-a5ad-279fec3b0842",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RelativeMonths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "Switch( ",
              "    True()",
              "    ,eomonth('Date'[Date],0) = eomonth(Today(),+1),\"Next month\" ",
              "    ,eomonth('Date'[Date],0) = eomonth(Today(),0),\"Current month\"",
              "    ,eomonth('Date'[Date],0) = eomonth(Today(),-1),\"Previous month\" ",
              "    ,Format('Date'[Date],\"MMM YYYY\")",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e47448f5-5453-4ce2-a071-2bc0d42a21bc",
            "sortByColumn": "Month of Year",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "RelativeYears",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "Switch( ",
              "    True()",
              "    ,'Date'[Year] = YEAR(Today())+1,\"Next Year\" ",
              "    ,'Date'[Year] = YEAR(Today())  ,\"Current Year\"",
              "    ,'Date'[Year] = Year(Today())-1,\"Previous Year\" ",
              "    //,\"Older\"",
              "    ,Format('Date'[Date],\"YYYY\")",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2584a4e6-58da-46cc-b3da-2d5febe9d89b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Is First Monday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b162a933-c784-4067-ad1a-81847f43972c",
            "sourceColumn": "[Is First Monday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is First Tuesday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "aa30ed98-ffae-44bf-b96c-3c19fd2876c0",
            "sourceColumn": "[Is First Tuesday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is First Wednesday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0f5236ba-db6e-407f-9f9b-17e52fcd8805",
            "sourceColumn": "[Is First Wednesday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is First Thursday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7a2f79a0-8b89-4968-8e1a-fa5c4d026221",
            "sourceColumn": "[Is First Thursday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is First Friday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8607b105-d4c5-45de-b81a-4fba6e970b0b",
            "sourceColumn": "[Is First Friday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Last Monday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "33e43a40-bc2f-4286-a777-beb8687e7066",
            "sourceColumn": "[Is Last Monday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Last Tuesdday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "120866b5-9bc9-4bb7-874b-097ea7c7e121",
            "sourceColumn": "[Is Last Tuesdday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Last Wednesday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b34b8579-5f11-4b06-80cc-8997ce6399b6",
            "sourceColumn": "[Is Last Wednesday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Last Thursday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9d8ab2a3-dbcc-40f9-8e6e-e5c1a4a8623e",
            "sourceColumn": "[Is Last Thursday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Last Friday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "97fee133-c3ae-425b-bbba-3e424f4823eb",
            "sourceColumn": "[Is Last Friday]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is First Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f24321a7-373d-4e65-a0f2-b28a8e043280",
            "sourceColumn": "[Is First Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Last Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f9aa9b8-e8ea-4a91-8d5d-1742fc4b3178",
            "sourceColumn": "[Is Last Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "58d72e32-c9cb-4206-87cf-f5fe252721fb",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Days in Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "09cf5cce-bba8-4800-a34d-778c34772a6b",
            "sourceColumn": "[Days in Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f127bdd2-6ddd-4b6e-a4d8-3ada3e97755d",
            "sourceColumn": "[Year Month Number]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f28a750a-330f-4459-bc18-04ad4da2f037",
            "sortByColumn": "Year Month Number",
            "sourceColumn": "[Month of Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9d517d1f-d197-467f-ada4-e864a34977c3",
            "sourceColumn": "[Day of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week No of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f37facb4-95f5-4c45-b7f5-4d275ca6b26d",
            "sourceColumn": "[Week No of Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "48fd3dc3-c4de-453d-ae96-2f516fb65a86",
            "sourceColumn": "[Week No]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "48e78539-3177-4d5e-8699-f9d131f8c885",
            "sourceColumn": "[Week of Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fd935da1-3b5b-4774-a8a0-345cf801079d",
            "sourceColumn": "[Week Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is DC Closure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "'Date'[DateKey] IN SUMMARIZECOLUMNS('DC - Closure'[DateKey])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b52bab54-81d9-4ee6-99d7-727e0276ede0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Is Week Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9799e742-9b97-48b0-906f-d7c8370cc627",
            "sourceColumn": "[IS Week Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Work Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "'Date'[Is DC Closure] = FALSE() && 'Date'[Is Week Day] = TRUE()",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9bdc8cf9-65c1-45bc-b4a5-1d5a41533651",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Is Middle Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "IF('Date'[Is First Week] = TRUE() || 'Date'[Is Last Week] = TRUE(), FALSE(), TRUE())",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1cb02b46-2501-42bc-88fc-1abe98cc91e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FML Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'Date'[Month] & ",
              "SWITCH( TRUE()",
              "    ,'Date'[Is First Week] = TRUE(), \" FW\"",
              "    ,'Date'[Is Last Week] = TRUE(), \" LW\"    ",
              "    , \" MW\"",
              ") "
            ],
            "isDataTypeInferred": true,
            "lineageTag": "56f4ddfc-20b8-43cf-9b0c-5e60c7484395",
            "sortByColumn": "FML Week Sort",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FML Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "'Date'[Month] & \" \" & 'Date'[Year] & ",
              "SWITCH( TRUE()",
              "    ,'Date'[Is First Week] = TRUE(), \" FW\"",
              "    ,'Date'[Is Last Week] = TRUE(), \" LW\"    ",
              "    , \" MW\"",
              ") "
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7f74045e-7ee1-4481-aab2-f1e5254fd756",
            "sortByColumn": "FLM Week of Year Sort",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FML Week Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE()",
              "    ,'Date'[Month No] = 1, 0",
              "    ,'Date'[Month No] = 2, 3",
              "    ,'Date'[Month No] = 3, 6",
              "    ,'Date'[Month No] = 4, 9",
              "    ,'Date'[Month No] = 5, 12",
              "    ,'Date'[Month No] = 6, 15",
              "    ,'Date'[Month No] = 7, 18",
              "    ,'Date'[Month No] = 8, 21",
              "    ,'Date'[Month No] = 9, 24",
              "    ,'Date'[Month No] = 10, 27",
              "    ,'Date'[Month No] = 11, 30",
              "    ,'Date'[Month No] = 12, 33",
              ")",
              " + ",
              "SWITCH( TRUE()",
              "    ,'Date'[Is First Week] = TRUE(), 1",
              "    ,'Date'[Is Last Week] = TRUE(), 3",
              "    , 2",
              ") "
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3256e514-6734-4f9d-a191-80b695f0689e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FLM Week of Year Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "((('Date'[Year] * 100) + 'Date'[Month No]) * 10) +",
              "SWITCH( TRUE()",
              "    ,'Date'[Is First Week] = TRUE(), 1",
              "    ,'Date'[Is Last Week] = TRUE(), 3",
              "    , 2",
              ") "
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "99d9fcce-5b3c-4bf3-a0f3-4b66bb631a1c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month No",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1ab789c1-9aae-4dc6-b204-d37be097ad1c",
            "sourceColumn": "[Month No]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "385dad78-1869-4fd8-8f84-21ca6b21c384",
            "sortByColumn": "Month No",
            "sourceColumn": "[Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4d63a9a0-05b8-4c8b-8e15-3d155ad9f307",
            "sourceColumn": "[Day]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day No of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "917e5bcf-46cd-4bdc-b96f-1b50f21d6483",
            "sourceColumn": "[Day No of Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b0527971-da19-4af3-9abc-5cc402f9fe89",
            "sortByColumn": "Quarter Sort",
            "sourceColumn": "[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2ed0d968-7d29-48ef-bb9f-c15d2649a41a",
            "sourceColumn": "[Quarter Sort]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "24231eef-a288-4db8-a352-aa3e527beaf3",
            "sortByColumn": "Quarter of Year Sort",
            "sourceColumn": "[Quarter of Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter of Year Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3e7d424e-26ae-471e-903c-e8f1b180c823",
            "sourceColumn": "[Quarter of Year Sort]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "FML Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "418fe3bc-ae83-45f2-92f5-31c14b11d0c1",
                "ordinal": 0
              },
              {
                "name": "Month of Year",
                "column": "Month of Year",
                "lineageTag": "7172f6d9-d75b-404d-80b9-eba16f793ab5",
                "ordinal": 1
              },
              {
                "name": "FML Week of Year",
                "column": "FML Week of Year",
                "lineageTag": "dcbef972-8259-42ad-805a-d129f7928c89",
                "ordinal": 2
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "146df916-42ac-48fd-89c2-9ea7b93bffc7",
                "ordinal": 3
              }
            ],
            "lineageTag": "6bbd2be1-7f2d-4871-b66f-57be0851d66c"
          },
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0b8149ae-4277-451a-8326-f8013c08e846",
                "ordinal": 0
              },
              {
                "name": "Quarter of Year",
                "column": "Quarter of Year",
                "lineageTag": "83dadf3d-3f53-42ce-a426-e61df5654915",
                "ordinal": 1
              },
              {
                "name": "Month of Year",
                "column": "Month of Year",
                "lineageTag": "3cfcb64a-dd72-49dc-a1cf-50d21e9aa753",
                "ordinal": 2
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "2ba44dae-4cf6-4a4b-8cd7-48aeae125b8f",
                "ordinal": 3
              }
            ],
            "lineageTag": "fd6aa060-8055-4da4-be4a-660d885d73bf"
          },
          {
            "name": "Week Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "151b9e71-693f-43ab-8313-3b5f00551e28",
                "ordinal": 0
              },
              {
                "name": "Week of Year",
                "column": "Week of Year",
                "lineageTag": "23885560-1476-4b66-ad51-f044ab6d9a19",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "efbd6432-7690-45be-a806-d371d312ece9",
                "ordinal": 2
              }
            ],
            "lineageTag": "16ff9f62-9205-48ed-942f-48167c323dbb"
          }
        ],
        "lineageTag": "44167419-ec06-4811-a766-3a6702989590",
        "measures": [
          {
            "name": "This Period Start",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": "FIRSTDATE('Date'[Date])",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "80d14730-e392-439c-8624-7299b2065506"
          },
          {
            "name": "This Period End",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": "LASTDATE('Date'[Date])",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "f7c06d5e-f4ca-4c04-8d56-74ecbce70653"
          }
        ],
        "partitions": [
          {
            "name": "Date-16904a73-91a9-4d32-a97a-a29fc20e9dc1",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "//************** Script developed by RADACAD - edition: JuActivity021 ",
                "//************** set the variables below for your custom date table setting ",
                "var _fromYear=2018 // set the start year of the date dimension. dates start from 1st of January of this year",
                "var _toYear=YEAR(TODAY() + 1)   // set the end year of the date dimension. dates end at 31st of December of this year",
                "//var _startOfFiscalYear=1 // set the month number that is start of the financial year. example; if fiscal year start is July, value is 7",
                "//************** ",
                "//var _today=TODAY()",
                "return",
                "ADDCOLUMNS(",
                "    CALENDAR(",
                "                DATE(_fromYear,1,1),",
                "                DATE(_toYear,12,31)",
                "),",
                "\"DateKey\", INT(FORMAT([Date],\"YYYYMMDD\")),",
                "\"Year\",YEAR([Date]),",
                "// \"Start of Year\",DATE( YEAR([Date]),1,1),",
                "//\"End of Year\",DATE( YEAR([Date]),12,31),",
                "\"Month No\",MONTH([Date]),",
                "//\"Start of Month\",DATE( YEAR([Date]), MONTH([Date]), 1),",
                "//\"End of Month\",EOMONTH([Date],0),",
                "\"Days in Month\",DATEDIFF(DATE( YEAR([Date]), MONTH([Date]), 1),EOMONTH([Date],0),DAY)+1,",
                "\"Year Month Number\",INT(FORMAT([Date],\"YYYYMM\")),",
                "\"Month of Year\",FORMAT([Date],\"MMM YYYY\"),",
                "//\"Month Name\",FORMAT([Date],\"MMMM\"),",
                "\"Month\",FORMAT([Date],\"MMM\"),",
                "// \"Day\",DAY([Date]),",
                "\"Day\",FORMAT([Date],\"DDD\"),",
                "\"Day of Week\",WEEKDAY([Date]),",
                "\"Is Week Day\",NOT WEEKDAY([Date]) in {1,7},",
                "\"Day No of Year\",DATEDIFF(DATE( YEAR([Date]), 1, 1),[Date],DAY)+1,",
                "\"Quarter Sort\",QUARTER([Date]),",
                "\"Quarter\",\"Q\"&FORMAT([Date],\"Q\"),",
                "\"Quarter of Year\",\"Q\" & FORMAT([Date],\"Q\") & \" \" & FORMAT([Date],\"YYYY\"),",
                "\"Quarter of Year Sort\",INT(FORMAT([Date],\"YYYYQ\")),",
                "//\"Start of Quarter\",DATE( YEAR([Date]), (QUARTER([Date])*3)-2, 1),",
                "//\"End of Quarter\",EOMONTH(DATE( YEAR([Date]), QUARTER([Date])*3, 1),0),",
                "\"Week No of Year\",WEEKNUM([Date]),",
                "\"Week No\", \"Wk \" & FORMAT(WEEKNUM([Date]),\"0#\"),",
                "\"Week of Year\", FORMAT([Date]-WEEKDAY([Date])+1, \"mm/dd/yy\") & \" - \" & FORMAT([Date]+7-WEEKDAY([Date]), \"mm/dd/yy\"),",
                "\"Week Year\",\"Wk \" & FORMAT(WEEKNUM([Date]),\"0#\") & \" \" & Convert(YEAR([Date]),STRING),",
                "//\"Start of Week\", [Date]-WEEKDAY([Date])+1,",
                "//\"End of Week\",[Date]+7-WEEKDAY([Date]),",
                "//\"Fiscal Year\",if(_startOfFiscalYear=1,YEAR([Date]),YEAR([Date])+ QUOTIENT(MONTH([Date])+ (13-_startOfFiscalYear),13)),",
                "//\"Fiscal Quarter\",QUARTER( DATE( YEAR([Date]),MOD( MONTH([Date])+ (13-_startOfFiscalYear) -1 ,12) +1,1) ),",
                "//\"Fiscal Month\",MOD( MONTH([Date])+ (13-_startOfFiscalYear) -1 ,12) +1,",
                "//\"Day Offset\",DATEDIFF(_today,[Date],DAY),",
                "//\"Month Offset\",DATEDIFF(_today,[Date],MONTH),",
                "//\"Quarter Offset\",DATEDIFF(_today,[Date],QUARTER),",
                "//\"Year Offset\",DATEDIFF(_today,[Date],YEAR)",
                "\"Is First Monday\", [Date] = CEILING(EOMONTH([Date],-1)-1,7)+2,",
                "\"Is First Tuesday\", [Date] = CEILING(EOMONTH([Date],-1)-1,7)+3,",
                "\"Is First Wednesday\", [Date] = CEILING(EOMONTH([Date],-1)-1,7)+4,",
                "\"Is First Thursday\", [Date] = CEILING(EOMONTH([Date],-1)-1,7)+5,",
                "\"Is First Friday\", [Date] = CEILING(EOMONTH([Date],-1)-1,7)+6,",
                "\"Is Last Monday\", [Date] = CEILING(EOMONTH([Date],0)-8,7)+2,",
                "\"Is Last Tuesdday\", [Date] = CEILING(EOMONTH([Date],0)-9,7)+3,",
                "\"Is Last Wednesday\", [Date] = CEILING(EOMONTH([Date],0)-10,7)+4,",
                "\"Is Last Thursday\", [Date] = CEILING(EOMONTH([Date],0)-11,7)+5,",
                "\"Is Last Friday\", [Date] = CEILING(EOMONTH([Date],0)-12,7)+6,",
                "\"Is First Week\", [Date] = CEILING(EOMONTH([Date],-1)-1,7)+2 || [Date] = CEILING(EOMONTH([Date],-1)-1,7)+3 || [Date] = CEILING(EOMONTH([Date],-1)-1,7)+4 || [Date] = CEILING(EOMONTH([Date],-1)-1,7)+5 || [Date] = CEILING(EOMONTH([Date],-1)-1,7)+6,",
                "\"Is Last Week\", [Date] = CEILING(EOMONTH([Date],0)-8,7)+2 || [Date] = CEILING(EOMONTH([Date],0)-9,7)+3 || [Date] = CEILING(EOMONTH([Date],0)-10,7)+4 || [Date] = CEILING(EOMONTH([Date],0)-11,7)+5 || [Date] = CEILING(EOMONTH([Date],0)-12,7)+6",
                "",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Drives - Time Tracking",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "26a580a3-ce59-44f8-8b8a-bef8c6aa6ead",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "08351988-4286-4cf8-ae50-36df5837f839",
            "sourceColumn": "User",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8cd4a522-3cab-4e19-ad87-b9553816fad3",
            "sourceColumn": "Transaction Type",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c66f25d6-745d-4886-ac41-2f8e27c54ed8",
            "sourceColumn": "Transaction Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Payment Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "997832ad-6b5b-49ef-82d8-4b1350918769",
            "sourceColumn": "Payment Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7dd19c90-3a57-4345-9ed1-359f39a2ff46",
            "sourceColumn": "Total Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Transaction Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "d753c0f9-61bb-4e6d-a7ce-7583c6d71ce8",
            "sourceColumn": "Transaction Start",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "0f5fbdc9-adca-4242-ab80-a4d106f14bf2",
            "sourceColumn": "Transaction End",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Start",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "9cd08cd1-e6a0-442f-bd26-58e9bd0d54ed",
            "sourceColumn": "Payment Start",
            "summarizeBy": "none"
          },
          {
            "name": "Payment End",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "edb0095b-6e14-4871-966a-9cc9c0b78ef2",
            "sourceColumn": "Payment End",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Sequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "72aeef6d-0ec1-4fbd-81de-43ed05b19a7e",
            "sourceColumn": "Payment Sequence",
            "summarizeBy": "none"
          },
          {
            "name": "Activity Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c7af03bd-5046-4c0d-be44-c8d5a631cb6e",
            "sourceColumn": "Activity Key",
            "summarizeBy": "none"
          },
          {
            "name": "Case Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "11f413e3-bb96-4acf-80fe-757e59144f11",
            "sourceColumn": "Case Key",
            "summarizeBy": "count"
          },
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7f3213c3-a03d-4582-ad6c-ee43c6251b2b",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "24401a8c-2a93-40d0-af2f-f538a0790e9b",
            "sourceColumn": "Transaction Date",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "\"Transaction Group\"",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "de84d6eb-ecd2-4011-a3b1-cdffddd3e266",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Type Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "961d71e4-8d01-4976-97c9-afc618a06fb9",
            "sourceColumn": "Type Category",
            "summarizeBy": "none"
          },
          {
            "name": "LocationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "27f4ba85-3bc6-4a6d-9f0f-b402f46a9bae",
            "sourceColumn": "LocationId",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5b2e9e43-68c5-4efb-8540-b75d69b6ec55",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TimeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "(Hour('Drives - Time Tracking'[Transaction Start]) * 3600) + (MINUTE('Drives - Time Tracking'[Transaction Start]) * 60)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2471b6c9-9e15-4b2e-92f4-a40066a886bd",
            "summarizeBy": "count",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "53cedbb1-ba85-4c10-8c63-511f39c6e15f",
        "measures": [
          {
            "name": "Payment Duration",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = Sum('Drives - Time Tracking'[Payment Time])",
              "// There are 3,600 seconds in an hour",
              "VAR Hours =",
              "    INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    CONCATENATE (",
              "        H,",
              "        CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) )",
              "    )"
            ],
            "isHidden": true,
            "lineageTag": "034346f4-5a7f-42e8-91fe-966fb3d142b6"
          }
        ],
        "partitions": [
          {
            "name": "Drives - Time Tracking-2c5cac95-ff92-42a9-954c-becfecc297d3",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/drives/Transaction%20Time%20Tracking/\"),",
                "    #\"pq\" = Source{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Underscore,{{\"Transaction Start\", type datetime}, {\"Transaction End\", type datetime}, {\"Payment Start\", type datetime}, {\"Payment End\", type datetime}, {\"Transaction Time\", Int64.Type}, {\"Payment Time\", Int64.Type}, {\"Total Time\", Int64.Type}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"Transaction Start\", \"Transaction Start - Copy\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Duplicated Column\",{{\"Transaction Start - Copy\", \"Transaction Date\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Transaction Date\", type date}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type1\", {\"Type\"}, #\"mdm MVTypeCategory\", {\"TypeCode\"}, \"mdm MVTypeCategory\", JoinKind.LeftOuter),",
                "    #\"Expanded mdm MVTypeCategory\" = Table.ExpandTableColumn(#\"Merged Queries\", \"mdm MVTypeCategory\", {\"Category\"}, {\"mdm MVTypeCategory.Category\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded mdm MVTypeCategory\",{{\"mdm MVTypeCategory.Category\", \"Type Category\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns1\",null,\"Not Mapped\",Replacer.ReplaceValue,{\"Type Category\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"Case Key\", Int64.Type}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type2\", each [Office] <> null),",
                "    #\"Merged DC Location\" = Table.NestedJoin(#\"Filtered Rows1\", {\"Office\"}, #\"DC - Location\", {\"DrivesOfficeName\"}, \"DC Location\", JoinKind.LeftOuter),",
                "    #\"Expanded DC Location\" = Table.ExpandTableColumn(#\"Merged DC Location\", \"DC Location\", {\"LocationId\"}, {\"LocationId\"}),",
                "    #\"Changed Type LocationId\" = Table.TransformColumnTypes(#\"Expanded DC Location\",{{\"LocationId\", Int64.Type}}),",
                "    #\"Removed Office\" = Table.RemoveColumns(#\"Changed Type LocationId\",{\"Office\"})",
                "in",
                "    #\"Removed Office\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Drives - Financials",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Drawer Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "0238a259-939f-414a-8b03-c77f1f681a92",
            "sourceColumn": "Drawer Date",
            "summarizeBy": "none"
          },
          {
            "name": "Drawer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1283542a-e826-4290-92e7-e400b5ecb006",
            "sourceColumn": "Drawer ID",
            "summarizeBy": "count"
          },
          {
            "name": "Cashier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c8917d72-5f96-46c3-b876-a1d23c96b74f",
            "sourceColumn": "Cashier",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1a35cc27-e3f8-4419-ba95-de8c415e00ca",
            "sourceColumn": "Payment Type",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "718e21fb-913a-455b-9a1d-f79b85b848d7",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Payment ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "88abd21c-32e9-4092-84fc-6fd8a2c15ee2",
            "sourceColumn": "Payment ID",
            "summarizeBy": "count"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "lineageTag": "84203dc9-e907-4b96-9c44-3135bfaede9c",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Routing Transit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7c770434-6e20-47fe-9159-9fb58ac81384",
            "sourceColumn": "Routing Transit",
            "summarizeBy": "none"
          },
          {
            "name": "Account Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0826bb0b-b9d3-4584-9d6c-f51f36b2fad6",
            "sourceColumn": "Account Number",
            "summarizeBy": "none"
          },
          {
            "name": "Payment Detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "09e14dc2-2dd0-4dd2-9356-b3dcdf6d4267",
            "sourceColumn": "Payment Detail",
            "summarizeBy": "none"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2ee90354-0a9b-4b1a-92ce-2ab76d122209",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7d879057-7640-4874-a7be-c885e31d7806",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "LocationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a3b3c4f9-ebc4-46de-bfe4-6ce435b587db",
            "sourceColumn": "LocationId",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bc0f2ce9-dd83-4b19-956b-e8dc2369a577",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Payment Type Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              " SWITCH('Drives - Financials'[Payment Type], ",
              "\t\"Redeem Escrow\", \"Redeem Escrow\",",
              "\t\"OTC E-Check\", \"OTC E-Check\",",
              "\t\"Online Credit Card\", \"Online\",",
              "\t\"Money Order\", \"Money Order\",",
              "\t\"Kiosk Credit Card\", \"Kiosk\",",
              "\t\"Kiosk Check\", \"Kiosk\",",
              "\t\"Kiosk Cash\", \"Kiosk\",",
              "\t\"Credit Card\", \"Credit Card\",",
              "\t\"County Internal\", \"County Internal\",",
              "\t\"Check\", \"Check\",",
              "\t\"Cash\", \"Cash\",",
              "\t\"App Credit Card\", \"App Credit Card\"",
              "    , \"Other\" ) ",
              "",
              ""
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "73893dc4-b6a1-482f-ab19-be60320da5e6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "6e73f9c3-d689-49d7-ba0b-59f5424fca72",
        "partitions": [
          {
            "name": "Drives - Financials-0be95140-9977-44b6-91bf-59d0fbb8acdc",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/drives/Financials/\"),",
                "    #\"pq\" = Source{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Underscore,{{\"Drawer ID\", Int64.Type}, {\"Payment ID\", Int64.Type}, {\"Amount\", Currency.Type}, {\"Drawer Date\", type datetime}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"Drawer Date\", type date}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type1\", each [Office] <> null),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Filtered Rows\", {\"Office\"}, #\"DC - Location\", {\"DrivesOfficeName\"}, \"DC Location\", JoinKind.LeftOuter),",
                "    #\"Expanded DC Location\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DC Location\", {\"LocationId\"}, {\"LocationId\"}),",
                "    #\"Removed Office\" = Table.RemoveColumns(#\"Expanded DC Location\",{\"Office\"})",
                "in",
                "    #\"Removed Office\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Drives - Title Application Errors",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4ce4a409-7b67-4662-8a2b-c8ebb4d7f414",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "Case Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fe972dad-2700-45dc-8ef8-e84319b937fd",
            "sourceColumn": "Case Id",
            "summarizeBy": "none"
          },
          {
            "name": "Title Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f5911f98-de8b-4a9f-bfdb-adae83d85023",
            "sourceColumn": "Title Number",
            "summarizeBy": "none"
          },
          {
            "name": "Jurisdiction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "20be488d-783d-46f4-9176-204598744738",
            "sourceColumn": "Jurisdiction",
            "summarizeBy": "none"
          },
          {
            "name": "Current Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "96ad3c8d-5ec2-4a63-879b-a0fa8482cffa",
            "sourceColumn": "Current Stage",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Jurisdiction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fc803737-e7bb-489d-8893-c8c73780fbd0",
            "sourceColumn": "Sub Jurisdiction",
            "summarizeBy": "none"
          },
          {
            "name": "Ownership Document",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "958d2442-30b4-4eb2-ab8b-95b11435e57c",
            "sourceColumn": "Ownership Document",
            "summarizeBy": "none"
          },
          {
            "name": "Reject Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2022d126-dd46-43f8-a76a-442bc8465948",
            "sourceColumn": "Reject Category",
            "summarizeBy": "none"
          },
          {
            "name": "Reject Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fb6dd726-0690-4f66-9bda-26d5689519bb",
            "sourceColumn": "Reject Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "da8345e0-aff2-406a-a199-b55019d6c237",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "LocationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1f885c3f-fb48-4b1c-abeb-d027c8051306",
            "sourceColumn": "LocationId",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "656611f9-2156-4c10-9668-e9c6c71ded9f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Original User Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "10a481c1-9a38-41dd-a257-36f52e0c5e5f",
            "sourceColumn": "Original User Id",
            "summarizeBy": "none"
          },
          {
            "name": "Original User Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "13d36912-7b92-49de-8011-e040d60336da",
            "sourceColumn": "Original User Name",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "faa67a67-7a90-4cdc-a3dd-513874a707a4",
        "partitions": [
          {
            "name": "Drives - Title Application Errors-74a4ab63-8c8c-4eea-a098-83770e412e22",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/drives/Title Application Errors/Park Meadows Center Office/\"),",
                "    #\"pq\" = Source{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Imported Parquet\", each ([Office] = \"Douglas County - Park Meadows\")),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each ([Office] <> null)),",
                "    #\"Appended Query\" = Table.Combine({#\"Filtered Rows1\", #\"Drives - Title Application Errors Castle Rock\", #\"Drives - Title Application Errors Highlands Ranch\"}),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Appended Query\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    Custom1 = Table.AddColumn(#\"Underscore\", \"File Date\", each Text.Combine(List.RemoveNulls(List.Transform(Text.ToList([File Name]),each if Value.Is(Value.FromText(_), type number) then _ else null)))),",
                "    #\"Added Custom\" = Table.AddColumn(Custom1, \"Date\", each Date.FromText(",
                "Text.Start([File Date],6) & \"01\", [Format=\"yyyyMMdd\"])),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Date\", type date}}),",
                "    #\"Removed File Date\" = Table.RemoveColumns(#\"Changed Type\",{\"File Date\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed File Date\", {\"Office\"}, #\"DC - Location\", {\"DrivesOfficeName\"}, \"DC Location\", JoinKind.LeftOuter),",
                "    #\"Expanded DC Location\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DC Location\", {\"LocationId\"}, {\"LocationId\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded DC Location\",{\"Office\"}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Removed Columns\", \"Original User\", Splitter.SplitTextByEachDelimiter({\" - \"}, QuoteStyle.Csv, false), {\"Original User.1\", \"Original User.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Original User.1\", type text}, {\"Original User.2\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Original User.2\", \"Original User Name\"}, {\"Original User.1\", \"Original User Id\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SnapEngage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Snap"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2e565a84-ba01-4cbf-88dd-712507ffd0fe",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "TimeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "(HOUR('SnapEngage'[Created At]) * 3600) + (MINUTE('SnapEngage'[Created At]) * 60)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "82faceb3-1e5e-4350-bc27-884649214e34",
            "summarizeBy": "count",
            "type": "calculated"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "85524583-6291-4ce5-9633-4a5acca37a07",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4d652d98-a0e2-4963-b128-a9e998f20a0e",
            "sourceColumn": "Url",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8ef00113-83f6-457a-ae33-7a214043468b",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Requested By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "30ad6a6d-cbb8-407a-a71e-94e2dd0845a2",
            "sourceColumn": "Requested By",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "53b59270-8eb4-4620-a716-fca0b0f5c7c3",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Created At Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d1d5b353-bb0d-4501-b0b9-6ac55eed399d",
            "sourceColumn": "Created At Date",
            "summarizeBy": "none"
          },
          {
            "name": "Created At Seconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "91988e61-7214-4f8d-ba7d-52ef73b5785f",
            "sourceColumn": "Created At Seconds",
            "summarizeBy": "none"
          },
          {
            "name": "Created At Milliseconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7e9eb36d-e618-4aa1-91dc-30639b4c7ef9",
            "sourceColumn": "Created At Milliseconds",
            "summarizeBy": "none"
          },
          {
            "name": "Proactive Chat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "446a2323-46da-48f3-89c2-6c5efdd44a7b",
            "sourceColumn": "Proactive Chat",
            "summarizeBy": "none"
          },
          {
            "name": "Page Url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "58592877-0c1e-4101-996a-d5eb5e5601fb",
            "sourceColumn": "Page Url",
            "summarizeBy": "none"
          },
          {
            "name": "Referrer Url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6cb46d4d-35ac-478c-a962-03f0a40d91cf",
            "sourceColumn": "Referrer Url",
            "summarizeBy": "none"
          },
          {
            "name": "Entry Url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4cbbf3c0-ffa9-4a40-a665-2ede97c96b9c",
            "sourceColumn": "Entry Url",
            "summarizeBy": "none"
          },
          {
            "name": "Ip Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "135682c7-e377-40a0-a41e-77f0322c36a1",
            "sourceColumn": "Ip Address",
            "summarizeBy": "none"
          },
          {
            "name": "User Agent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0d9c2a08-785a-4663-8747-de36ee42305f",
            "sourceColumn": "User Agent",
            "summarizeBy": "none"
          },
          {
            "name": "Browser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "990b9479-d1e8-408b-b749-b80b7884f9be",
            "sourceColumn": "Browser",
            "summarizeBy": "none"
          },
          {
            "name": "Os",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8a622505-aca8-4a3f-bd48-e752d11e8598",
            "sourceColumn": "Os",
            "summarizeBy": "none"
          },
          {
            "name": "Country Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "56dd2183-489e-492a-a267-4a011b3862ef",
            "sourceColumn": "Country Code",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3571e50e-012a-425a-b3ad-9e65419b94b8",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9c8b5e3d-b2b4-4eb7-844e-d2eb876540f6",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "da4068c8-5fe0-43d5-9f3f-657fe92dbf95",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "91f44bc0-b3c5-4055-b4ff-cbe10bff9f9b",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "594cdb4d-8886-4a6a-8ce8-1cbf1bcc0c2a",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Source Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ffa8b2b3-4a05-46ac-a394-78433c3a159b",
            "sourceColumn": "Source Id",
            "summarizeBy": "none"
          },
          {
            "name": "Chat Waittime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "82adf500-8f1c-496d-9908-c7b741670f42",
            "sourceColumn": "Chat Waittime",
            "summarizeBy": "sum"
          },
          {
            "name": "Chat Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "84ca0f15-aef9-48da-9e78-1b504201b605",
            "sourceColumn": "Chat Duration",
            "summarizeBy": "sum"
          },
          {
            "name": "Chat Responded",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b89e10d5-fc81-4bc0-946d-0e0472091c0b",
            "sourceColumn": "Chat Responded",
            "summarizeBy": "none"
          },
          {
            "name": "Chat Agent Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9ab66228-95d6-469b-962d-f54eaf11cb6f",
            "sourceColumn": "Chat Agent Id",
            "summarizeBy": "none"
          },
          {
            "name": "Chat Agent Alias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "725bf594-ea1f-4d1b-ae11-917ab33df693",
            "sourceColumn": "Chat Agent Alias",
            "summarizeBy": "none"
          },
          {
            "name": "Survey Score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "97170084-1e25-420c-bd76-70a18812450e",
            "sourceColumn": "Survey Score",
            "summarizeBy": "average"
          },
          {
            "name": "Survey Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "663db249-facb-4e51-b744-e7eb8a23c850",
            "sourceColumn": "Survey Comments",
            "summarizeBy": "none"
          },
          {
            "name": "Language Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "89f1452a-7a85-4e2a-906e-aa256ccd6419",
            "sourceColumn": "Language Code",
            "summarizeBy": "none"
          },
          {
            "name": "Destination Url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "35bb5d02-d069-4292-a5b9-cf89c2fa1d62",
            "sourceColumn": "Destination Url",
            "summarizeBy": "none"
          },
          {
            "name": "Created At",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "VAR UnixTimestamp = ((SnapEngage[Created At Seconds] - 25200)  / ( 60 * 60 * 24)) ",
              "RETURN",
              "    DATE(1970,1,1) + UnixTimestamp"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9ed2939d-5329-431a-8e21-7c877acab120",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT(SnapEngage[Created At],\"yyyymmdd\")",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b33233be-1918-4b9f-a1f7-c0d9f2670cad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "If(CONTAINSSTRING(SnapEngage[Entry Url] , \"drivers\"), 2,1) ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "31ffe15a-9120-4850-b596-b87b46970312",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Page Url - Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "92a7ebb8-1399-4860-961c-67a48d20af59",
            "sourceColumn": "Page Url - Type",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "9f63ab87-75f8-42c8-8d96-59adb6792aa4",
        "measures": [
          {
            "name": "Snap Chats Not Responded",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(SnapEngage), Filter(SnapEngage, SnapEngage[Chat Responded] = \"FALSE\"))"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d8682214-7496-4fc0-b466-89e504de208c"
          }
        ],
        "partitions": [
          {
            "name": "SnapEngage-7a074354-c499-48f2-9fd0-0b5a95f1536e",
            "mode": "import",
            "queryGroup": "SnapEngage",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/snapengage/integrationApi/\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".json\")),",
                "    #\"Expanded Attributes\" = Table.ExpandRecordColumn(#\"Filtered Rows\", \"Attributes\", {\"Content Type\", \"Kind\", \"Size\", \"Group\", \"Owner\", \"Permissions\"}, {\"Attributes.Content Type\", \"Attributes.Kind\", \"Attributes.Size\", \"Attributes.Group\", \"Attributes.Owner\", \"Attributes.Permissions\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Expanded Attributes\", each ([Attributes.Size] <> 45)),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Folder Path\", \"Attributes.Content Type\", \"Attributes.Kind\", \"Attributes.Size\", \"Attributes.Group\", \"Attributes.Owner\", \"Attributes.Permissions\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Columns1\", \"SnapBinarytoText\", each SnapBinarytoText([Content])),",
                "    #\"Expanded SnapBinarytoText\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"SnapBinarytoText\", {\"Column1\"}, {\"Column1\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded SnapBinarytoText\",{\"Content\"}),",
                "    #\"Invoked Custom Function1\" = Table.AddColumn(#\"Removed Columns\", \"SnapFileMain\", each SnapFileMain([Column1])),",
                "    #\"Expanded SnapFileMain\" = Table.ExpandTableColumn(#\"Invoked Custom Function1\", \"SnapFileMain\", {\"id\", \"url\", \"type\", \"requested_by\", \"description\", \"created_at_date\", \"created_at_seconds\", \"created_at_milliseconds\", \"proactive_chat\", \"page_url\", \"referrer_url\", \"entry_url\", \"ip_address\", \"user_agent\", \"browser\", \"os\", \"country_code\", \"country\", \"region\", \"city\", \"latitude\", \"longitude\", \"source_id\", \"chat_waittime\", \"chat_duration\", \"chat_responded\", \"chat_agent_id\", \"chat_agent_alias\", \"survey_score\", \"survey_comments\", \"language_code\", \"destination_url\"}, {\"id\", \"url\", \"type\", \"requested_by\", \"description\", \"created_at_date\", \"created_at_seconds\", \"created_at_milliseconds\", \"proactive_chat\", \"page_url\", \"referrer_url\", \"entry_url\", \"ip_address\", \"user_agent\", \"browser\", \"os\", \"country_code\", \"country\", \"region\", \"city\", \"latitude\", \"longitude\", \"source_id\", \"chat_waittime\", \"chat_duration\", \"chat_responded\", \"chat_agent_id\", \"chat_agent_alias\", \"survey_score\", \"survey_comments\", \"language_code\", \"destination_url\"}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Expanded SnapFileMain\",{\"Column1\"}),",
                "    Underscore = Table.RenameColumns(#\"Removed Columns2\", List.Transform(Table.ColumnNames(#\"Removed Columns2\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    Proper = Table.RenameColumns(Underscore, List.Transform(Table.ColumnNames(Underscore), each {_, Text.Proper(_)})),",
                "    #\"Filtered Rows3\" = Table.SelectRows(Proper, each Text.StartsWith([Entry Url], \"https://www.douglas.co.us/motor\")),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Filtered Rows3\", \"Page Url\", \"Page Url - Copy\"),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Duplicated Column\",\"https://www.douglas.co.us/\",\"\",Replacer.ReplaceText,{\"Page Url - Copy\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"motorvehicle/motor-vehicle\",\"motor-vehicle\",Replacer.ReplaceText,{\"Page Url - Copy\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"motorvehicle/drivers-license\",\"drivers-license\",Replacer.ReplaceText,{\"Page Url - Copy\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Replaced Value2\",{{\"Page Url - Copy\", \"Page Url - Type\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "mdm MVTypeCategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "69e19d93-6d03-41ef-bf88-0c39af5c4625",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "TypeCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "501e7758-0c21-4782-a4b9-e2aa7e816fcc",
            "sourceColumn": "TypeCode",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "ae3ac06f-5636-4d13-babc-70bdefcbcd98",
        "partitions": [
          {
            "name": "mdm MVTypeCategory-ccea9b98-228f-4c57-bb49-d49f1ca81746",
            "mode": "import",
            "queryGroup": "MDS",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SQLServerName, SQLServerDB),",
                "    mdm_MVTypeCategory = Source{[Schema=\"mdm\",Item=\"MVTypeCategory\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(mdm_MVTypeCategory,{\"Name\", \"Code\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"Name\", \"Category\"}, {\"Code\", \"TypeCode\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Call Manager - App Summary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Call Manager"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "59b522b2-551c-4415-86e0-9680c8a69865",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Application Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "86f9d5e7-1337-411e-be0c-be01426f3e97",
            "sourceColumn": "Application Name",
            "summarizeBy": "none"
          },
          {
            "name": "Called Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "79cdb308-fedf-42f9-93b4-69c8bfa19e50",
            "sourceColumn": "Called Number",
            "summarizeBy": "none"
          },
          {
            "name": "Calls Presented",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ceec4625-9078-409c-8159-60ec3f1f026e",
            "sourceColumn": "Calls Presented",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6f69fbef-fa0b-4f7c-a28e-0debc3a1a2f0",
            "sourceColumn": "Calls Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Speed Of Answer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "0b756139-549b-48b8-b6ef-e95639f4f318",
            "sourceColumn": "Avg Speed Of Answer",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Talk Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "ba250e2a-8f8c-4b93-9027-08a82cc0eacb",
            "sourceColumn": "Avg Talk Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Work Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "ef96517a-29f1-48f2-8fbc-0cafdce7e729",
            "sourceColumn": "Avg Work Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Calls Abandoned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4e105774-bce0-4763-b63d-2e7809e46d85",
            "sourceColumn": "Calls Abandoned",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Abandon Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "edda22df-d2b3-4a93-84db-c4157ecc828f",
            "sourceColumn": "Avg Abandon Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Hidden",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "cf72ac24-9820-4768-b66e-790f322ed1dc",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "faac296c-92f0-4792-a284-ac6acec693f2",
        "partitions": [
          {
            "name": "Call Manager - App Summary-531cc804-35cf-4884-93f5-1e7fc008f27c",
            "mode": "import",
            "queryGroup": "Call Manager",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/callmanager/applicationSummary/\"),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(Source, \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Application Name\", type text}, {\"Called Number\", Int64.Type}, {\"Calls Presented\", Int64.Type}, {\"Flow-In\", Int64.Type}, {\"Flow-Out\", Int64.Type}, {\"Calls Handled\", Int64.Type}, {\"Avg Speed Of Answer\", type number}, {\"Avg Talk Time\", type number}, {\"Avg Work Time\", type number}, {\"Calls Abandoned\", Int64.Type}, {\"Avg Abandon Time\", type number}, {\"Date\", type date}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",0,null,Replacer.ReplaceValue,{\"Calls Presented\", \"Flow-In\", \"Flow-Out\", \"Calls Handled\", \"Avg Speed Of Answer\", \"Avg Talk Time\", \"Avg Work Time\", \"Calls Abandoned\", \"Avg Abandon Time\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value\",{\"Flow-In\", \"Flow-Out\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Call Manager - Agent Call Summary",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Call Manager"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "61184982-c874-429d-befc-ba4f3943ae7d",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Hidden",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "60d1c15b-c2c1-4705-9418-748ffc3efd3b",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Agent Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "347aa560-593c-4251-b85c-bc5c52f55264",
            "sourceColumn": "Agent Name",
            "summarizeBy": "none"
          },
          {
            "name": "Agent ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e2363a57-a6fc-4111-a1c1-88c5d6f614d4",
            "sourceColumn": "Agent ID",
            "summarizeBy": "none"
          },
          {
            "name": "Extension IPCC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2644b0ae-c43b-4595-9f57-b47229e489ac",
            "sourceColumn": "Extension IPCC",
            "summarizeBy": "none"
          },
          {
            "name": "Extension Non IPCC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "508ad349-e555-412b-bb52-2a414a5544f9",
            "sourceColumn": "Extension Non IPCC",
            "summarizeBy": "none"
          },
          {
            "name": "Total Inbound",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f163dae4-ff09-47ab-9fe5-a887a98b41c5",
            "sourceColumn": "Total Inbound",
            "summarizeBy": "sum"
          },
          {
            "name": "Inbound ACD Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1994fc05-3010-4c40-8751-deb9f1c3e1d9",
            "sourceColumn": "Inbound ACD Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Talk Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "1a7ce5eb-5e01-4e15-87ac-fea67eedfc05",
            "sourceColumn": "Avg Talk Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Hold Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "b25e059a-760e-46b6-a66a-3901e104f000",
            "sourceColumn": "Avg Hold Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Work Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "0d445572-fd98-4335-9cc3-a760907ffe74",
            "sourceColumn": "Avg Work Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Inbound Non-ACD On IPCC Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7be31fb9-9685-419f-a2e8-ba00d46c1811",
            "sourceColumn": "Inbound Non-ACD On IPCC Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Talk Time_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "7653fe7f-1c1c-4903-857f-41fa666c5d89",
            "sourceColumn": "Avg Talk Time_1",
            "summarizeBy": "sum"
          },
          {
            "name": "Max Talk Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "1ff41f26-21a6-4f68-8732-b415dba700d1",
            "sourceColumn": "Max Talk Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Inbound Non-ACD On Non-IPCC Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff9079ac-cab1-4a51-9bd1-5466a36ec122",
            "sourceColumn": "Inbound Non-ACD On Non-IPCC Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Call Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "082ee7ce-0086-405c-a765-51b889c7c5f6",
            "sourceColumn": "Avg Call Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Max Call Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "1bc5a8db-8190-4b23-80be-50d61742144a",
            "sourceColumn": "Max Call Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Outbound On IPCC Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0b435ac1-a457-415a-a053-8682fc13ba81",
            "sourceColumn": "Outbound On IPCC Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Call Time_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "f392d6d7-fb5a-43fb-af23-365d402090a7",
            "sourceColumn": "Avg Call Time_2",
            "summarizeBy": "sum"
          },
          {
            "name": "Max Call Time_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "d8c85e82-6b3c-48ef-8ee2-335b6d40f854",
            "sourceColumn": "Max Call Time_3",
            "summarizeBy": "sum"
          },
          {
            "name": "Outbound On Non-IPCC Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c12ae064-7cf6-4229-913f-e35d3a6355b4",
            "sourceColumn": "Outbound On Non-IPCC Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Talk Time_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "efc10a27-dc6a-48aa-961b-2e714ad6eb0f",
            "sourceColumn": "Avg Talk Time_4",
            "summarizeBy": "sum"
          },
          {
            "name": "Max Talk Time_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "e5b8fe3a-9a50-49a9-b5b2-e00357b52b0d",
            "sourceColumn": "Max Talk Time_5",
            "summarizeBy": "sum"
          },
          {
            "name": "ACD Transfer In",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9ae1c39f-e50b-4efa-acd1-a7739b8e6f08",
            "sourceColumn": "ACD Transfer In",
            "summarizeBy": "sum"
          },
          {
            "name": "Transfer Out",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1d5f458f-08af-4c9a-8f9e-8e3272bd80de",
            "sourceColumn": "Transfer Out",
            "summarizeBy": "sum"
          },
          {
            "name": "Conference",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c3d8aaa0-3117-4b0e-a945-e1b9ef3a4ade",
            "sourceColumn": "Conference",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "514aa8fb-d856-42f6-96fb-dd0eec532afd",
        "partitions": [
          {
            "name": "Call Manager - Agent Call Summary-4b08ff50-1bb0-47d0-8cb4-a064dfac5613",
            "mode": "import",
            "queryGroup": "Call Manager",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/callmanager/agentCallSummary\"),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(Source, \"Transform File (2)\", each #\"Transform File (2)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (2)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample AgentSummary\"))),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded Table Column1\",{\"Source.Name\", \"Date\", \"Agent Name\", \"Agent ID\", \"Extension IPCC\", \"Extension Non IPCC\", \"Total Inbound\", \"Inbound ACD Total\", \"Avg Talk Time\", \"Avg Hold Time\", \"Avg Work Time\", \"Inbound Non-ACD On IPCC Total\", \"Avg Talk Time_1\", \"Max Talk Time\", \"Inbound Non-ACD On Non-IPCC Total\", \"Avg Call Time\", \"Max Call Time\", \"Outbound On IPCC Total\", \"Avg Call Time_2\", \"Max Call Time_3\", \"Outbound On Non-IPCC Total\", \"Avg Talk Time_4\", \"Max Talk Time_5\", \"ACD Transfer In\", \"Transfer Out\", \"Conference\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each ([Date] <> null)),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Total Inbound\", Int64.Type}, {\"Inbound ACD Total\", Int64.Type}, {\"Inbound Non-ACD On IPCC Total\", Int64.Type}, {\"Inbound Non-ACD On Non-IPCC Total\", Int64.Type}, {\"Outbound On IPCC Total\", Int64.Type}, {\"Outbound On Non-IPCC Total\", Int64.Type}, {\"ACD Transfer In\", Int64.Type}, {\"Transfer Out\", Int64.Type}, {\"Conference\", Int64.Type}, {\"Avg Talk Time_1\", type number}, {\"Max Talk Time\", type number}, {\"Avg Call Time\", type number}, {\"Max Call Time\", type number}, {\"Avg Call Time_2\", type number}, {\"Max Call Time_3\", type number}, {\"Avg Talk Time_4\", type number}, {\"Max Talk Time_5\", type number}}),",
                "    #\"Replaced zero with null\" = Table.ReplaceValue(#\"Changed Type\",0,null,Replacer.ReplaceValue,{\"Total Inbound\", \"Inbound ACD Total\", \"Avg Talk Time\", \"Avg Hold Time\", \"Avg Work Time\", \"Inbound Non-ACD On IPCC Total\", \"Avg Talk Time_1\", \"Max Talk Time\", \"Inbound Non-ACD On Non-IPCC Total\", \"Avg Call Time\", \"Max Call Time\", \"Outbound On IPCC Total\", \"Avg Call Time_2\", \"Max Call Time_3\", \"Outbound On Non-IPCC Total\", \"Avg Talk Time_4\", \"Max Talk Time_5\", \"ACD Transfer In\", \"Transfer Out\", \"Conference\"})",
                "in",
                "    #\"Replaced zero with null\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Call Manager - Common Skill CSQ",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Call Manager"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "0d45697b-40ad-4903-8271-b572a7750b6d",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Skills",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6ab0097b-ad06-4dd7-ad7c-2fb64c1f2c57",
            "sourceColumn": "Skills",
            "summarizeBy": "none"
          },
          {
            "name": "Interval Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Hidden",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "beb32243-cbcc-4b0e-a1f1-d030de4c9211",
            "sourceColumn": "Interval Date",
            "summarizeBy": "none"
          },
          {
            "name": "Interval Start Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Time",
            "isHidden": true,
            "lineageTag": "617969cc-832d-46c5-b39a-3c6c49661194",
            "sourceColumn": "Interval Start Time",
            "summarizeBy": "none"
          },
          {
            "name": "Interval End Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Time",
            "isHidden": true,
            "lineageTag": "ea83ef53-12b5-47f7-982a-cb202d80c015",
            "sourceColumn": "Interval End Time",
            "summarizeBy": "none"
          },
          {
            "name": "CSQ Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bf99388f-6d98-43b7-bd6f-3586e0a6c4ab",
            "sourceColumn": "CSQ Name",
            "summarizeBy": "none"
          },
          {
            "name": "Calls Presented",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "853df772-5449-4bee-8bf2-0be41e4a5294",
            "sourceColumn": "Calls Presented",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Queue Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "2926c095-e3b8-4b7e-affb-9c763f7084b8",
            "sourceColumn": "Avg Queue Time",
            "summarizeBy": "average"
          },
          {
            "name": "Max Queue Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "2cf73f73-acf2-4f3e-926e-20f784f073a6",
            "sourceColumn": "Max Queue Time",
            "summarizeBy": "max"
          },
          {
            "name": "Calls Handled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6bb5b702-6a2c-4efa-8cb9-46774e6866f4",
            "sourceColumn": "Calls Handled",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Handle Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "c28e5a85-c27c-4da2-8395-4e1d136e7498",
            "sourceColumn": "Avg Handle Time",
            "summarizeBy": "average"
          },
          {
            "name": "Max Handle Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "fd13ec86-a510-41ef-92fb-30e553fceaae",
            "sourceColumn": "Max Handle Time",
            "summarizeBy": "max"
          },
          {
            "name": "Calls Abandoned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "091233cc-88d7-446d-a9bd-1cd6ec1597eb",
            "sourceColumn": "Calls Abandoned",
            "summarizeBy": "sum"
          },
          {
            "name": "Avg Queue Time_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "165983d2-577d-4697-b7cb-d802f20dfeb5",
            "sourceColumn": "Avg Queue Time_1",
            "summarizeBy": "average"
          },
          {
            "name": "Max QueueTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "bfa415cb-0c32-4931-a358-ec35e688621c",
            "sourceColumn": "Max QueueTime",
            "summarizeBy": "sum"
          },
          {
            "name": "Service Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "8ed076b5-6a4b-42c4-a8c2-fbf77aebc9e0",
            "sourceColumn": "Service Level",
            "summarizeBy": "average"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Hidden",
            "expression": "IF (LEFT('Call Manager - Common Skill CSQ'[CSQ Name],9) = \"MOTORV-DL\",2,1)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8a96c0ac-9aae-4271-8ad8-b362a7683f6e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Interval Start Time Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "(Hour('Call Manager - Common Skill CSQ'[Interval Start Time]) * 3600) + MINUTE('Call Manager - Common Skill CSQ'[Interval Start Time])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "faff41d5-509c-4eb6-9257-5949c9c69001",
            "summarizeBy": "count",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "b9aebf65-95b6-42df-804d-64aefdde8bb4",
        "partitions": [
          {
            "name": "Call Manager - Common Skill CSQ-b146cc9f-551c-4cf1-8371-7ee9be676359",
            "mode": "import",
            "queryGroup": "Call Manager",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/callmanager/commonSkillCSQ\"),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(Source, \"Transform File (3)\", each #\"Transform File (3)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (3)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (3)\", Table.ColumnNames(#\"Transform File (3)\"(#\"Sample CSQ\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Skills\", type text}, {\"Interval Start Time\", type datetime}, {\"Interval End Time\", type datetime}, {\"CSQ Name\", type text}, {\"Calls Presented\", Int64.Type}, {\"Avg Queue Time\", type number}, {\"Max Queue Time\", type number}, {\"Avg Handle Time\", type number}, {\"Calls Handled\", Int64.Type}, {\"Calls Abandoned\", Int64.Type}, {\"Max Handle Time\", type number}, {\"Avg Queue Time_1\", type number}, {\"Max QueueTime\", type number}, {\"Service Level\", type number}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Skills] <> null)),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Filtered Rows\", \"Interval Start Time\", \"Interval Start Time - Copy\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Duplicated Column\",{\"Source.Name\", \"Skills\", \"Interval Start Time - Copy\", \"Interval Start Time\", \"Interval End Time\", \"CSQ Name\", \"Calls Presented\", \"Avg Queue Time\", \"Max Queue Time\", \"Calls Handled\", \"Avg Handle Time\", \"Max Handle Time\", \"Calls Abandoned\", \"Avg Queue Time_1\", \"Max QueueTime\", \"Service Level\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Interval Start Time - Copy\", \"Interval Date\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Interval Date\", type date}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type1\",{{\"Interval Start Time\", type time}, {\"Interval End Time\", type time}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type2\", each [Calls Presented] > 0),",
                "    #\"Replaced zero with null\" = Table.ReplaceValue(#\"Filtered Rows1\",0,null,Replacer.ReplaceValue,{\"Calls Presented\", \"Avg Queue Time\", \"Max Queue Time\", \"Calls Handled\", \"Avg Handle Time\", \"Max Handle Time\", \"Calls Abandoned\", \"Avg Queue Time_1\", \"Max QueueTime\", \"Service Level\"})",
                "in",
                "    #\"Replaced zero with null\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DC - Time",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "DC"
          }
        ],
        "columns": [
          {
            "name": "Interval 30Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "424e5c8b-a77d-4dfb-a077-6c310b479da5",
            "sortByColumn": "Interval 30Min 24 Order",
            "sourceColumn": "Interval 30Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Am Pm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "194028b4-591c-498d-8d59-b99616cab850",
            "sourceColumn": "Am Pm",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 15Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb981870-c47d-4200-98f7-9a61fd3b80e0",
            "sortByColumn": "Interval 15Min 24 Order",
            "sourceColumn": "Interval 15Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 5Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2af41f50-5188-4c39-9a4d-64150a9e30a2",
            "sortByColumn": "Interval 5Min 24 Order",
            "sourceColumn": "Interval 5Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Hour 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "565928b6-a895-44b7-8c21-b795e9a8198b",
            "sourceColumn": "Hour 24",
            "summarizeBy": "none"
          },
          {
            "name": "Minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f19fa33d-6f6c-424c-a39d-210e395e1863",
            "sourceColumn": "Minute",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 10Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "12ba8c78-bb24-4811-9057-f8fe60ca83c4",
            "sortByColumn": "Interval 10Min 24 Order",
            "sourceColumn": "Interval 10Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 30Min 24 Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "59053904-b0e1-4bf8-9a18-78fd65a01803",
            "sourceColumn": "Interval 30Min 24 Order",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 15Min 24 Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ca3ea919-37ab-4770-abb5-6676fa75b706",
            "sourceColumn": "Interval 15Min 24 Order",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 10Min 24 Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "2c701712-e6c4-4b9b-b0c1-3d71e8725411",
            "sourceColumn": "Interval 10Min 24 Order",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 5Min 24 Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "469482a3-184e-4e25-8b78-99b757accd5f",
            "sourceColumn": "Interval 5Min 24 Order",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fc5e822e-77ea-4d35-9785-9b0ea6c2f9de",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "Time Label 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "dateTime",
            "formatString": "hh:nn",
            "lineageTag": "c8719950-41db-4473-98e3-70465ba11f5e",
            "sortByColumn": "id",
            "sourceColumn": "Time Label 24",
            "summarizeBy": "none"
          },
          {
            "name": "Time Label 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "dateTime",
            "formatString": "hh:nn AM/PM",
            "lineageTag": "453bd051-91a6-447b-8e5a-3cb5dc498726",
            "sortByColumn": "id",
            "sourceColumn": "Time Label 12",
            "summarizeBy": "none"
          },
          {
            "name": "Hour 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "650c525e-c373-4e8a-a464-9eb5acff747e",
            "sourceColumn": "Hour 12",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 60Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5be103d-4ac1-48c1-a292-c02ec40bd24d",
            "sortByColumn": "Interval 60Min 24 Order",
            "sourceColumn": "Interval 60Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 60Min 24 Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6644ef3c-f14b-4e6c-ad7b-6a6b3c3a68f3",
            "sourceColumn": "Interval 60Min 24 Order",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 5Min 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f27ca37-d032-48e2-aaca-7e39754ce654",
            "sortByColumn": "Interval 5Min 24 Order",
            "sourceColumn": "Interval 5Min 12",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 10Min 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ffd322f-68ca-48e2-80d4-158c2e8ba3c9",
            "sortByColumn": "Interval 10Min 24 Order",
            "sourceColumn": "Interval 10Min 12",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 15Min 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "db271f6f-4de9-431b-b87d-93ffcdd86f9b",
            "sortByColumn": "Interval 15Min 24 Order",
            "sourceColumn": "Interval 15Min 12",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 30Min 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3413df61-359a-4566-956c-4f35c5f7d7e1",
            "sortByColumn": "Interval 30Min 24 Order",
            "sourceColumn": "Interval 30Min 12",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 60Min 12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "902c7239-fbd2-468a-bd5c-694b99b42a29",
            "sortByColumn": "Interval 60Min 24 Order",
            "sourceColumn": "Interval 60Min 12",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e1d16cb5-ca9c-4411-a246-ba0e0c91f51f",
        "partitions": [
          {
            "name": "DC - Time-cdccae20-a45a-4a03-a546-7481f65545b0",
            "mode": "import",
            "queryGroup": "DC",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/consumer/reference/time/\"),",
                "",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.StartsWith([Name], \"ref_time_min\")),",
                "    Content = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(Content),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "",
                "",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Underscore,{{\"Time Label 24\", type datetime}, {\"Time Label 12\", type datetime}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - End Time",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "8976e2bb-3617-43f2-a0ba-81994def9c44",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "Interval 30Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e61a40e2-f1ef-40dc-aa9a-069c58777142",
            "sourceColumn": "Interval 30Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 15Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b48c6d1b-f517-42bf-a27e-da9903262219",
            "sourceColumn": "Interval 15Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Am Pm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3998ea3e-6031-4f01-80f4-5fc3943ed544",
            "sourceColumn": "Am Pm",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 5Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c8a9e5be-7c90-45d3-8161-d033346e8e30",
            "sourceColumn": "Interval 5Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 15Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c1f5e648-84e2-4e92-a8ef-c0198ce701cf",
            "sourceColumn": "Interval 15Min",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 10Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c7bbf75e-ae54-43bb-b150-e905312edbe6",
            "sourceColumn": "Interval 10Min",
            "summarizeBy": "none"
          },
          {
            "name": "Hour 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "24d4e91e-8b3f-4440-8691-4aa4f54249d9",
            "sourceColumn": "Hour 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 30Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0a5d10ec-1568-4290-b9dd-c1a329189722",
            "sourceColumn": "Interval 30Min",
            "summarizeBy": "none"
          },
          {
            "name": "Minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0931458e-e5e0-4214-922e-e30a838722c4",
            "sourceColumn": "Minute",
            "summarizeBy": "sum"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5b20e198-6243-4891-a3bf-fdf73218db82",
            "sourceColumn": "Hour",
            "summarizeBy": "sum"
          },
          {
            "name": "Interval 10Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "643b9706-53de-4c1a-bd48-75ec9625a71a",
            "sourceColumn": "Interval 10Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "isHidden": true,
            "lineageTag": "9c883cc8-a389-45c9-9a45-24fcb71ce87f",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 5Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ae7e2d5b-8e4b-427c-9f4d-715eb5215546",
            "sourceColumn": "Interval 5Min",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "9732927b-b6c3-4b51-af7a-5d0c4fa9973f",
        "partitions": [
          {
            "name": "Qmatic - End Time-54f6090c-7237-4ab9-b3e5-4037236fdf0a",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"EndTime.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(Underscore,{\"Id\", \"Interval 30Min 24\", \"Interval 15Min 24\", \"Am Pm\", \"Interval 5Min 24\", \"Interval 15Min\", \"Interval 10Min\", \"Hour 24\", \"Interval 30Min\", \"Minute\", \"Hour\", \"Interval 10Min 24\", \"Time\", \"Interval 5Min\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Reordered Columns\",\"1970-01-01T\",\"\",Replacer.ReplaceText,{\"Time\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Z\",\"\",Replacer.ReplaceText,{\"Time\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Time\", type time}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Entered Queue Time",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "16bfe644-8571-4832-8ce0-6b0ff8fcda25",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 30Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a561fbd6-56e0-4c88-94f8-fbe180756703",
            "sourceColumn": "Interval 30Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Am Pm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3c08900f-c634-4fc3-be3a-23ad09fb55c0",
            "sourceColumn": "Am Pm",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 15Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "62f35c84-c925-43c0-b7d3-a4ac0fdc7152",
            "sourceColumn": "Interval 15Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 5Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0c2d8aa5-787f-47e2-967d-e71bf7f7f129",
            "sourceColumn": "Interval 5Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 15Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "199743f9-68aa-45c7-8921-e55bc0169e44",
            "sourceColumn": "Interval 15Min",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 10Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c5b62e7b-48b7-4d4d-93b5-b84e0b1a6707",
            "sourceColumn": "Interval 10Min",
            "summarizeBy": "none"
          },
          {
            "name": "Hour 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "76e8f964-4acc-4acb-8e69-5c7336e43e3b",
            "sourceColumn": "Hour 24",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 30Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f49e7013-0331-46f5-b046-309baea7bf60",
            "sourceColumn": "Interval 30Min",
            "summarizeBy": "none"
          },
          {
            "name": "Minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "be026615-bd6b-4cd6-b694-58504199786d",
            "sourceColumn": "Minute",
            "summarizeBy": "none"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f87fb6d1-5517-4566-829f-0892343f43fb",
            "sourceColumn": "Hour",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 10Min 24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d2950b15-4956-4e80-89fb-1321a7371597",
            "sourceColumn": "Interval 10Min 24",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "isHidden": true,
            "lineageTag": "ebc8130d-ab88-4df4-9e4c-4d9429c23dcf",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          },
          {
            "name": "Interval 5Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5f3d2f53-ecb0-4379-a784-98bdac3b8737",
            "sourceColumn": "Interval 5Min",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "9fb9d5aa-e40c-4d3d-b0d8-c4378f9cc367",
        "partitions": [
          {
            "name": "Qmatic - Entered Queue Time-7fe348bf-789a-4487-9589-887c4f719df3",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"EnteredQueueTime.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Number Cap\",\"1970-01-01T\",\"\",Replacer.ReplaceText,{\"Time\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Z\",\"\",Replacer.ReplaceText,{\"Time\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"Time\", type time}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Changed Type\",{\"Id\", \"Interval 30Min 24\", \"Am Pm\", \"Interval 15Min 24\", \"Interval 5Min 24\", \"Interval 15Min\", \"Interval 10Min\", \"Hour 24\", \"Interval 30Min\", \"Minute\", \"Hour\", \"Interval 10Min 24\", \"Time\", \"Interval 5Min\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Entry Point",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "a6793e02-b124-417b-99f1-a9bb142649d5",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Entry Point",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "0100b4da-952f-448b-a7f7-e8308a7f9a04",
            "sourceColumn": "Entry Point",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "2792662d-1666-49a7-bbc8-9113fd911023",
        "partitions": [
          {
            "name": "Qmatic - Entry Point-c5d5aa78-6b0f-4d3c-af80-48ff27f224e4",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"EntryPoint.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Camel Cap\",{\"Id\", \"Entry Point\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Queue",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "ce73c666-8e45-4aca-9798-9615e9e0a2f8",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Queue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "395313ac-9d4c-4423-85bd-ce384f7438e2",
            "sourceColumn": "Queue",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "IF(LEFT('Qmatic - Queue'[Queue], 3) = \"DLS\", 2, 1)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "de8e0502-cf0b-480e-9dbc-1c08e60aaf29",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "33a0097d-e447-443a-8810-36ff3a926b01",
        "partitions": [
          {
            "name": "Qmatic - Queue-f3fa0723-c912-4a2f-9f96-ff392a4c2d62",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"Queue.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Imported Parquet\",{\"Id\", \"Queue\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Queue Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "7ad6d0ee-4943-4c76-8c9c-de252c5e93ef",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Queue Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "8b2fb5c3-5e90-4a6c-ac10-bbf767e62aa7",
            "sourceColumn": "Queue Type",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "05ec2dd6-406a-4d36-8f4e-343fe5b37f7c",
        "partitions": [
          {
            "name": "Qmatic - Queue Type-8350e49f-1da4-47f4-87ef-fa025f120fb4",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"QueueType.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Camel Cap\",{\"Id\", \"Queue Type\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Service Point",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "bd10fb50-2fa9-42b1-99db-968fbb89be28",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Service Point",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "48e26bda-6b15-4843-a2ba-7801794626a7",
            "sourceColumn": "Service Point",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "57181a53-1daf-4e60-a671-85d3d9137fd6",
        "partitions": [
          {
            "name": "Qmatic - Service Point-1af2a91a-1a9c-4dc1-8388-51dcb2159119",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"ServicePoint.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Camel Cap\",{\"Id\", \"Service Point\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Service",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "3277ffbb-15bd-4b7d-b022-1fd99bdbf555",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "e9b02afd-1c60-418f-a150-fb43d56503b5",
            "sourceColumn": "Service",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF (",
              "    LEFT('Qmatic - Service'[Service], 2) = \"DL\"",
              "    , 2",
              "    ,IF (CONTAINSSTRING('Qmatic - Service'[Service],\"License\")",
              "        , 2",
              "        , 1",
              "    )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a35caf50-1347-49b2-a599-7baf35c34d01",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Service - Copy.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "75aa93bd-228e-4544-8da7-3776a1d65741",
            "sourceColumn": "Service - Copy.1",
            "summarizeBy": "none"
          },
          {
            "name": "Service - Copy.2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0340261e-c643-45d3-9dd2-e9f272e21031",
            "sourceColumn": "Service - Copy.2",
            "summarizeBy": "none"
          },
          {
            "name": "Service - Copy.3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "79ab5032-a148-4bc4-a39e-cd6684d06dc6",
            "sourceColumn": "Service - Copy.3",
            "summarizeBy": "none"
          },
          {
            "name": "Service - Copy.4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cc5bd1ef-ed92-4dd0-a98f-d9acd1f49a50",
            "sourceColumn": "Service - Copy.4",
            "summarizeBy": "none"
          },
          {
            "name": "Service - Copy.5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cd4cf295-4ea9-466d-8c10-a554cd4ddd94",
            "sourceColumn": "Service - Copy.5",
            "summarizeBy": "none"
          },
          {
            "name": "Service - Copy.6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e8443815-3d34-40fa-84e7-60a02f64daa0",
            "sourceColumn": "Service - Copy.6",
            "summarizeBy": "none"
          },
          {
            "name": "DealerIndividual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "if (CONTAINSSTRING('Qmatic - Service'[Service],\"Dealer\")",
              "    ,\"Dealer\"",
              "    ,if (CONTAINSSTRING('Qmatic - Service'[Service],\"Business\")",
              "        ,\"Dealer\"",
              "        ,\"Indivual\"",
              "    )",
              ")"
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e8570860-a269-4e43-b166-69b895f334d8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Service Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "'Qmatic - Service'[Service]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3b7f10f7-cb00-4a4d-b950-78bb2759cb93",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "f6266a25-a216-4548-83cb-397a9b349eb5",
        "partitions": [
          {
            "name": "Qmatic - Service-980a87ec-1aaf-42d0-b0f5-b0fa5374cae9",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows1\" = Table.SelectRows(Source, each ([Name] = \"Service.pq\")),",
                "    #\"pq\" = #\"Filtered Rows1\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Imported Parquet\",{\"Id\", \"Service\"}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Reordered Columns\", \"Service\", \"Service - Copy\"),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Duplicated Column\", \"Service - Copy\", Splitter.SplitTextByDelimiter(\" \", QuoteStyle.Csv), {\"Service - Copy.1\", \"Service - Copy.2\", \"Service - Copy.3\", \"Service - Copy.4\", \"Service - Copy.5\", \"Service - Copy.6\", \"Service - Copy.7\", \"Service - Copy.8\", \"Service - Copy.9\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Service - Copy.1\", type text}, {\"Service - Copy.2\", type text}, {\"Service - Copy.3\", type text}, {\"Service - Copy.4\", type text}, {\"Service - Copy.5\", type text}, {\"Service - Copy.6\", type text}, {\"Service - Copy.7\", type text}, {\"Service - Copy.8\", type text}, {\"Service - Copy.9\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([#\"Service - Copy.1\"] <> \"Adult\" and [#\"Service - Copy.1\"] <> \"AppointmentInfo\" and [#\"Service - Copy.1\"] <> \"BSI\" and [#\"Service - Copy.1\"] <> \"Burial\" and [#\"Service - Copy.1\"] <> \"Cash\" and [#\"Service - Copy.1\"] <> \"Child\" and [#\"Service - Copy.1\"] <> \"Espaol\" and [#\"Service - Copy.1\"] <> \"Fingerprinting\" and [#\"Service - Copy.1\"] <> \"Food\" and [#\"Service - Copy.1\"] <> \"General\" and [#\"Service - Copy.1\"] <> \"LEAP\" and [#\"Service - Copy.1\"] <> \"Long\" and [#\"Service - Copy.1\"] <> \"Medical\" and [#\"Service - Copy.1\"] <> \"Professional\" and [#\"Service - Copy.1\"] <> \"REC-Document\" and [#\"Service - Copy.1\"] <> \"REC-General\" and [#\"Service - Copy.1\"] <> \"REC-Passport\" and [#\"Service - Copy.1\"] <> \"REC-Passports\" and [#\"Service - Copy.1\"] <> \"Supervised\") and ([#\"Service - Copy.2\"] <> \"Child\" and [#\"Service - Copy.2\"] <> \"Medical\") and ([#\"Service - Copy.3\"] <> \"Visitation\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Service - Copy.7\", \"Service - Copy.8\", \"Service - Copy.9\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Staff",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "9d6c2eb4-199b-4c05-8545-94cf9ffec792",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Last Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1a834095-d41f-415f-a22d-f66723c0bf82",
            "sourceColumn": "Last Name",
            "summarizeBy": "none"
          },
          {
            "name": "First Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6aeffd62-1e1d-4987-a37e-8e8a81b83ff2",
            "sourceColumn": "First Name",
            "summarizeBy": "none"
          },
          {
            "name": "Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "7ff9663f-04cb-419f-9372-c605fe0e29dd",
            "sourceColumn": "Staff",
            "summarizeBy": "none"
          },
          {
            "name": "DCUserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "b0d758ac-91bf-4bac-a065-ef5c8f396d46",
            "sourceColumn": "DCUserId",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "d9a96af8-9aac-4b4a-a55b-ca8a31198f1d",
        "partitions": [
          {
            "name": "Qmatic - Staff-74a76ebb-f84f-40d2-858e-b5ff989b78cb",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"Staff.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Imported Parquet\", {\"Staff\"}, #\"Qmatic - Staff Group by\", {\"Staff\"}, \"Qmatic - Staff Group by\", JoinKind.Inner),",
                "    #\"Expanded Qmatic - Staff Group by\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Qmatic - Staff Group by\", {\"MinId\"}, {\"MinId\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Expanded Qmatic - Staff Group by\",{{\"LastName\", Order.Ascending}}),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Sorted Rows\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(Underscore,{\"Id\", \"Min Id\", \"Last Name\", \"First Name\", \"Staff\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Reordered Columns\",{{\"Min Id\", \"DCUserId\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Visit Call Type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "f2757de0-f37e-45bc-8aaa-353b3c5bb22f",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Visit Call Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "144eac5c-4e40-4edb-9fb0-365789834f2a",
            "sourceColumn": "Visit Call Type",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "1e780233-145c-44c5-8bdb-3634af0ec5e8",
        "partitions": [
          {
            "name": "Qmatic - Visit Call Type-00e413c0-9f8f-4ea3-9975-d0f8b9902dd1",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"VisitCallType.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Camel Cap\",{\"Id\", \"Visit Call Type\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Visit",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "45c05501-8afc-4179-9ecb-048b69cd3edf",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Vip Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0b535dd6-6906-46bf-bd1b-de337603adf3",
            "sourceColumn": "Vip Level",
            "summarizeBy": "none"
          },
          {
            "name": "Created Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5f0f132d-f290-460b-aea2-a42a410f98d6",
            "sourceColumn": "Created Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "Is Appointment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6e168d18-5ac2-4a16-8baf-f79168a173f9",
            "sourceColumn": "Is Appointment",
            "summarizeBy": "none"
          },
          {
            "name": "Ticket Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "65342e68-5453-4f6b-94c9-f7b6cf8a0721",
            "sourceColumn": "Ticket Id",
            "summarizeBy": "none"
          },
          {
            "name": "Custom 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e5350967-89ee-48b9-8c2c-e73dbd9ffd64",
            "sourceColumn": "Custom 1",
            "summarizeBy": "none"
          },
          {
            "name": "Custom 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "edb313f8-2b16-4a1c-8514-e213ff957679",
            "sourceColumn": "Custom 2",
            "summarizeBy": "none"
          },
          {
            "name": "Custom 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f1465cf-8039-4851-9016-a149a7caab26",
            "sourceColumn": "Custom 3",
            "summarizeBy": "none"
          },
          {
            "name": "Custom 4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9550837e-4fdf-44a4-9c4d-bb1642353d61",
            "sourceColumn": "Custom 4",
            "summarizeBy": "none"
          },
          {
            "name": "Custom 5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1a9df4ce-0857-4bf2-9d48-74f7b8aefe2e",
            "sourceColumn": "Custom 5",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "86254461-3d19-440b-9f2c-7db21ddd3b51",
        "partitions": [
          {
            "name": "Qmatic - Visit-5f0e2ae8-fa6b-4288-acf0-154791392af3",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"Visit.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" ))",
                "in",
                "    #\"Number Cap\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Visit Transaction Outcome",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "fdc97561-5910-4f8e-b610-a38ebb887b48",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Visit Transaction Outcome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "9b9cb026-2d13-421d-8b46-93d0e6a4c4e5",
            "sourceColumn": "Visit Transaction Outcome",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "800f30ee-309b-4c96-9dd6-1a5ad1119c84",
        "partitions": [
          {
            "name": "Qmatic - Visit Transaction Outcome-3a13752d-1e2e-4fa7-818b-0ad87d25a4f2",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"VisitTransactionOutcome.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" ))",
                "in",
                "    #\"Camel Cap\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Work Profile",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "08335dee-1701-4ffd-af30-e7c520ab2779",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Origin Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "307ebd43-228e-4c14-b868-f8ef715ef5ab",
            "sourceColumn": "Origin Id",
            "summarizeBy": "count"
          },
          {
            "name": "End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9e65bf9c-f2b0-4f04-82a2-256924aaf1d4",
            "sourceColumn": "End Date",
            "summarizeBy": "none"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c55f54a9-683b-4e27-849b-4b6da53ac8af",
            "sourceColumn": "Client Key",
            "summarizeBy": "count"
          },
          {
            "name": "Branch Origin Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cd9e249f-88a1-4291-beb7-539d320b72d0",
            "sourceColumn": "Branch Origin Id",
            "summarizeBy": "count"
          },
          {
            "name": "Work Profile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8a69a7a3-b168-4d6d-b597-38df0c0d3a67",
            "sourceColumn": "Work Profile",
            "summarizeBy": "none"
          },
          {
            "name": "Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "17be7e1e-7d56-4f21-9700-1a1942eeab6e",
            "sourceColumn": "Start Date",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "139e7051-8926-4d5f-b064-4e5351bdb838",
        "partitions": [
          {
            "name": "Qmatic - Work Profile-4aee9e9b-e613-4141-9e00-86ec9832511a",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"WorkProfile.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" ))",
                "in",
                "    #\"Camel Cap\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Visit Transaction",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "8bf6586f-345e-45b3-aaa8-50492c5f4fc7",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "Transaction Time Vs Service Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "51a799eb-84ae-4632-a330-0fe049c15fe6",
            "sourceColumn": "Transaction Time Vs Service Level",
            "summarizeBy": "none"
          },
          {
            "name": "Waiting Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "97705185-c366-4de9-8303-03c7b6fa7eb4",
            "sourceColumn": "Waiting Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Waiting Time Service Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4d1bef58-40df-4ef7-a069-23de82f3e6c2",
            "sourceColumn": "Waiting Time Service Level",
            "summarizeBy": "average"
          },
          {
            "name": "End Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6f7bd258-490d-4308-ab30-5c8d4b4d81a5",
            "sourceColumn": "End Time Key",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "470b38af-de21-4ae1-ac2c-2c4d2d282c18",
            "sourceColumn": "Transaction Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Branch Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d97f75f2-b3cc-48db-9ae2-c52a30a5c093",
            "sourceColumn": "Branch Key",
            "summarizeBy": "none"
          },
          {
            "name": "Queue Type Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "274b36ed-12cf-4fad-b3d2-b4a9ea8c52cd",
            "sourceColumn": "Queue Type Key",
            "summarizeBy": "none"
          },
          {
            "name": "Call Time Of Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "15da54b2-9fc9-49c2-8c37-c098541807a6",
            "sourceColumn": "Call Time Of Day",
            "summarizeBy": "none"
          },
          {
            "name": "Entered Queue Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d68e20b0-0484-48b6-a28b-3f0bcf819c67",
            "sourceColumn": "Entered Queue Time Key",
            "summarizeBy": "none"
          },
          {
            "name": "Time Seconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2a4eae92-c5ff-40f9-8e64-a3caf2c365c1",
            "sourceColumn": "Time Seconds",
            "summarizeBy": "sum"
          },
          {
            "name": "Staff Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ace3251a-2c23-43a2-98d9-7872215d9b61",
            "sourceColumn": "Staff Key",
            "summarizeBy": "none"
          },
          {
            "name": "Work Profile Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ea599deb-69dc-4de1-a442-a5bceb914508",
            "sourceColumn": "Work Profile Key",
            "summarizeBy": "none"
          },
          {
            "name": "Waiting Time Vs Service Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6026e058-eec8-4333-88ad-52ec665fd75f",
            "sourceColumn": "Waiting Time Vs Service Level",
            "summarizeBy": "none"
          },
          {
            "name": "Entry Point Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "74b3d85b-db1e-4a34-823f-55b2b27876d6",
            "sourceColumn": "Entry Point Key",
            "summarizeBy": "none"
          },
          {
            "name": "Visit Outcome Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1836a32e-e041-406e-ae1e-1d734ca2137a",
            "sourceColumn": "Visit Outcome Key",
            "summarizeBy": "none"
          },
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "45c4ea1e-efc6-477c-9642-f7c7184f9b65",
            "sourceColumn": "Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Queue Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c553ce0f-964e-46c5-8659-39625ade0a46",
            "sourceColumn": "Queue Key",
            "summarizeBy": "none"
          },
          {
            "name": "End Time Of Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "293c077e-cd02-4f13-a552-d9dedd810d06",
            "sourceColumn": "End Time Of Day",
            "summarizeBy": "none"
          },
          {
            "name": "Is Appointment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "149f2b06-0d4d-47a5-a970-d2534c095294",
            "sourceColumn": "Is Appointment",
            "summarizeBy": "none"
          },
          {
            "name": "Staff Transaction Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4ce00aa4-a97f-4640-8144-0fac9dd3b07e",
            "sourceColumn": "Staff Transaction Time",
            "summarizeBy": "sum"
          },
          {
            "name": "Call Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "117165b4-c11e-4a55-b212-f430de201ea4",
            "sourceColumn": "Call Time Key",
            "summarizeBy": "none"
          },
          {
            "name": "Enter Queue Time Of Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1c60199-4d08-4e36-b787-c501dcd2dc45",
            "sourceColumn": "Enter Queue Time Of Day",
            "summarizeBy": "none"
          },
          {
            "name": "Outcome Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a7c56032-cb47-48d0-8e1c-4749635a4ef5",
            "sourceColumn": "Outcome Key",
            "summarizeBy": "none"
          },
          {
            "name": "Service Point Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a9a7bbb0-1b44-4fdc-9fad-98d6da7632d6",
            "sourceColumn": "Service Point Key",
            "summarizeBy": "none"
          },
          {
            "name": "Visit Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4eb7c2e2-0d23-48d7-ac70-b9dedf140f88",
            "sourceColumn": "Visit Key",
            "summarizeBy": "none"
          },
          {
            "name": "Entered Queue Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "89ef3321-40f4-41e1-8471-050a26e0e607",
            "sourceColumn": "Entered Queue Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "Walking Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "20a027dd-ab3e-4845-86b5-33ef0f960164",
            "sourceColumn": "Walking Time",
            "summarizeBy": "average"
          },
          {
            "name": "Wrapup Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7f4acae6-cb4a-4913-9240-f2afdd4f720b",
            "sourceColumn": "Wrapup Time",
            "summarizeBy": "none"
          },
          {
            "name": "Vertical Message Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3b614f18-25e7-44d3-a952-ec6131ea3b1c",
            "sourceColumn": "Vertical Message Key",
            "summarizeBy": "none"
          },
          {
            "name": "Service Transaction Time Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a9bed202-4b51-498e-859e-1acc43d58b0e",
            "sourceColumn": "Service Transaction Time Level",
            "summarizeBy": "sum"
          },
          {
            "name": "Recycle Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8f2b1051-937a-4cfe-8d53-3fdeedb77954",
            "sourceColumn": "Recycle Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Call Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a81046fb-d349-4a13-b100-49cb14ea5d3e",
            "sourceColumn": "Call Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "Visit Call Type Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2c3dcae7-e7d2-4e03-ad07-6af80bb35ea6",
            "sourceColumn": "Visit Call Type Key",
            "summarizeBy": "none"
          },
          {
            "name": "Service Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Key",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f6292ad9-50f4-490c-97f7-0614cd83f6ca",
            "sourceColumn": "Service Key",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "d474c408-4e2a-41bb-8b8b-d9fca1a656ca",
        "partitions": [
          {
            "name": "Qmatic - Visit Transaction-6a21c68f-2b0b-42a1-8956-9c33ea48099d",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows1\" = Table.SelectRows(Source, each ([Name] = \"VisitTransaction.pq\")),",
                "    #\"pq\" = #\"Filtered Rows1\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Camel Cap\", each ([Branch Key] <> 4)),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Filtered Rows\", {\"Service Key\"}, #\"Qmatic - Service\", {\"Id\"}, \"Qmatic - Service\", JoinKind.Inner)",
                "in",
                "    #\"Merged Queries\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Drives - Fee Statistics",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Fee Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e051f126-6ea7-457d-ae56-be70442aad84",
            "sourceColumn": "Fee Type",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "03628389-74f5-42ae-876d-28fa470c5ca5",
            "sourceColumn": "Transaction Date",
            "summarizeBy": "none"
          },
          {
            "name": "Activity Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7b898bd7-0ed5-4de8-9e4d-ccfbea53a198",
            "sourceColumn": "Activity Type",
            "summarizeBy": "none"
          },
          {
            "name": "Amount Assessed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isHidden": true,
            "lineageTag": "3e757b0b-c170-4d5d-a6ca-c1eed2d5ae56",
            "sourceColumn": "Amount Assessed",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2acd14b0-4880-41d8-89d3-79750bf53874",
            "sourceColumn": "Customer Id",
            "summarizeBy": "none"
          },
          {
            "name": "Office Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9ccc796e-9973-4b12-b468-354546415db3",
            "sourceColumn": "Office Type",
            "summarizeBy": "none"
          },
          {
            "name": "Fee Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "47c203fc-233a-45c2-afe1-f74cdebcf30f",
            "sourceColumn": "Fee Category",
            "summarizeBy": "none"
          },
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ff52e752-14bb-4c75-a17e-5ddfa88b942b",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "LocationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "82f2b712-aba4-4ab4-9009-9291ed27db1d",
            "sourceColumn": "LocationId",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b3fe975f-9fc8-4073-93ba-3acabef250f8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "e31cb155-2dbc-4ea5-bed3-6b0cd8fa08dc",
        "partitions": [
          {
            "name": "Drives - Fee Statistics-da6c34a4-3c44-46c4-b799-c32852ced25b",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(\"https://dldmvprwestus3.dfs.core.windows.net\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{[#\"Folder Path\"=\"https://dldmvprwestus3.dfs.core.windows.net/datalake/\" & datapath & \"consumer/drives/Fee%20Statistics/\",Name=\"FeeStatistics.pq\"]}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Underscore,{{\"Amount Assessed\", Currency.Type}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each [Office] <> null),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Filtered Rows1\", {\"Office\"}, #\"DC - Location\", {\"DrivesOfficeName\"}, \"DC Location\", JoinKind.LeftOuter),",
                "    #\"Expanded DC Location\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DC Location\", {\"LocationId\"}, {\"LocationId\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Expanded DC Location\",{{\"LocationId\", Int64.Type}}),",
                "    #\"Removed Office\" = Table.RemoveColumns(#\"Changed Type1\",{\"Office\"})",
                "in",
                "    #\"Removed Office\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Drives - Fee Waiver Tracking",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Fee Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ec97c138-1ffe-4ee9-828c-fdb6afdb5ec9",
            "sourceColumn": "Fee Type",
            "summarizeBy": "none"
          },
          {
            "name": "Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "163fd637-cbbe-4050-8879-8a0e21f29b40",
            "sourceColumn": "Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Calculated Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isHidden": true,
            "lineageTag": "97b2579b-bdf2-42fe-8dc8-90eb24b22306",
            "sourceColumn": "Calculated Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount Charged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isHidden": true,
            "lineageTag": "7791bf23-bfec-4220-8b6c-d199ab2c4af6",
            "sourceColumn": "Amount Charged",
            "summarizeBy": "sum"
          },
          {
            "name": "Waived Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "isHidden": true,
            "lineageTag": "9a18150f-9bf7-439f-8690-3a4f3d6d31a3",
            "sourceColumn": "Waived Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Cashier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f8497eec-e7fd-4329-a3df-69e2012bbb9b",
            "sourceColumn": "Cashier",
            "summarizeBy": "none"
          },
          {
            "name": "Date Of Transaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "970a694f-0ae1-4d7a-8bdf-ec36dbf52254",
            "sourceColumn": "Date Of Transaction",
            "summarizeBy": "none"
          },
          {
            "name": "View Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1dfdf290-a0d7-4fe7-a854-321169393dfd",
            "sourceColumn": "View Title",
            "summarizeBy": "none"
          },
          {
            "name": "View Title And Registration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0ae22270-cd77-41e3-9541-877783b555ce",
            "sourceColumn": "View Title And Registration",
            "summarizeBy": "none"
          },
          {
            "name": "Approver",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "142826b3-2fbc-4562-9c62-169e243b9da1",
            "sourceColumn": "Approver",
            "summarizeBy": "none"
          },
          {
            "name": "Note",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d308b0d8-06cf-4914-82d9-68a88ee6f72c",
            "sourceColumn": "Note",
            "summarizeBy": "none"
          },
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7d5eea52-cac4-472a-8432-bb70285e0417",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "LocationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fc95254f-dea7-44f3-a14b-12ca6d94360c",
            "sourceColumn": "LocationId",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "1",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "87be4ae7-3235-4511-93be-51e035c83818",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TimeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "(Hour('Drives - Fee Waiver Tracking'[Date Of Transaction]) * 3600) + (MINUTE('Drives - Fee Waiver Tracking'[Date Of Transaction]) * 60)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "921bd569-89af-429f-b6ee-caea512c47a1",
            "summarizeBy": "count",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "845c5cc5-97ed-4e44-8a75-ab816e14fd86",
        "partitions": [
          {
            "name": "Drives - Fee Waiver Tracking-f94efd95-2ac8-447c-89bb-ec1dc4e0fd85",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(\"https://dldmvprwestus3.dfs.core.windows.net\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{[#\"Folder Path\"=\"https://dldmvprwestus3.dfs.core.windows.net/datalake/\" & datapath & \"consumer/drives/Fee%20Waiver%20Tracking/\",Name=\"FeeWaiverTracking.pq\"]}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Underscore,{{\"Calculated Amount\", Currency.Type}, {\"Amount Charged\", Currency.Type}, {\"Waived Amount\", Currency.Type}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each ([Office] <> null)),",
                "    #\"Merged DC Location\" = Table.NestedJoin(#\"Filtered Rows1\", {\"Office\"}, #\"DC - Location\", {\"DrivesOfficeName\"}, \"DC Location\", JoinKind.LeftOuter),",
                "    #\"Expanded DC Location\" = Table.ExpandTableColumn(#\"Merged DC Location\", \"DC Location\", {\"LocationId\"}, {\"LocationId\"}),",
                "    #\"Removed Office\" = Table.RemoveColumns(#\"Expanded DC Location\",{\"Office\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Office\",{{\"Date Of Transaction\", type datetime}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DC - Location",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "DC"
          }
        ],
        "columns": [
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "836c1d86-886a-42b7-8ec3-5ac068492294",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "LocationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "4c5defdc-6127-4f69-9081-22b3a6e8a32d",
            "sourceColumn": "LocationId",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Latitude",
            "dataType": "double",
            "lineageTag": "0528d731-a8ec-48e7-8df1-5412c44d4da9",
            "sourceColumn": "Latitude",
            "summarizeBy": "average"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Longitude",
            "dataType": "double",
            "lineageTag": "c0ca65e0-b85a-4e70-91b2-2a56d7c876c4",
            "sourceColumn": "Longitude",
            "summarizeBy": "average"
          },
          {
            "name": "QmaticBranchId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5d1f775d-9649-40e0-be7c-0d1c3ea44a79",
            "sourceColumn": "QmaticBranchId",
            "summarizeBy": "none"
          },
          {
            "name": "QmaticBranchName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9524d9d0-ed82-485d-aa95-55505c5c51ae",
            "sourceColumn": "QmaticBranchName",
            "summarizeBy": "none"
          },
          {
            "name": "DrivesOfficeId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5c7ac8c0-5b30-4ab7-96f7-f6690de95e77",
            "sourceColumn": "DrivesOfficeId",
            "summarizeBy": "none"
          },
          {
            "name": "DrivesOfficeName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b59e366-e67e-492d-b915-9997325a7f9a",
            "sourceColumn": "DrivesOfficeName",
            "summarizeBy": "none"
          },
          {
            "name": "Loacation Summary",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(TRUE()",
              "    ,'DC - Location'[Location] = \"Lone Tree\", \"Inhouse\"",
              "    ,'DC - Location'[Location] = \"Highlands Ranch\", \"Inhouse\"",
              "    ,'DC - Location'[Location] = \"Castle Rock\", \"Inhouse\"",
              "    ,'DC - Location'[Location] = \"Communications Center\", \"Inhouse\"",
              "    ,'DC - Location'[Location] = \"E-Services\", \"E-Services\"",
              "    ,'DC - Location'[Location] = \"Kiosk\", \"Kiosk\"",
              "    ,'DC - Location'[Location] = \"Douglas County - TPT\", \"Third Party Title\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "96d3e245-641a-4249-8178-a66fb6a49c66",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "0046f1a8-ed63-4392-89c2-0b4a7db7e0d5",
        "partitions": [
          {
            "name": "DC - Location-62622ea0-ec5d-4f35-8b0c-2e122d2f1fca",
            "mode": "import",
            "queryGroup": "DC",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SQLServerName, SQLServerDB, [Query=\"select#(lf)#(tab)[Location] = l.[Name]#(lf)#(tab),LocationId = l.Code#(lf)#(tab),b.Latitude#(lf)#(tab),b.Longitude#(lf)#(tab),QmaticBranchId = l.[Qmatic Branch_Code]#(lf)#(tab),QmaticBranchName = l.[Qmatic Branch_Name]#(lf)#(tab),DrivesOfficeId = o.Code#(lf)#(tab),DrivesOfficeName = o.[Name]#(lf)from [mdm].[MVLocaction] l#(lf)#(tab)left join [mdm].[MVQmaticBranch] b on l.[Qmatic Branch_Code] = b.Code#(lf)#(tab)left join [mdm].[MVDrivesOffice] o on l.[Drives Office_Code] = o.Code\", CreateNavigationProperties=false])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DC - Division",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "DC"
          }
        ],
        "columns": [
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "14fd8f56-b610-4679-986d-86727932364f",
            "sourceColumn": "OrgId",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d1f44b8-43a9-4b30-9a64-f9cb8be77e56",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7c066e7c-4924-4d44-a47e-8a7dfab1126c",
        "partitions": [
          {
            "name": "DC - Division-6245679b-a3fd-4135-8f6f-d7a8753836da",
            "mode": "import",
            "queryGroup": "DC",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUfLNL8kvUghLzchMzklVitWJVjICiroUZZalFhUr+GQmp+YVA8VjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [OrgId = _t, Organization = _t]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Organization\", \"Division\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"OrgId\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Staff Group by",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3d46b6a8-9acf-4499-b4a2-d8fcdd1f8428",
            "sourceColumn": "Staff",
            "summarizeBy": "none"
          },
          {
            "name": "MinId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "de196c65-73f5-4a01-8c6c-d1d791f7b102",
            "sourceColumn": "MinId",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "b7e4caf1-5329-4038-bc50-199cda1b863c",
        "partitions": [
          {
            "name": "Qmatic - Staff Group by-c5d8eac3-53fd-49fc-a666-910ab037a9de",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"Staff.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Grouped Rows\" = Table.Group(#\"Imported Parquet\", {\"Staff\"}, {{\"MinId\", each List.Min([Id]), type nullable number}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Grouped Rows\",{{\"Staff\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Hidden",
            "isHidden": true,
            "lineageTag": "389787e9-e8d5-4b1e-bebe-02d4a9e311bc",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7e508cc4-cb9a-4d79-8d04-dbec360353fb",
        "measures": [
          {
            "name": "CSQ Calls Presented",
            "displayFolder": "Common Skill CSQ",
            "expression": "Sum('Call Manager - Common Skill CSQ'[Calls Presented])",
            "formatString": "0",
            "lineageTag": "6c6e9240-5987-4e7e-9644-dff024792a6e"
          },
          {
            "name": "CSQ Calls Presented LM",
            "displayFolder": "Common Skill CSQ\\Monthly",
            "expression": [
              "",
              "CALCULATE(",
              "    Sum( 'Call Manager - Common Skill CSQ'[Calls Presented])",
              "    ,DATEADD('Date'[Date],-1,MONTH)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a2bdf61e-d547-4b84-ba59-12605ae8af5c"
          },
          {
            "name": "CSQ Calls Presented L1W",
            "displayFolder": "Common Skill CSQ\\Weekly",
            "expression": [
              "",
              "CALCULATE(",
              "    Sum( 'Call Manager - Common Skill CSQ'[Calls Presented])",
              "    ,DATEADD('Date'[Date],-7,DAY)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "314e1446-cd56-48a3-afbd-146bb1eba16d"
          },
          {
            "name": "CSQ Calls Presented L2W",
            "displayFolder": "Common Skill CSQ\\Weekly",
            "expression": [
              "",
              "CALCULATE(",
              "    Sum( 'Call Manager - Common Skill CSQ'[Calls Presented])",
              "    ,DATEADD('Date'[Date],-14,DAY)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d1e17e49-fb1d-46a1-8b12-e24b469570e2"
          },
          {
            "name": "CSQ Calls Presented L4W",
            "displayFolder": "Common Skill CSQ\\Weekly",
            "expression": [
              "",
              "CALCULATE(",
              "    Sum( 'Call Manager - Common Skill CSQ'[Calls Presented])",
              "    ,DATEADD('Date'[Date],-28,DAY)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "11b36caf-b34d-46ef-ba43-d3f1fd52b90c"
          },
          {
            "name": "CSQ Calls Presented % Total",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "Sum('Call Manager - Common Skill CSQ'[Calls Presented]) / [CSQ Total Calls Presented]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1c86a399-3894-4dfe-860b-77debb0f9ee8"
          },
          {
            "name": "CSQ Calls Handled %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "Sum('Call Manager - Common Skill CSQ'[Calls Handled]) / Sum('Call Manager - Common Skill CSQ'[Calls Presented])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d3dfe1e3-6f5b-42c1-9855-0ca08837b5d3"
          },
          {
            "name": "CSQ Calls Presented YTD",
            "displayFolder": "Common Skill CSQ\\YTD",
            "expression": [
              "",
              "// CALCULATE(SUM('Call Manager - Common Skill CSQ'[Calls Presented]),DATESYTD(dateadd('Date'[Date],-1,Month),\"12/31\"))",
              "",
              "TOTALYTD(",
              "    Sum( 'Call Manager - Common Skill CSQ'[Calls Presented])",
              "    ,'Date'[Date]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d03fed77-6147-4470-894e-ecb692a63a6f"
          },
          {
            "name": "CSQ Calls Abandoned %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "Sum('Call Manager - Common Skill CSQ'[Calls Abandoned]) / Sum('Call Manager - Common Skill CSQ'[Calls Presented])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "93c44cd5-648f-4d0b-be3c-9e9e713d6e64"
          },
          {
            "name": "CSQ Total Calls Presented",
            "displayFolder": "Common Skill CSQ",
            "expression": "CALCULATE(Sum('Call Manager - Common Skill CSQ'[Calls Presented]), ALL( 'Call Manager - Common Skill CSQ'[CSQ Name] ), 'Call Manager - Common Skill CSQ'[OrgId])",
            "formatString": "0",
            "lineageTag": "b424397a-3cf8-456b-af47-befdce2e0dd1"
          },
          {
            "name": "CSQ Avg Handle Time (s)",
            "displayFolder": "Common Skill CSQ",
            "expression": "AVERAGE('Call Manager - Common Skill CSQ'[Avg Handle Time]) * [Sec per Day]",
            "formatString": "0",
            "lineageTag": "c38a3d58-0d0d-4f95-9b32-a9e19af27fc0"
          },
          {
            "name": "CSQ Avg Handle Time (mm:ss)",
            "displayFolder": "Common Skill CSQ",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [CSQ Avg Handle Time (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([CSQ Avg Handle Time (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )",
              "    "
            ],
            "lineageTag": "ff0b26e2-d952-4a0c-b339-f431d5a1efce"
          },
          {
            "name": "CSQ Avg Queue Time (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "AVERAGE('Call Manager - Common Skill CSQ'[Avg Queue Time]) * [Sec per Day]",
            "formatString": "0",
            "lineageTag": "4b619389-17c4-4fc4-b734-f949f0512cf0"
          },
          {
            "name": "Sec per Day",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Hidden",
            "expression": "86400",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "326107cb-6fd4-4e87-b474-eca08f10e7f0"
          },
          {
            "name": "CSQ Avg Queue Time (mm:ss)",
            "displayFolder": "Common Skill CSQ",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [CSQ Avg Queue Time (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([CSQ Avg Queue Time (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )",
              "    "
            ],
            "lineageTag": "a769b6eb-b8cf-488b-a321-76e71eac71e1"
          },
          {
            "name": "CSQ Max Queue Time (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "MAX('Call Manager - Common Skill CSQ'[Max Queue Time]) * [Sec per Day]",
            "formatString": "0",
            "lineageTag": "8f288b61-f9e2-4671-8b52-01656d4386cc"
          },
          {
            "name": "CSQ Max Queue Time (mm:ss)",
            "displayFolder": "Common Skill CSQ",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [CSQ Max Queue Time (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([CSQ Max Queue Time (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )",
              "    "
            ],
            "lineageTag": "9973c442-4fcf-4ea7-84d5-bad68d57fbdf"
          },
          {
            "name": "CSQ Max Handle Time (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "MAX('Call Manager - Common Skill CSQ'[Max Handle Time]) * [Sec per Day]",
            "formatString": "0",
            "lineageTag": "9873e66c-a6ca-4ad1-ad69-b2d26d70f59c"
          },
          {
            "name": "CSQ Max Handle Time (mm:ss)",
            "displayFolder": "Common Skill CSQ",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [CSQ Max Handle Time (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([CSQ Max Handle Time (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )",
              "    "
            ],
            "lineageTag": "31b42f45-3c01-4bf0-825d-4efd21a6c752"
          },
          {
            "name": "CSQ Avg Total Call Time (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "[CSQ Avg Handle Time (s)] + [CSQ Avg Queue Time (s)]",
            "lineageTag": "a5028f92-4546-40d3-894c-d17042c419e9"
          },
          {
            "name": "CSQ Avg Total Call Time (mm:ss)",
            "displayFolder": "Common Skill CSQ",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [CSQ Avg Total Call Time (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([CSQ Avg Total Call Time (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )",
              "    "
            ],
            "lineageTag": "2bbf04f0-61b4-4a4c-ab33-4f593bcc61c6"
          },
          {
            "name": "CSQ Avg Handle Time %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "[CSQ Avg Handle Time (s)]/[CSQ Avg Total Call Time (s)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f9ced1a3-247e-41ae-a3c8-e5df48ea9e2b"
          },
          {
            "name": "CSQ Avg Queue Time %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "[CSQ Avg Queue Time (s)]/[CSQ Avg Total Call Time (s)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6a4e1f7c-b48e-42d2-8ec6-0990472029b2"
          },
          {
            "name": "App Avg Abandon Time (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "App Summary",
            "expression": "AVERAGE('Call Manager - App Summary'[Avg Abandon Time]) * [Sec per Day]",
            "lineageTag": "054f9c77-5b69-4be7-9894-b1d0a59a1eff"
          },
          {
            "name": "App Avg Abandon Time (mm:ss)",
            "displayFolder": "App Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [App Avg Abandon Time (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([App Avg Abandon Time (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "d6a28890-222f-4ac6-8488-148557bc8ec8"
          },
          {
            "name": "App Avg Speed Answer (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "App Summary",
            "expression": "AVERAGE('Call Manager - App Summary'[Avg Speed Of Answer]) * [Sec per Day]",
            "lineageTag": "f9f9db6e-c96d-46a1-ab50-d4b26463d263"
          },
          {
            "name": "App Avg Speed Answer (mm:ss)",
            "displayFolder": "App Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [App Avg Speed Answer (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([App Avg Speed Answer (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "6aa2af23-d470-47b0-98c9-0eab214b7525"
          },
          {
            "name": "App Avg Talk (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "App Summary",
            "expression": "AVERAGE('Call Manager - App Summary'[Avg Talk Time]) * [Sec per Day]",
            "lineageTag": "4db11cac-a2d5-490b-b532-910beb695f5c"
          },
          {
            "name": "App Avg Work (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "App Summary",
            "expression": "AVERAGE('Call Manager - App Summary'[Avg Work Time]) * [Sec per Day]",
            "lineageTag": "1a605216-0235-485f-90c9-09f082d55b03"
          },
          {
            "name": "App Avg Talk (mm:ss)",
            "displayFolder": "App Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [App Avg Talk (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([App Avg Talk (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "d035fb5b-6fd1-479c-8c38-2c651003dcdc"
          },
          {
            "name": "App Avg Work (mm:ss)",
            "displayFolder": "App Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [App Avg Work (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([App Avg Work (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "3070b7ec-b4d7-4c27-a0c6-e950975b88c6"
          },
          {
            "name": "Agent Avg Call (s)",
            "displayFolder": "Agent Call Summary",
            "expression": "AVERAGE('Call Manager - Agent Call Summary'[Avg Call Time_2]) * [Sec per Day]",
            "formatString": "0",
            "lineageTag": "2050e92d-f0a4-4af3-a3ab-b2fb7f41c287"
          },
          {
            "name": "Agent Avg Hold (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "AVERAGE('Call Manager - Agent Call Summary'[Avg Hold Time]) * [Sec per Day]",
            "lineageTag": "5529414c-acde-4238-bae6-5d9f111ed07c"
          },
          {
            "name": "Agent Avg Talk (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "AVERAGE('Call Manager - Agent Call Summary'[Avg Talk Time]) * [Sec per Day]",
            "lineageTag": "01157fed-3e4f-45cb-8a3b-d635d2576935"
          },
          {
            "name": "Agent Avg Work (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "AVERAGE('Call Manager - Agent Call Summary'[Avg Work Time]) * [Sec per Day]",
            "lineageTag": "3bb8c99b-2fb0-4610-8544-4f1dec6c6eaf"
          },
          {
            "name": "Agent Max Call (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "MAX('Call Manager - Agent Call Summary'[Max Call Time]) * [Sec per Day]",
            "lineageTag": "43d4790b-1bdc-4710-998b-28f28e72b229"
          },
          {
            "name": "Agent Max Talk (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "MAX('Call Manager - Agent Call Summary'[Max Talk Time]) * [Sec per Day]",
            "lineageTag": "72cc458d-5675-4edf-91dd-287fc4136d91"
          },
          {
            "name": "Agent Avg Call (mm:ss)",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Agent Avg Call (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Agent Avg Call (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "528cb3a5-dbe3-4a36-9761-c84729e33a3c"
          },
          {
            "name": "Agent Avg Hold (mm:ss)",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Agent Avg Hold (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Agent Avg Hold (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "44031dc1-fc52-43a0-ba57-8f31183b7fc8"
          },
          {
            "name": "Agent Avg Talk (mm:ss)",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Agent Avg Talk (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Agent Avg Talk (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "6aeda574-81e5-49de-b72d-db91692937bf"
          },
          {
            "name": "Agent Avg Work (mm:ss)",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Agent Avg Work (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Agent Avg Work (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "6181d0a2-11c0-4a18-9043-aad9171ce1d9"
          },
          {
            "name": "Agent Max Call (mm:ss)",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Agent Max Call (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Agent Max Call (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "7ee5c9b4-6a1a-4356-acd3-8b562fabe0c5"
          },
          {
            "name": "Agent Max Talk (mm:ss)",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Agent Max Talk (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Agent Max Talk (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "0e8e37f2-39f0-4df5-a40a-27e27bce1286"
          },
          {
            "name": "Agent Avg Talk_1 (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "AVERAGE('Call Manager - Agent Call Summary'[Avg Talk Time_1]) * [Sec per Day]",
            "lineageTag": "5d8707b4-7fb2-45da-be68-4134dd35ae16"
          },
          {
            "name": "Agent Avg Talk_1 (mm:ss)",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Agent Avg Talk_1 (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Agent Avg Talk_1 (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "ae24fb19-41a0-47db-abfd-59e37344515a"
          },
          {
            "name": "Agent Total Inbound Total",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "IF(Sum('Call Manager - Agent Call Summary'[Total Inbound]) = BLANK()",
              "    , BLANK()",
              "    ,CALCULATE(",
              "        Sum('Call Manager - Agent Call Summary'[Total Inbound])",
              "        , REMOVEFILTERS('DC - User'[Name])",
              "        )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "61a65303-bc6e-4620-a61d-47873e7cb4c5"
          },
          {
            "name": "Agent Inbound ACD Total %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "Sum('Call Manager - Agent Call Summary'[Inbound ACD Total]) / [Agent Total Inbound Total]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "db0c0880-59e1-4cd6-9f79-342cac500aa6"
          },
          {
            "name": "Agent Total Inbound ACD Total",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "CALCULATE(",
              "    Sum('Call Manager - Agent Call Summary'[Inbound ACD Total])",
              "    , REMOVEFILTERS('DC - User'[Name])",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "6e09c537-fe40-4cf6-b45f-d7cb34b85199"
          },
          {
            "name": "Agent Inbound Total %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "Sum('Call Manager - Agent Call Summary'[Total Inbound]) / [Agent Total Inbound Total]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e0a5866d-a1f6-44b6-a909-3acb3cd96cb2"
          },
          {
            "name": "CSQ Service Level %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Common Skill CSQ\\Weekly",
            "expression": "AVERAGE('Call Manager - Common Skill CSQ'[Service Level]) / 100",
            "lineageTag": "38d691d7-5edb-4890-8ac5-f0e0815d09d1"
          },
          {
            "name": "CSQ Service Level % L1W",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Common Skill CSQ\\Weekly",
            "expression": [
              "",
              "CALCULATE(",
              "    Average( 'Call Manager - Common Skill CSQ'[Service Level]) / 100",
              "    ,DATEADD('Date'[Date],-7,DAY)",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f8fdd1f5-88ea-4c27-b104-b27a71162308"
          },
          {
            "name": "CSQ Service Level % L4W",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Common Skill CSQ\\Weekly",
            "expression": [
              "",
              "CALCULATE(",
              "    Average( 'Call Manager - Common Skill CSQ'[Service Level]) / 100",
              "    ,DATEADD('Date'[Date],-28,DAY)",
              ")"
            ],
            "lineageTag": "083b31fb-f928-403e-a8e4-2d2bd7b36726"
          },
          {
            "name": "CSQ Calls Presented LY",
            "displayFolder": "Common Skill CSQ\\Year",
            "expression": [
              "",
              "CALCULATE(",
              "    Sum( 'Call Manager - Common Skill CSQ'[Calls Presented])",
              "    ,DATEADD('Date'[Date],-1,YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a0f9c24c-31a9-478f-8145-2414bccc7d6f"
          },
          {
            "name": "CSQ Service Level % LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Common Skill CSQ\\Year",
            "expression": [
              "",
              "CALCULATE(",
              "    Average( 'Call Manager - Common Skill CSQ'[Service Level]) / 100",
              "    ,DATEADD('Date'[Date],-1,YEAR)",
              ")"
            ],
            "lineageTag": "9ba13a54-5ea5-420f-8175-ccd6bf2d4b30"
          },
          {
            "name": "Total Mail - Processed",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Mail Processed - Business] + [Mail Processed - Renewals] + [Mail Processed - MM] + [Mail Processed - Salvages]",
            "formatString": "#,##0",
            "lineageTag": "855b2330-11f1-4bef-b6e4-99c8ae0d5066"
          },
          {
            "name": "Mail Processed - Business",
            "displayFolder": "Staff Stats\\Business",
            "expression": [
              "Sum('Staff Stats - Physical Mail'[Enterprise-Pro])",
              "+ SUM('Staff Stats - Physical Mail'[Business-Renewal-Pro])",
              "+ SUM('Staff Stats - Physical Mail'[Business-MM-Pro])",
              "+ SUM('Staff Stats - Physical Mail'[Business-Communications-Pro])",
              "+ SUM('Staff Stats - Physical Mail'[Dealer-Renewal-Pro])",
              "+ SUM('Staff Stats - Physical Mail'[Dealer-MM-Pro])",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "00d59012-5c46-4854-9c80-5f634e6ef197"
          },
          {
            "name": "Qmatic Visit",
            "displayFolder": "Qmatic\\Counts",
            "expression": "COUNTROWS('Qmatic - Visit Transaction')",
            "formatString": "0",
            "lineageTag": "9a2f0b5c-8fbb-4d74-a97e-5f79bdd97598"
          },
          {
            "name": "Qmatic Visit YTD",
            "displayFolder": "Qmatic\\Counts",
            "expression": [
              "",
              "TOTALYTD(",
              "    COUNTROWS( 'Qmatic - Visit Transaction' )",
              "    ,'Date'[Date]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3ce190d8-814e-41ef-ba2c-6d682b442b8b"
          },
          {
            "name": "Qmatic Day Count",
            "displayFolder": "Qmatic\\Counts",
            "expression": [
              "DISTINCTCOUNT('Qmatic - Visit Transaction'[Date Key])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "2f9bd442-76cd-4e4b-ac9a-9495b2ba8a9c"
          },
          {
            "name": "Qmatic Avg Daily Visit",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Qmatic\\Counts",
            "expression": "[Qmatic Visit]/[Qmatic Day Count]",
            "formatString": "0",
            "lineageTag": "7c03318a-a213-456d-bc4e-dc11a921d794"
          },
          {
            "name": "Qmatic Day Count YTD",
            "displayFolder": "Qmatic\\Counts",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT( 'Qmatic - Visit Transaction'[Date Key] )",
              "    ,DATESYTD ( 'Date'[Date] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "525db27a-49ab-435d-971b-273952191bf2"
          },
          {
            "name": "Qmatic Avg Daily Visit YTD",
            "displayFolder": "Qmatic\\Counts",
            "expression": "[Qmatic Visit YTD]/[Qmatic Day Count YTD]",
            "formatString": "0",
            "lineageTag": "a1f26eb1-4d72-4136-b2d1-ca204cb5572b"
          },
          {
            "name": "Qmatic Visit R3M",
            "displayFolder": "Qmatic\\Counts",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('Qmatic - Visit Transaction')",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4aba4456-b28e-4eec-9f24-0185649c17cd"
          },
          {
            "name": "Total Work Days",
            "displayFolder": "Date",
            "expression": "CALCULATE(count('Date'[DateKey]), 'Date'[Is Work Day] = TRUE())",
            "formatString": "0",
            "lineageTag": "9475d392-e137-4e4e-982b-7ff117a24445"
          },
          {
            "name": "Qmatic Day Count R3M",
            "displayFolder": "Qmatic\\Counts",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('Qmatic - Visit Transaction'[Date Key])",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bf73b57c-da86-49dd-9dff-e233feb5f6ad"
          },
          {
            "name": "Qmatic Avg Daily Visit R3M",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Qmatic\\Counts",
            "expression": "[Qmatic Visit R3M]/[Qmatic Day Count R3M]",
            "formatString": "0",
            "lineageTag": "a4a86923-6f22-4787-aa60-6511e919bef3"
          },
          {
            "name": "Qmatic Transaction Time (s)",
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": "Sum('Qmatic - Visit Transaction'[Transaction Time])",
            "formatString": "0",
            "lineageTag": "3c63ae66-fb7b-4428-ba94-f5cb199826cd"
          },
          {
            "name": "Qmatic Staff Transaction Time (s)",
            "displayFolder": "Qmatic\\Staff Transaction Time",
            "expression": "Sum('Qmatic - Visit Transaction'[Staff Transaction Time])",
            "formatString": "0",
            "lineageTag": "653bb7d5-9cfc-4e05-9600-7b259b5d55de"
          },
          {
            "name": "Qmatic Wait Time (s)",
            "displayFolder": "Qmatic\\Wait Times",
            "expression": "Sum('Qmatic - Visit Transaction'[Waiting Time])",
            "formatString": "0",
            "lineageTag": "6de078f1-ce89-41bf-9af7-42fe8cffe7a7"
          },
          {
            "name": "Qmatic Staff Transaction Time (hh:mm:ss)",
            "displayFolder": "Qmatic\\Staff Transaction Time",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Qmatic Staff Transaction Time (s)]",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "     IF ( LEN ( Hours ) = 1, ",
              "         CONCATENATE ( \"0\", Hours ),",
              "         CONCATENATE ( \"\", Hours )",
              "       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Qmatic Staff Transaction Time (s)] = BLANK()",
              "    , BLANK()",
              "    ,CONCATENATE (",
              "        H,",
              "        CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     )",
              "    ))"
            ],
            "lineageTag": "ed8cb28d-7058-45cb-84fc-ccdf2ed58850"
          },
          {
            "name": "Qmatic Staff Transaction Time Avg (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Qmatic\\Staff Transaction Time",
            "expression": "AVERAGE('Qmatic - Visit Transaction'[Staff Transaction Time])",
            "lineageTag": "6d903830-ce0f-4a10-b6d3-7bdb59ccb11e"
          },
          {
            "name": "Qmatic Staff Transaction Time Avg (mm:ss)",
            "displayFolder": "Qmatic\\Staff Transaction Time",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Qmatic Staff Transaction Time Avg (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Qmatic Staff Transaction Time Avg (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "ae6e2f6f-eb04-4d4f-840f-b2a11fa020b7"
          },
          {
            "name": "Qmatic Wait Time Avg (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Qmatic\\Wait Times",
            "expression": "AVERAGE('Qmatic - Visit Transaction'[Waiting Time])",
            "lineageTag": "05f1d462-2bf4-4ffd-b68e-433ba3ddce33"
          },
          {
            "name": "Qmatic Wait Time Avg (mm:ss)",
            "displayFolder": "Qmatic\\Wait Times",
            "expression": [
              "",
              "// Duration formatting ",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Qmatic Wait Time Avg (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Qmatic Wait Time Avg (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "e2ffdd37-5dec-4d71-bc4c-688e6919b6cc"
          },
          {
            "name": "Qmatic Transaction Time Avg (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": "AVERAGE('Qmatic - Visit Transaction'[Transaction Time])",
            "lineageTag": "fc86d370-7f48-4521-a068-073056cd319c"
          },
          {
            "name": "Qmatic Transaction Time Avg (mm:ss)",
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": [
              "",
              "// Duration formatting ",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Qmatic Transaction Time Avg (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Qmatic Transaction Time Avg (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "34403ef7-c5b8-4ff6-9357-b2e68adac20e"
          },
          {
            "name": "Qmatic Staff Transaction Time Max (s)",
            "displayFolder": "Qmatic\\Staff Transaction Time",
            "expression": "MAX('Qmatic - Visit Transaction'[Staff Transaction Time])",
            "formatString": "0",
            "lineageTag": "2b8cbaec-6f29-4d3e-9938-1c9844e76a0a"
          },
          {
            "name": "Qmatic Staff Transaction Time Min (s)",
            "displayFolder": "Qmatic\\Staff Transaction Time",
            "expression": "MIN('Qmatic - Visit Transaction'[Staff Transaction Time])",
            "formatString": "0",
            "lineageTag": "a5bcf16c-ee4a-4a65-8b20-1ff7faad59e6"
          },
          {
            "name": "Qmatic Transaction Time Max (s)",
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": "MAX('Qmatic - Visit Transaction'[Transaction Time])",
            "formatString": "0",
            "lineageTag": "c2314cd7-0fd1-4769-9fc8-b45b02eafb6a"
          },
          {
            "name": "Qmatic Transaction Time Min (s)",
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": "Min('Qmatic - Visit Transaction'[Transaction Time])",
            "formatString": "0",
            "lineageTag": "f517e583-265b-400a-8b8a-3a10e52d4095"
          },
          {
            "name": "Qmatic Transaction Time Min (mm:ss)",
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": [
              "",
              "// Duration formatting ",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Qmatic Transaction Time Min (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Qmatic Transaction Time Min (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "397a4dbf-d736-4117-aa16-c4d146543ea1"
          },
          {
            "name": "Qmatic Wait Time Min (s)",
            "displayFolder": "Qmatic\\Wait Times",
            "expression": "Min('Qmatic - Visit Transaction'[Waiting Time])",
            "formatString": "0",
            "lineageTag": "842e0dba-b983-44cb-9bc3-8393bbdbe753"
          },
          {
            "name": "Qmatic Wait Time Max (s)",
            "displayFolder": "Qmatic\\Wait Times",
            "expression": "Max('Qmatic - Visit Transaction'[Waiting Time])",
            "formatString": "0",
            "lineageTag": "8ca7d41f-413b-4187-a3a5-5b7b42347021"
          },
          {
            "name": "Qmatic Wait Time Min (mm:ss)",
            "displayFolder": "Qmatic\\Wait Times",
            "expression": [
              "",
              "// Duration formatting ",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Qmatic Wait Time Min (s)]",
              "// There are 3,600 seconds in an hour",
              "// VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "// VAR H =",
              "//     IF ( LEN ( Hours ) = 1, ",
              "//         CONCATENATE ( \"0\", Hours ),",
              "//         CONCATENATE ( \"\", Hours )",
              "//       )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Qmatic Wait Time Min (s)] = BLANK()",
              "    , BLANK()",
              "    ,//CONCATENATE (",
              "        //H,",
              "        //CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     //)",
              "    )"
            ],
            "lineageTag": "e916acf5-d92a-4acf-aab3-64fe843ccaf6"
          },
          {
            "name": "Qmatic Wait Time Max (mm:ss)",
            "displayFolder": "Qmatic\\Wait Times",
            "expression": [
              "",
              "// Duration formatting ",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Qmatic Wait Time Max (s)]",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( INT ( Duration / 3600) * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF ([Qmatic Wait Time Max (s)] = BLANK()",
              "    , BLANK()",
              "    ,CONCATENATE (",
              "        H,",
              "        CONCATENATE ( \":\", ",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "     )",
              "    ))"
            ],
            "lineageTag": "fd03eb7b-9823-4470-8ca9-c07f197042e8"
          },
          {
            "name": "Drives Transaction Count",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": "DISTINCTCOUNT('Drives - Time Tracking'[Case Key])",
            "formatString": "#,0",
            "lineageTag": "83e1f922-3644-4b98-a230-269ef4b54c24"
          },
          {
            "name": "Drives Avg Transaction Duration (hh:mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = AVERAGE('Drives - Time Tracking'[Transaction Time])",
              "// There are 3,600 seconds in an hour",
              "VAR Hours =",
              "    INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (AVERAGE('Drives - Time Tracking'[Transaction Time]) = BLANK()",
              "    , BLANK()",
              "    , CONCATENATE (",
              "        H,",
              "        CONCATENATE (CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ), \" (hh:mm:ss)\")",
              "    ))"
            ],
            "lineageTag": "49696c47-f2e5-46ff-940d-b8b60a88547d"
          },
          {
            "name": "Transaction Duration (h)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": "SUM('Drives - Time Tracking'[Transaction Time]) / 3600",
            "lineageTag": "2617cb8d-18eb-4f79-918f-44b9a757458a"
          },
          {
            "name": "Transaction Duration (m)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": "Sum('Drives - Time Tracking'[Transaction Time]) / 60",
            "formatString": "0.00",
            "lineageTag": "ab340400-974a-4548-bdc0-b8122c504d82"
          },
          {
            "name": "Drives Total Duration (hh:mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = Sum('Drives - Time Tracking'[Total Time])",
              "// There are 3,600 seconds in an hour",
              "VAR Hours =",
              "    INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    CONCATENATE (",
              "        H,",
              "        CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) )",
              "    )"
            ],
            "lineageTag": "6a98a284-a0b6-47cc-8b0e-f0327d2faaf7"
          },
          {
            "name": "Drives Fee Waiver Count",
            "displayFolder": "Drives\\Fee Waiver",
            "expression": "COUNTROWS('Drives - Fee Waiver Tracking')",
            "formatString": "0",
            "lineageTag": "65e10e27-3984-4c39-b24a-7b9a89f48afc"
          },
          {
            "name": "Drives Title Errors Count",
            "displayFolder": "Drives\\Title Errors",
            "expression": "COUNTROWS('Drives - Title Application Errors')",
            "formatString": "0",
            "lineageTag": "71ba3031-9661-4b8d-b6ea-910e8c97ac92"
          },
          {
            "name": "Drives Avg Transaction Duration (s)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": "AVERAGE('Drives - Time Tracking'[Transaction Time])",
            "formatString": "0",
            "lineageTag": "b2f3c98a-d427-430e-9db0-40c11ac2fe97"
          },
          {
            "name": "Drives Transaction Duration Max (hh:mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = MAX('Drives - Time Tracking'[Transaction Time])",
              "// There are 3,600 seconds in an hour",
              "VAR Hours =",
              "    INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    CONCATENATE (",
              "        H,",
              "        CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) )",
              "    )"
            ],
            "lineageTag": "9140b291-13a1-4c05-b761-6d6b271033ad"
          },
          {
            "name": "Drives Transaction Duration Min (hh:mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = MIN('Drives - Time Tracking'[Transaction Time])",
              "// There are 3,600 seconds in an hour",
              "VAR Hours =",
              "    INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    CONCATENATE (H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )"
            ],
            "lineageTag": "279878c8-6394-4073-8018-9b840da590c0"
          },
          {
            "name": "Drives Day Count R3M",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('Drives - Time Tracking'[Transaction Date])",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3a17b9b4-a629-481f-9b3f-61db849bd779"
          },
          {
            "name": "Drives Transaction Count YTD",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "TOTALYTD(",
              "    COUNTROWS( 'Drives - Time Tracking' )",
              "    ,'Date'[Date]",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "8eed9742-dc0a-401c-9ca0-f1e9b450a663"
          },
          {
            "name": "Drives Transaction Count R3M",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS( 'Drives - Time Tracking' )",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "b92b82c6-07e4-4bba-ab4f-dae0b94c592e"
          },
          {
            "name": "Drives Day Count",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": "DISTINCTCOUNT('Drives - Time Tracking'[Transaction Date])",
            "formatString": "0",
            "lineageTag": "73f39b9a-7741-402c-9731-ba744077afa5"
          },
          {
            "name": "Drives Avg Transaction Count",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": "[Drives Transaction Count] / [Drives Day Count]",
            "formatString": "#,0",
            "lineageTag": "74b0281f-5099-4246-a51c-bb37cb4d1ea1"
          },
          {
            "name": "Drives Day Count YTD",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT( 'Drives - Time Tracking'[Transaction Date] )",
              "    ,DATESYTD ( 'Date'[Date] )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c9015ac4-9366-415b-9bcb-14ec2996c290"
          },
          {
            "name": "Drives Avg Transaction Count YTD",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": "[Drives Transaction Count YTD] / [Drives Day Count YTD]",
            "formatString": "#,0",
            "lineageTag": "b3a21ce8-09a5-4338-8f57-82ad8085f5a2"
          },
          {
            "name": "Drives Avg Transaction Count R3M",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": "[Drives Transaction Count R3M] / [Drives Day Count R3M]",
            "formatString": "#,0",
            "lineageTag": "4143c4a8-607b-47d6-b15e-8875b45a189a"
          },
          {
            "name": "Drives Avg Transaction Duration YTD (s)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Drives - Time Tracking'[Transaction Time] )",
              "    ,DATESYTD ('Date'[Date])",
              ")",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f479dead-af3b-4347-b54b-0ad06a909d61"
          },
          {
            "name": "Drives Avg Transaction Duration YTD (hh:mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Drives Avg Transaction Duration YTD (s)]",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    CONCATENATE ( H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )"
            ],
            "lineageTag": "d5fc2b2d-30ca-458a-bd2f-76e3e43ba7d0"
          },
          {
            "name": "Drives Avg Transaction Duration R3M (s)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Drives - Time Tracking'[Transaction Time] )",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6bc1b4bd-3b38-4c28-9d5a-54405171ccfa"
          },
          {
            "name": "Drives Avg Transaction Duration R3M (hh:mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Drives Avg Transaction Duration R3M (s)]",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    CONCATENATE ( H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )"
            ],
            "lineageTag": "3e27321a-7322-49cf-87c0-7ed8ca4788b5"
          },
          {
            "name": "Drives Avg Title Errors Count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Title Errors",
            "expression": "[Drives Title Errors Count] / [Drives Day Count]",
            "lineageTag": "e04330d0-f528-4a9f-81fa-1a4065ed6f09"
          },
          {
            "name": "Drives Avg Title Errors Count YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Title Errors",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS( 'Drives - Title Application Errors' )",
              "    ,DATESYTD ('Date'[Date])",
              ") / [Drives Day Count YTD]"
            ],
            "lineageTag": "4cb3eb96-fc45-4399-8cf7-fed348a98e5a"
          },
          {
            "name": "Drives Avg Title Errors Count R3M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Title Errors",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS( 'Drives - Title Application Errors' )",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ") / [Drives Day Count R3M]"
            ],
            "lineageTag": "1e3bbbb9-c09b-4aae-835f-8f5e480c5fa1"
          },
          {
            "name": "Drives Fee Stats Amount Assesed",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Fee Stats",
            "expression": "SUM('Drives - Fee Statistics'[Amount Assessed])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "18c46254-36c1-45ec-960d-3af2833e3fac"
          },
          {
            "name": "Drives Fee Stats Count",
            "displayFolder": "Drives\\Fee Stats",
            "expression": "COUNTROWS('Drives - Fee Statistics')",
            "formatString": "0",
            "lineageTag": "9f2ccafe-7868-41b0-82ec-bac24b505d32"
          },
          {
            "name": "Drives Fee Stats Amount Assesed YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Fee Stats",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Statistics'[Amount Assessed])",
              "    ,DATESYTD ( 'Date'[Date])",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "af81fae4-a02e-4c38-85f1-d0948538dc7a"
          },
          {
            "name": "Drives Avg Fee Stats Amount Assesed R3M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Fee Stats",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Statistics'[Amount Assessed])",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ") / 3"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c832e34c-b9ef-4ae3-bc6f-3e0f9c80114b"
          },
          {
            "name": "Drives Fee Waiver Calculated",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": "SUM('Drives - Fee Waiver Tracking'[Calculated Amount])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c00f8548-f68d-46a0-a144-341cd4e8e123"
          },
          {
            "name": "Drives Avg Fee Waiver Calculated R3M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Waiver Tracking'[Calculated Amount])",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ") / 3",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8258fc54-5a87-4ae2-b8cf-befcc1334a20"
          },
          {
            "name": "Drives Fee Waiver Calculated YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Waiver Tracking'[Calculated Amount])",
              "    ,DATESYTD ( 'Date'[Date])",
              ")",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a934f116-8037-4ed6-acb6-c91f57a0e8ae"
          },
          {
            "name": "Drives Fee Waiver Charged",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": "SUM('Drives - Fee Waiver Tracking'[Amount Charged])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "a03f9604-0478-4cb8-a867-64df8fce422d"
          },
          {
            "name": "Drives Avg Fee Waiver Charged R3M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Waiver Tracking'[Amount Charged])",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ") / 3"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "c69683d6-dc7e-49ba-8386-947efab0b288"
          },
          {
            "name": "Drives Fee Waiver Charged YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Waiver Tracking'[Amount Charged])",
              "    ,DATESYTD ( 'Date'[Date])",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1451a287-f5b5-4887-bdd5-c4e382017dc5"
          },
          {
            "name": "Drives Fee Waiver",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": "SUM('Drives - Fee Waiver Tracking'[Waived Amount])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "8c806535-517e-4da1-9ee9-d8a57a4cb740"
          },
          {
            "name": "Drives Avg Fee Waiver R3M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Waiver Tracking'[Waived Amount])",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ") / 3"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "617ab3a9-4979-4dc5-8bb2-8be53c018c85"
          },
          {
            "name": "Drives Fee Waiver YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Drives\\Fee Waiver",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Fee Waiver Tracking'[Waived Amount])",
              "    ,DATESYTD ( 'Date'[Date])",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "add4f209-fc45-4864-bf66-c16cc2447d03"
          },
          {
            "name": "Drives Financials Amount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "SUM('Drives - Financials'[Amount])",
            "lineageTag": "b0022e56-ca2b-4454-9af2-ede705f73215"
          },
          {
            "name": "Drives Avg Financials Amount R3M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Financials'[Amount])",
              "    ,DATESINPERIOD (",
              "        'Date'[Date],",
              "        LASTDATE ( 'Date'[Date] ), -3, MONTH",
              "    )",
              ") / 3"
            ],
            "lineageTag": "16b41635-be63-462c-85c5-95da737b9f49"
          },
          {
            "name": "Drives Financials Amount YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Financials'[Amount])",
              "    ,DATESYTD ( 'Date'[Date])",
              ")"
            ],
            "lineageTag": "d3531105-d445-42f7-879b-e791ed2c6a88"
          },
          {
            "name": "Drives Financials Amount LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Financials'[Amount])",
              "    ,DATEADD('Date'[Date],-1,MONTH)",
              ")"
            ],
            "lineageTag": "ee16f599-e37c-46e1-85b3-d58e498ab52c"
          },
          {
            "name": "Drives Financials Amount LQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Financials'[Amount])",
              "    ,DATEADD('Date'[Date],-4,MONTH)",
              ")"
            ],
            "lineageTag": "2236dc34-5c31-4ef3-9ad0-e1bfe443862f"
          },
          {
            "name": "Drives Financials Amount LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Financials'[Amount])",
              "    ,DATEADD('Date'[Date],-1,YEAR)",
              ")"
            ],
            "lineageTag": "daded474-e96b-43df-8101-652d999427de"
          },
          {
            "name": "Drives Financials Amount Var LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "[Drives Financials Amount] - [Drives Financials Amount LM]",
            "lineageTag": "2e770861-0493-4b22-bf54-88529e0140de"
          },
          {
            "name": "Drives Financials Amount Var LQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "[Drives Financials Amount] - [Drives Financials Amount LQ]",
            "lineageTag": "12a3fbf3-fd3e-4670-a675-ae2bc957e701"
          },
          {
            "name": "Drives Financials Amount Var LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "[Drives Financials Amount] - [Drives Financials Amount LY]",
            "lineageTag": "741a2e5d-cac1-42ee-a4a4-e3999d6de0e9"
          },
          {
            "name": "Drives Financials Amount Var LM %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "([Drives Financials Amount] - [Drives Financials Amount LM]) / [Drives Financials Amount LM]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4e79651d-841c-471f-9bb4-fefd37c9bcdc"
          },
          {
            "name": "Drives Financials Amount Var LQ %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "([Drives Financials Amount] - [Drives Financials Amount LQ]) / [Drives Financials Amount LQ]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2885e55b-6b6f-4ea8-a4b7-71475222f6c4"
          },
          {
            "name": "Drives Financials Amount Var LY %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "([Drives Financials Amount] - [Drives Financials Amount LY]) / [Drives Financials Amount LY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dcc215c7-ecfc-46f6-a8cb-450873f99eff"
          },
          {
            "name": "Drives Financials Amount Var R3M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "[Drives Financials Amount] - [Drives Avg Financials Amount R3M]",
            "lineageTag": "37416479-ce0e-4325-81a5-ba7192b66473"
          },
          {
            "name": "Drives Financials Amount Var R3M %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "([Drives Financials Amount] - [Drives Avg Financials Amount R3M]) / [Drives Avg Financials Amount R3M]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c754c6fc-c7b0-447b-80fa-4cd0d128416a"
          },
          {
            "name": "Drives Financials Amount YTD LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Drives - Financials'[Amount])",
              "    ,DATESYTD ( DATEADD ('Date'[Date], -12, MONTH ) )",
              ")"
            ],
            "lineageTag": "4f60a4b6-96fc-41a0-8c12-df8531fcc056"
          },
          {
            "name": "Drives Financials Amount YTD Var",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "[Drives Financials Amount YTD] - [Drives Financials Amount YTD LY]",
            "lineageTag": "ad3e6624-c125-489c-a6c5-d1f657e997d9"
          },
          {
            "name": "Drives Financials Amount YTD Var %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Drives\\Financials",
            "expression": "([Drives Financials Amount YTD] - [Drives Financials Amount YTD LY]) / [Drives Financials Amount YTD LY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ccb50e7b-6033-4077-a256-4b8b661b102a"
          },
          {
            "name": "Snap Avg Chat Duration (m)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": "Sum(SnapEngage[Chat Duration]) / [Snap Chat Count] / 60",
            "lineageTag": "787ad97f-9348-4426-bfa5-083e0121410a"
          },
          {
            "name": "Snap Avg Chat Duration (mm:ss)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": [
              "",
              "",
              "// Duration formatting ",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Snap Avg Chat Duration (m)] * 60",
              "// There are 3,600 seconds in an hour",
              "VAR Hours =   INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "//VAR H =",
              "//    IF ( LEN ( Hours ) = 1, ",
              "//        CONCATENATE ( \"0\", Hours ),",
              "//        CONCATENATE ( \"\", Hours )",
              "//      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    if (IsBlank([Snap Avg Chat Duration (m)]),",
              "        BLANK(),",
              "        //CONCATENATE (H,CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) )",
              "        CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ",
              "        //TIME(H,M,S)",
              "    )"
            ],
            "lineageTag": "8a91035c-8386-4706-a506-3f960964bf22"
          },
          {
            "name": "Snap Avg Chat Waittime",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": "AVERAGE(SnapEngage[Chat Waittime])",
            "lineageTag": "c2b5c30f-6a9b-4156-b1c7-874419bfd5f9"
          },
          {
            "name": "Snap Avg Survey Score",
            "displayFolder": "SnapEngage",
            "expression": "AVERAGE(SnapEngage[Survey Score])",
            "formatString": "0.00",
            "lineageTag": "c939796e-a919-497f-be9e-26b34e62b239"
          },
          {
            "name": "Snap Chat Count",
            "displayFolder": "SnapEngage",
            "expression": "COUNTROWS(SnapEngage)",
            "formatString": "0",
            "lineageTag": "43486699-5bee-4993-a9fe-0ecee116aa6a"
          },
          {
            "name": "Snap Chat Duration (m)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": "Sum(SnapEngage[Chat Duration]) / 60",
            "lineageTag": "a31e56fe-d792-4308-9236-331a20a41b1a"
          },
          {
            "name": "Snap Survey Count",
            "displayFolder": "SnapEngage",
            "expression": "count(SnapEngage[Survey Score])",
            "formatString": "0",
            "lineageTag": "0a078282-fded-49f5-8a66-ee449accd272"
          },
          {
            "name": "Has Data",
            "displayFolder": "Your Feedback Matters\\Has Data",
            "expression": "COUNTROWS('YFM - Your Feedback Matters')",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "28a3c57b-e89c-46fe-8421-fc2c2d6bd92d"
          },
          {
            "name": "Positive %",
            "displayFolder": "Your Feedback Matters\\Positive",
            "expression": "DIVIDE(sum('YFM - Your Feedback Matters'[IsPositive]), (sum('YFM - Your Feedback Matters'[IsPositive]) + sum('YFM - Your Feedback Matters'[IsNegative])))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a767464c-4985-4498-bcf0-5ef3aa3c3e3a"
          },
          {
            "name": "Transaction Completed",
            "displayFolder": "Your Feedback Matters\\Completed",
            "expression": "CALCULATE(COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"Yes\" )",
            "formatString": "0",
            "lineageTag": "d6e1695c-71c0-407d-917c-1f496888984b"
          },
          {
            "name": "Transaction Completed %",
            "displayFolder": "Your Feedback Matters\\Completed",
            "expression": "[Transaction Completed] / [Has Data]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "68b9a1bc-c460-4fca-90c8-2ca8a7ba9028"
          },
          {
            "name": "Transaction Incomplete",
            "displayFolder": "Your Feedback Matters\\Incomplete",
            "expression": "CALCULATE(COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"No\" )",
            "formatString": "0",
            "lineageTag": "5385ec11-93a2-41fb-af62-9e53ca561d4d"
          },
          {
            "name": "Transaction Incomplete %",
            "displayFolder": "Your Feedback Matters\\Incomplete",
            "expression": "[Transaction Incomplete]/[Has Data]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b5224f03-9dbe-441f-94f4-f37d9960fc52"
          },
          {
            "name": "Transaction Unanswered",
            "displayFolder": "Your Feedback Matters\\Unanswered",
            "expression": "CALCULATE(COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"\" )",
            "formatString": "0",
            "lineageTag": "8efbef94-c716-4129-b2e1-40a8180f5d28"
          },
          {
            "name": "Transaction Unanswered %",
            "displayFolder": "Your Feedback Matters\\Unanswered",
            "expression": "[Transaction Unanswered]/[Has Data]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "66522ce6-7bdd-4a30-9f80-3954c2f3e903"
          },
          {
            "name": "Count Work Days",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pay Type JDE",
            "expression": "DISTINCTCOUNT('Drives - Time Tracking'[Transaction Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cc11508d-b33e-438a-bad2-4bd0b6790659"
          },
          {
            "name": "Avg Hours per day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Pay Type JDE",
            "expression": "[Pay Hours Total] / [Count Work Days] / [Active Employee Count]",
            "isHidden": true,
            "lineageTag": "30ec3a61-842c-495d-8a9f-289319b6d664"
          },
          {
            "name": "Pay Hours Total",
            "displayFolder": "Pay Type JDE",
            "expression": "Sum('Pay Type JDE'[Hours])",
            "formatString": "#,0.00",
            "lineageTag": "e55c1a58-4ed9-4b5b-a8a8-54982bcf69cd"
          },
          {
            "name": "Active Employee Count",
            "displayFolder": "Pay Type JDE",
            "expression": "CALCULATE(DISTINCTCOUNT('Pay Type JDE'[Email Address]), 'Pay Type JDE'[Pay Status Code] = \"0\")",
            "formatString": "0",
            "lineageTag": "d0c332be-45e6-4684-a04f-2ebeba363c9a"
          },
          {
            "name": "Drives Transaction Count LM",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "IF(ISBLANK([Drives Transaction Count]), BLANK(),",
              "    CALCULATE(",
              "        COUNTROWS( 'Drives - Time Tracking' )",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "ad9852ac-e0af-4731-8b87-83a6fa644409"
          },
          {
            "name": "Drives Transaction Count LY",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "IF(ISBLANK([Drives Transaction Count]), BLANK(),",
              "    CALCULATE(",
              "        COUNTROWS( 'Drives - Time Tracking' )",
              "        ,SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "133e6b60-cce1-4ae0-b432-ae68aace0cf5"
          },
          {
            "name": "Drives Avg Transaction Duration LM (m)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "IF(ISBLANK([Drives Avg Transaction Duration (s)]), BLANK(),",
              "    CALCULATE(",
              "        AVERAGE('Drives - Time Tracking'[Transaction Time] )",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "    )",
              ") / 60"
            ],
            "lineageTag": "7f8db89c-996b-40b9-8f5c-b952133483a9"
          },
          {
            "name": "Drives Avg Transaction Duration LY (m)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "IF(ISBLANK([Drives Avg Transaction Duration (s)]), BLANK(),",
              "    CALCULATE(",
              "        AVERAGE('Drives - Time Tracking'[Transaction Time] )",
              "        ,SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ") / 60"
            ],
            "lineageTag": "a9e5a384-f7cf-4434-bf38-5d2fb026c4b8"
          },
          {
            "name": "Drives Avg Transaction Duration (m)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": "AVERAGE('Drives - Time Tracking'[Transaction Time]) / 60",
            "lineageTag": "813fef25-fedc-4210-9d71-5a583a90d8a5"
          },
          {
            "name": "Drives Avg Transaction Duration (mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = AVERAGE('Drives - Time Tracking'[Transaction Time])",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "//VAR H = ",
              "//    IF ( LEN ( Hours ) = 1, ",
              "//        CONCATENATE ( \"0\", Hours ),",
              "//        CONCATENATE ( \"\", Hours )",
              "//      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (AVERAGE('Drives - Time Tracking'[Transaction Time]) = BLANK()",
              "    , BLANK()",
              "    , CONCATENATE ( M, CONCATENATE ( \":\", S ) )",
              "    )"
            ],
            "lineageTag": "5f19afd0-39f3-47e2-b676-f312f9b17ef0"
          },
          {
            "name": "Overtime",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pay Type JDE",
            "expression": "calculate(sum('Pay Type JDE'[Hours]), 'Pay Type JDE'[PDBA Code Desc] = \"Overtime\")",
            "lineageTag": "cfedeb80-6807-4bc9-9bfc-e5bf3bad8bef"
          },
          {
            "name": "Regular",
            "displayFolder": "Pay Type JDE",
            "expression": "calculate(sum('Pay Type JDE'[Hours]), 'Pay Type JDE'[PDBA Code Desc] = \"Regular\")",
            "formatString": "#,0.00",
            "lineageTag": "379acc3e-2334-4913-9d11-03eb05248dc6"
          },
          {
            "name": "Overtime %",
            "displayFolder": "Pay Type JDE",
            "expression": "if([Pay Hours Total] > 0, [Overtime]/[Pay Hours Total], BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8d7ffef9-6889-4948-9745-832373b78b27"
          },
          {
            "name": "Sick %",
            "displayFolder": "Pay Type JDE",
            "expression": "if([Pay Hours Total] > 0, CALCULATE(sum('Pay Type JDE'[Hours]), 'Pay Type JDE'[PDBA Code] = \"Sick\")/[Pay Hours Total], BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7f1dbd07-caf6-4c4f-80a1-6715d93f5f70"
          },
          {
            "name": "Vacation %",
            "displayFolder": "Pay Type JDE",
            "expression": "if([Pay Hours Total] > 0, CALCULATE(sum('Pay Type JDE'[Hours]), 'Pay Type JDE'[PDBA Code] = \"vacation\")/[Pay Hours Total], BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4d6cab04-2207-4f8b-adb0-9400ba53f769"
          },
          {
            "name": "Regular %",
            "displayFolder": "Pay Type JDE",
            "expression": "if ([Pay Hours Total] > 0, [Regular]/[Pay Hours Total], Blank())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ebaa493a-a2f9-4eb4-a4b7-84755d3a5367"
          },
          {
            "name": "Drives Day Count LM",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('Drives - Time Tracking'[Transaction Date])",
              "    ,PREVIOUSMONTH('Date'[Date])",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f896a6bf-fcae-4ef3-8096-ff9fe69c0560"
          },
          {
            "name": "Drives Day Count LY",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('Drives - Time Tracking'[Transaction Date])",
              "    ,SAMEPERIODLASTYEAR('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "87c2bb0c-8059-4869-ab1f-e5c2587e0018"
          },
          {
            "name": "Drives Avg Transaction Duration LM (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Drives - Time Tracking'[Transaction Time] )",
              "    ,PREVIOUSMONTH('Date'[Date])",
              ")",
              ""
            ],
            "lineageTag": "208cc339-dd6d-4431-bf37-4d17760e7c71"
          },
          {
            "name": "Drives Avg Transaction Duration LY (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Drives - Time Tracking'[Transaction Time] )",
              "    ,SAMEPERIODLASTYEAR('Date'[Date])",
              ")"
            ],
            "lineageTag": "8ffc4411-b547-410c-a946-158248359c48"
          },
          {
            "name": "Drives Avg Transaction Duration LM (mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Drives Avg Transaction Duration LM (s)]",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "//VAR H = ",
              "//    IF ( LEN ( Hours ) = 1, ",
              "//        CONCATENATE ( \"0\", Hours ),",
              "//        CONCATENATE ( \"\", Hours )",
              "//      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (AVERAGE('Drives - Time Tracking'[Transaction Time]) = BLANK()",
              "    , BLANK()",
              "    , CONCATENATE ( M, CONCATENATE ( \":\", S ) )",
              "    )"
            ],
            "lineageTag": "73e4ee7c-50a6-4262-b8a3-26520ba57abc"
          },
          {
            "name": "Drives Avg Transaction Duration LY (mm:ss)",
            "displayFolder": "Drives\\Transaction Time\\Duration",
            "expression": [
              "",
              "// Duration formatting ",
              "// * @konstatinos 1/25/2016",
              "// * Given a number of seconds, returns a format of \"hh:mm:ss\"",
              "//",
              "// We start with a duration in number of seconds",
              "VAR Duration = [Drives Avg Transaction Duration LY (s)]",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "//VAR H = ",
              "//    IF ( LEN ( Hours ) = 1, ",
              "//        CONCATENATE ( \"0\", Hours ),",
              "//        CONCATENATE ( \"\", Hours )",
              "//      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (AVERAGE('Drives - Time Tracking'[Transaction Time]) = BLANK()",
              "    , BLANK()",
              "    , CONCATENATE ( M, CONCATENATE ( \":\", S ) )",
              "    )"
            ],
            "lineageTag": "a0d8d5a3-9f56-415d-9136-9aadcbae3ea9"
          },
          {
            "name": "Drives Avg Transaction Count LM",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": "[Drives Transaction Count LM] / [Drives Day Count LM]",
            "formatString": "#,0",
            "lineageTag": "e5d1aa72-dd53-420b-a91b-4c9c778e9bf6"
          },
          {
            "name": "Drives Avg Transaction Count LY",
            "displayFolder": "Drives\\Transaction Time\\Count",
            "expression": "[Drives Transaction Count LY] / [Drives Day Count LY]",
            "formatString": "#,0",
            "lineageTag": "e113c4ae-2fd9-4845-a082-bac86851849b"
          },
          {
            "name": "Qmatic Visit LM",
            "displayFolder": "Qmatic\\Counts",
            "expression": [
              "",
              "IF(ISBLANK([Qmatic Visit]), BLANK(),",
              "    CALCULATE(",
              "        COUNTROWS('Qmatic - Visit Transaction')",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "36c7236e-bd9a-4447-b779-3bb00a906130"
          },
          {
            "name": "Qmatic Visit LY",
            "displayFolder": "Qmatic\\Counts",
            "expression": [
              "",
              "IF(ISBLANK([Qmatic Visit]), BLANK(),",
              "    CALCULATE(",
              "        COUNTROWS('Qmatic - Visit Transaction')",
              "        ,SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "6f86b50e-2db4-47e7-a0dd-16a14f3b3f98"
          },
          {
            "name": "Qmatic Avg Transaction Time LM (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": [
              "",
              "IF(ISBLANK([Qmatic Transaction Time (s)]), BLANK(),",
              "    CALCULATE(",
              "        AVERAGE('Qmatic - Visit Transaction'[Transaction Time])",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "    )",
              ")"
            ],
            "lineageTag": "fe1e4dbe-5f58-476b-9322-001e0e261ed5"
          },
          {
            "name": "Qmatic Avg Transaction Time LY (s)",
            "displayFolder": "Qmatic\\Transaction Times",
            "expression": [
              "",
              "IF(ISBLANK([Qmatic Transaction Time (s)]), BLANK(),",
              "    CALCULATE(",
              "        AVERAGE('Qmatic - Visit Transaction'[Transaction Time])",
              "        ,SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d1b17ea4-c233-4ded-acbc-f9a2401f58a8"
          },
          {
            "name": "Qmatic Avg Wait Time LM (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Qmatic\\Wait Times",
            "expression": [
              "",
              "IF(ISBLANK([Qmatic Wait Time (s)]), BLANK(),",
              "    CALCULATE(",
              "        AVERAGE('Qmatic - Visit Transaction'[Waiting Time])",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "    )",
              ")"
            ],
            "lineageTag": "fe1008eb-7f13-4dc5-bfee-1ac7ae5c7533"
          },
          {
            "name": "Qmatic Avg Wait Time LY (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Qmatic\\Wait Times",
            "expression": [
              "",
              "IF(ISBLANK([Qmatic Wait Time (s)]), BLANK(),",
              "    CALCULATE(",
              "        AVERAGE('Qmatic - Visit Transaction'[Waiting Time])",
              "        ,SAMEPERIODLASTYEAR('Date'[Date])",
              "    )",
              ")"
            ],
            "lineageTag": "c5bb3b2f-e01f-471f-89a9-6a14eacf916e"
          },
          {
            "name": "Snap Chat Count LM",
            "displayFolder": "SnapEngage",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(SnapEngage)",
              "    ,PREVIOUSMONTH('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "04c585b3-a989-4c23-9dbe-06142121a3e0"
          },
          {
            "name": "Snap Chat Count LY",
            "displayFolder": "SnapEngage",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(SnapEngage)",
              "    ,SAMEPERIODLASTYEAR('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "092387a3-4767-47d9-b077-946f942f4a6a"
          },
          {
            "name": "Snap Avg Chat Duration LM (m)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": "CALCULATE(Sum(SnapEngage[Chat Duration]),PREVIOUSMONTH('Date'[Date])) / [Snap Chat Count LM] / 60",
            "lineageTag": "9d778609-e5da-40c5-9b20-8bc516e6877f"
          },
          {
            "name": "Snap Avg Chat Duration LY (m)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": "CALCULATE(Sum(SnapEngage[Chat Duration]),SAMEPERIODLASTYEAR('Date'[Date])) / [Snap Chat Count LY] / 60",
            "lineageTag": "fd5a1b37-2a95-4c86-a126-65716db4d8df"
          },
          {
            "name": "Snap Avg Chat Waittime LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": "CALCULATE(AVERAGE(SnapEngage[Chat Waittime]), PREVIOUSMONTH('Date'[Date]))",
            "lineageTag": "a9ea51f8-17fa-48c0-93b1-e557da537c4d"
          },
          {
            "name": "Snap Avg Chat Waittime LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SnapEngage",
            "expression": "CALCULATE(AVERAGE(SnapEngage[Chat Waittime]), SAMEPERIODLASTYEAR('Date'[Date]))",
            "lineageTag": "d279e214-900f-46f2-b989-f8270911010e"
          },
          {
            "name": "Snap Avg Survey Score LM",
            "displayFolder": "SnapEngage",
            "expression": "CALCULATE(AVERAGE(SnapEngage[Survey Score]), PREVIOUSMONTH('Date'[Date]))",
            "formatString": "0.00",
            "lineageTag": "6b517cb7-afbe-4def-95bf-47aa9c81a82a"
          },
          {
            "name": "Snap Avg Survey Score LY",
            "displayFolder": "SnapEngage",
            "expression": "CALCULATE(AVERAGE(SnapEngage[Survey Score]), SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "0.00",
            "lineageTag": "3b5fae71-e49d-4374-8232-43d7619fda2a"
          },
          {
            "name": "Transaction Completed LM",
            "displayFolder": "Your Feedback Matters\\Completed",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"Yes\" ",
              "    , PREVIOUSMONTH('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4ef3d861-3996-45c6-8a8e-1310ed135b85"
          },
          {
            "name": "Transaction Completed LY",
            "displayFolder": "Your Feedback Matters\\Completed",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"Yes\" ",
              "    , SAMEPERIODLASTYEAR('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d20db7b9-0ad2-42b9-a56d-700ed982edf8"
          },
          {
            "name": "Positive % LM",
            "displayFolder": "Your Feedback Matters\\Positive",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(sum('YFM - Your Feedback Matters'[IsPositive]), PREVIOUSMONTH('Date'[Date]))",
              "    , (CALCULATE(sum('YFM - Your Feedback Matters'[IsPositive]), PREVIOUSMONTH('Date'[Date])) + CALCULATE(sum('YFM - Your Feedback Matters'[IsNegative]), PREVIOUSMONTH('Date'[Date])))",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "748b976c-7d2e-4e0b-9f6f-ce8ac8ddf66b"
          },
          {
            "name": "Positive % LY",
            "displayFolder": "Your Feedback Matters\\Positive",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(sum('YFM - Your Feedback Matters'[IsPositive]), SAMEPERIODLASTYEAR('Date'[Date]))",
              "    , (CALCULATE(sum('YFM - Your Feedback Matters'[IsPositive]), SAMEPERIODLASTYEAR('Date'[Date])) + CALCULATE(sum('YFM - Your Feedback Matters'[IsNegative]), SAMEPERIODLASTYEAR('Date'[Date])))",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "43463cbe-b767-4179-9156-78fac76e22a0"
          },
          {
            "name": "Transaction Incomplete LY",
            "displayFolder": "Your Feedback Matters\\Incomplete",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"No\" ",
              "    , SAMEPERIODLASTYEAR('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "11b107a3-561f-4798-bf03-64967064779c"
          },
          {
            "name": "Transaction Unanswered LM",
            "displayFolder": "Your Feedback Matters\\Unanswered",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"\" ",
              "    , PREVIOUSMONTH('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8e81a84-8ce5-4cb5-aa13-683ec328a4be"
          },
          {
            "name": "Transaction Unanswered LY",
            "displayFolder": "Your Feedback Matters\\Unanswered",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"\" ",
              "    , SAMEPERIODLASTYEAR('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "546326e0-4246-4317-85e4-cc1470ec7ab3"
          },
          {
            "name": "Has Data LM",
            "displayFolder": "Your Feedback Matters\\Has Data",
            "expression": "CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), PREVIOUSMONTH('Date'[Date]))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e92d098c-35c2-444f-b90b-0e74fc1ec801"
          },
          {
            "name": "Has Data LY",
            "displayFolder": "Your Feedback Matters\\Has Data",
            "expression": "CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "701750ef-3865-466c-8555-61220ab0840b"
          },
          {
            "name": "CSQ Avg Service Level",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "AVERAGE('Call Manager - Common Skill CSQ'[Service Level])",
            "lineageTag": "7793b74d-2ccd-4ac4-888c-71f674bcf89f"
          },
          {
            "name": "CSQ Avg Service Level LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "CALCULATE(AVERAGE('Call Manager - Common Skill CSQ'[Service Level]), PREVIOUSMONTH('Date'[Date]))",
            "lineageTag": "aaeeb9a7-3e95-45d4-b686-239a11f19d90"
          },
          {
            "name": "CSQ Avg Service Level LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Common Skill CSQ",
            "expression": "CALCULATE(AVERAGE('Call Manager - Common Skill CSQ'[Service Level]), SAMEPERIODLASTYEAR('Date'[Date]))",
            "lineageTag": "ec4e0ade-3c22-4723-bd5e-d94dd839baf5"
          },
          {
            "name": "App Avg Speed Answer LM (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "App Summary",
            "expression": "CALCULATE(AVERAGE('Call Manager - App Summary'[Avg Speed Of Answer]) * [Sec per Day], PREVIOUSMONTH('Date'[Date]))",
            "lineageTag": "16edac67-5a75-4077-a393-62fd33960cf3"
          },
          {
            "name": "App Avg Speed Answer LY (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "App Summary",
            "expression": "CALCULATE(AVERAGE('Call Manager - App Summary'[Avg Speed Of Answer]) * [Sec per Day], SAMEPERIODLASTYEAR('Date'[Date]))",
            "lineageTag": "cfb0cc88-852b-44b4-af5a-8abd16bd71ab"
          },
          {
            "name": "Agent Avg Talk LM (s)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Agent Call Summary",
            "expression": "CALCULATE(AVERAGE('Call Manager - Agent Call Summary'[Avg Talk Time]), PREVIOUSMONTH('Date'[Date])) * [Sec per Day]",
            "lineageTag": "e5a511bb-e3e0-4880-b1d2-689d6cba965c"
          },
          {
            "name": "Agent Avg Talk LY (s)",
            "displayFolder": "Agent Call Summary",
            "expression": "CALCULATE(AVERAGE('Call Manager - Agent Call Summary'[Avg Talk Time]), SAMEPERIODLASTYEAR('Date'[Date])) * [Sec per Day]",
            "formatString": "0",
            "lineageTag": "df2cd17a-e89d-4f40-8f6e-70238c4a5682"
          },
          {
            "name": "Qmatic Visit No Show",
            "displayFolder": "Qmatic\\Counts",
            "expression": "CALCULATE(COUNTROWS('Qmatic - Visit Transaction'), 'Qmatic - Visit Transaction'[Outcome Key] = 2)",
            "formatString": "0",
            "lineageTag": "7279947a-fe57-4753-9a18-fa36a3195dc4"
          },
          {
            "name": "Agent Count",
            "displayFolder": "Agent Call Summary",
            "expression": "DISTINCTCOUNT('Call Manager - Agent Call Summary'[Agent ID])",
            "formatString": "0",
            "lineageTag": "ec60afc0-e953-4888-92ff-59a0f173c38f"
          },
          {
            "name": "Drives Row Count",
            "displayFolder": "Count",
            "expression": "COUNTROWS('Drives - Time Tracking')",
            "formatString": "0",
            "lineageTag": "44a105f5-2232-4592-8b05-b9039a59d822"
          },
          {
            "name": "Drives Transaction Count FW",
            "displayFolder": "Count",
            "expression": [
              "",
              "IF(ISBLANK([Drives Transaction Count]), BLANK(),",
              "    CALCULATE(",
              "        COUNTROWS( 'Drives - Time Tracking' )",
              "        ,'Date'[Is First Week] = TRUE()",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "e5aca80d-5693-49ba-8f54-87ca6de19333"
          },
          {
            "name": "Drives Transaction Count LM FW",
            "displayFolder": "Count",
            "expression": [
              "",
              "IF(ISBLANK([Drives Transaction Count]), BLANK(),",
              "    CALCULATE(",
              "        COUNTROWS( 'Drives - Time Tracking' )",
              "        ,PREVIOUSMONTH('Date'[Date]),'Date'[Is First Week] = TRUE()",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f678047f-164b-4825-9361-b6122e095c30"
          },
          {
            "name": "Drives Transaction Count LY FW",
            "displayFolder": "Count",
            "expression": [
              "",
              "IF(ISBLANK([Drives Transaction Count]), BLANK(),",
              "    CALCULATE(",
              "        COUNTROWS( 'Drives - Time Tracking' )",
              "        ,SAMEPERIODLASTYEAR('Date'[Date]),'Date'[Is First Week] = TRUE()",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9aad217a-2c5c-4477-a47f-57327349d447"
          },
          {
            "name": "Total Response Count",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "COUNTROWS('YFM - Your Feedback Matters')",
            "formatString": "0",
            "lineageTag": "7b99cffb-a25b-43fd-9b8f-98ea4b72c02c"
          },
          {
            "name": "Total Response Count All",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "IF([Total Response Count] = BLANK(), BLANK(),CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), ALL('Date')))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e3c096b1-9ca2-4382-8420-48d1d5d78a05"
          },
          {
            "name": "Total Response Count LP",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Response Count], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Response Count],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([Total Response Count], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Total Response Count], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Total Response Count], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Total Response Count], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Total Response Count], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Total Response Count], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Total Response Count], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f7e7ed48-790f-4f95-a316-f1c9ad8a02b9"
          },
          {
            "name": "Total Response Count LY",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Response Count], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Response Count],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Total Response Count], PARALLELPERIOD('Date'[Date], -4, QUARTER)),",
              "    CALCULATE([Total Response Count], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "a1661f06-060a-460f-b02a-7c2cdd1695b9"
          },
          {
            "name": "Total Response Count LP Var",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "[Total Response Count] - [Total Response Count LP]",
            "formatString": "0",
            "lineageTag": "8d606006-e48d-4fbe-819c-9217dd690bf5"
          },
          {
            "name": "Total Response Count All Var",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "[Total Response Count All] - [Total Response Count]",
            "formatString": "0",
            "lineageTag": "438af632-fb72-40d1-88e6-a53271875461"
          },
          {
            "name": "Total Response Count All Var %",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "[Total Response Count] / [Total Response Count All]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d74af7f7-b82c-4e38-bdca-74bfb0b89e55"
          },
          {
            "name": "Total Response Count LP Var %",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "([Total Response Count] - [Total Response Count LP]) / [Total Response Count LP]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8b523395-b3ed-4835-b17c-6c3b99c23341"
          },
          {
            "name": "Total Response Count LY Var",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "[Total Response Count] - [Total Response Count LY]",
            "formatString": "0",
            "lineageTag": "e6e0a8b4-ffe9-4d91-b2e0-20223472a4a2"
          },
          {
            "name": "Total Response Count LY Var %",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "([Total Response Count] - [Total Response Count LY])/ [Total Response Count LY]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f22e1b58-5a76-47c6-9b84-14c5c7f863b3"
          },
          {
            "name": "Total Response Count FW",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,'Date'[Is First Week] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8a069ee-75ac-44c2-8602-2bdb49d2dfdf"
          },
          {
            "name": "Total Response Count FW LM",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "        ,'Date'[Is First Week] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8e856d75-70a0-433f-b0ed-fc37661b2205"
          },
          {
            "name": "Total Response Count LW",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,'Date'[Is Last Week] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ccd0f938-ce3a-4e9a-b51b-0c750dd2845d"
          },
          {
            "name": "Total Response Count LW LM",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "        ,'Date'[Is Last Week] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5f3394f2-0097-4b1c-bd42-19b1b3f791ad"
          },
          {
            "name": "Total Response Count LW LY",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,SAMEPERIODLASTYEAR('Date'[Date])",
              "        ,'Date'[Is Last Week] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "03b5a0f5-f7a3-498e-af41-d6b01f1dfa5a"
          },
          {
            "name": "Total Response Count MW",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,'Date'[Is Middle Month] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "532c438b-dfa4-45fd-ad40-869381675fdb"
          },
          {
            "name": "Total Response Count MW LM",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,PREVIOUSMONTH('Date'[Date])",
              "        ,'Date'[Is Middle Month] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e7f0a1f2-5fb0-40ed-87ff-2261d69302c3"
          },
          {
            "name": "Total Response Count MW LY",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": [
              "",
              "    CALCULATE(",
              "        COUNTROWS( 'YFM - Your Feedback Matters' )",
              "        ,SAMEPERIODLASTYEAR('Date'[Date])",
              "        ,'Date'[Is Middle Month] = TRUE()",
              "    )",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a01d1ee3-d3e7-4101-94c9-ec67d8c7aa44"
          },
          {
            "name": "Total Days",
            "displayFolder": "Date",
            "expression": "count('Date'[DateKey])",
            "formatString": "0",
            "lineageTag": "7b977a61-3b01-43d8-a7b1-4a5f5eedfa2b"
          },
          {
            "name": "Current Year",
            "displayFolder": "Date",
            "expression": "FORMAT(Today(),\"YYYY\")",
            "lineageTag": "b5a0fe64-22c1-4e09-ad32-7dc8363d7074"
          },
          {
            "name": "Total Week Days",
            "displayFolder": "Date",
            "expression": "CALCULATE(count('Date'[DateKey]), 'Date'[Is Week Day] = TRUE())",
            "formatString": "0",
            "lineageTag": "6c186baa-6e23-4f39-8af7-b586c7cc279a"
          },
          {
            "name": "Total Manager Audits",
            "displayFolder": "Agent Call Summary",
            "expression": [
              "",
              "SUM('Audit and UAT Stats'[Manager Audits - # Overturned State Rejects])",
              "+ SUM('Audit and UAT Stats'[Manager Audits - # State Reject Reviews Submitted ])",
              "+ SUM('Audit and UAT Stats'[Manager Audits - Approved])",
              "+ SUM('Audit and UAT Stats'[Manager Audits - Corrected])",
              "+ SUM('Audit and UAT Stats'[Manager Audits - Rejected])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "51290ff4-fd75-43f1-b585-55ecd9d70380"
          },
          {
            "name": "Uploaded to Azure",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "SUM('Audit and UAT Stats'[DRIVES Reports - # Uploaded to Azure])",
            "formatString": "0",
            "lineageTag": "12209382-7ecb-46d6-85cf-bd545a1b6665"
          },
          {
            "name": "Mail Received - Renewals",
            "displayFolder": "Staff Stats\\Renewals",
            "expression": "SUM('Staff Stats - Physical Mail'[Renewals-Rec])",
            "formatString": "#,##0",
            "lineageTag": "bf9027c7-c49a-46f7-a77e-a5a5e09c9df0"
          },
          {
            "name": "Mail Processed - Renewals",
            "displayFolder": "Staff Stats\\Renewals",
            "expression": "SUM( 'Staff Stats - Physical Mail'[Renewals-Pro] )",
            "formatString": "#,##0",
            "lineageTag": "47ce8d11-78b2-4bf5-a050-5188523578a5"
          },
          {
            "name": "Mail Rejected % - Renewals",
            "displayFolder": "Staff Stats\\Renewals",
            "expression": "[Mail Rejected - Renewals] / ([Mail Processed - Renewals] + [Mail Sent Out - Renewals])",
            "formatString": "#,##0.00 %",
            "lineageTag": "3b2ed1e3-c1aa-4d34-bf78-2cea3c77c1f8"
          },
          {
            "name": "Total Response Count FW LM Var",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "[Total Response Count FW] - [Total Response Count FW LM]",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3855e9a3-9347-4a0c-9c83-a61f42413cad"
          },
          {
            "name": "Total Response Count FW LM Var %",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "([Total Response Count FW] - [Total Response Count FW LM]) / [Total Response Count FW LM]",
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "lineageTag": "1c650142-0c20-4db8-997a-970a045e1594"
          },
          {
            "name": "isFLMScope",
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "ISINSCOPE('Date'[FML Week of Year])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "b2d25507-d63e-402a-9abd-f7ab96262745"
          },
          {
            "name": "HASONEFILTER Date",
            "displayFolder": "Date",
            "expression": [
              "",
              "    HASONEFILTER('Date'[Date])",
              ""
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "bc5d10d6-dcb5-4d19-8d08-f7415d895981"
          },
          {
            "name": "HASONEFILTER FML Week of Year",
            "displayFolder": "Date",
            "expression": [
              "",
              "    HASONEFILTER('Date'[FML Week of Year])",
              ""
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d4f5f9ac-b86b-4a79-8c2e-6c91a0710412"
          },
          {
            "name": "HASONEFILTER Month of Year",
            "displayFolder": "Date",
            "expression": [
              "",
              "    HASONEFILTER('Date'[Month of Year])"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "64ed9a1a-85ce-4152-bb96-5e428fc26a9d"
          },
          {
            "name": "HASONEFILTER Year",
            "displayFolder": "Date",
            "expression": [
              "",
              "    HASONEFILTER('Date'[Year])"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6bc50b7c-f294-4440-8447-43c0d71b3bf7"
          },
          {
            "name": "HASONEFILTER Week of Year",
            "displayFolder": "Date",
            "expression": [
              "",
              "    HASONEFILTER('Date'[Week of Year])"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cd9e7c99-93ad-46b2-9879-4a7ec8bf9069"
          },
          {
            "name": "Avg Daily Response Count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Your Feedback Matters\\Avg Response Count",
            "expression": [
              "",
              "IF([Total Response Count] = BLANK()",
              "    ,BLANK()",
              "    ,[Total Response Count TD] / [No Of Days TD]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fb6c9f8e-ad00-4586-b606-09fedb3efcf1"
          },
          {
            "name": "Total Response Count TD",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Your Feedback Matters\\Avg Response Count",
            "expression": [
              "CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), DATESYTD('Date'[Date]))",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8702c27d-24e7-4915-8531-844a2e4e6e9c"
          },
          {
            "name": "Transaction Incomplete LM",
            "displayFolder": "Your Feedback Matters\\Incomplete",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA('YFM - Your Feedback Matters'[TransactionCompleted]), 'YFM - Your Feedback Matters'[TransactionCompleted] = \"No\" ",
              "    , PREVIOUSMONTH('Date'[Date])",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5e6c4011-f3bb-4c16-a317-1a117f6bc2a3"
          },
          {
            "name": "Mail Received - Business",
            "displayFolder": "Staff Stats\\Business",
            "expression": [
              "SUM('Staff Stats - Physical Mail'[Enterprise-Rec])",
              "+ SUM('Staff Stats - Physical Mail'[Business-Renewal-Rec])",
              "+ SUM('Staff Stats - Physical Mail'[Business-MM-Rec])",
              "+ SUM('Staff Stats - Physical Mail'[Business-Communications-Rec])",
              "+ SUM('Staff Stats - Physical Mail'[Dealer-Renewal-Rec])",
              "+ SUM('Staff Stats - Physical Mail'[Dealer-MM-Rec])"
            ],
            "formatString": "#,##0",
            "lineageTag": "d4836bf8-9c87-4cb7-a563-8c1b52bd759b"
          },
          {
            "name": "Mail Rejected - Business",
            "displayFolder": "Staff Stats\\Business",
            "expression": [
              "SUM('Staff Stats - Physical Mail'[Enterprise-Rej])",
              "+ SUM('Staff Stats - Physical Mail'[Business-Renewal-Rej])",
              "+ SUM('Staff Stats - Physical Mail'[Business-MM-Rej])",
              "+ SUM('Staff Stats - Physical Mail'[Business-Communications-Rej])",
              "+ SUM('Staff Stats - Physical Mail'[Dealer-Renewal-Rej])",
              "+ SUM('Staff Stats - Physical Mail'[Dealer-MM-Rej])"
            ],
            "formatString": "#,##0",
            "lineageTag": "52e652e6-d596-4c2a-9818-ec3c7f712ac9"
          },
          {
            "name": "Mail Rejected % - Business",
            "displayFolder": "Staff Stats\\Business",
            "expression": "[Mail Rejected - Business] / [Mail Processed - Business] ",
            "formatString": "#,##0.00 %",
            "lineageTag": "9c943a41-213d-400d-8e92-4d8b8a663ebb"
          },
          {
            "name": "Mail Rejected - Renewals",
            "displayFolder": "Staff Stats\\Renewals",
            "expression": [
              "SUM( 'Staff Stats - Physical Mail'[Renewals-Rej] )",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "c6029d04-b5a0-44bc-8ea8-c6a446fc0643"
          },
          {
            "name": "Mail Sent Out - Renewals",
            "displayFolder": "Staff Stats\\Renewals",
            "expression": "SUM( 'Staff Stats - Physical Mail'[Renewals-SO] )",
            "formatString": "#,##0",
            "lineageTag": "6594126f-52ef-44fc-b58a-bc22864e8618"
          },
          {
            "name": "Mail Processed - MM",
            "displayFolder": "Staff Stats\\MM",
            "expression": "SUM('Staff Stats - Physical Mail'[Mortgage Mail-Pro])",
            "formatString": "#,##0",
            "lineageTag": "426a0314-7b0c-404c-803b-861ec56030ca"
          },
          {
            "name": "Mail Received - MM",
            "displayFolder": "Staff Stats\\MM",
            "expression": "SUM('Staff Stats - Physical Mail'[Mortgage Mail-Rec])",
            "formatString": "#,##0",
            "lineageTag": "627da6f1-162e-4222-8eee-fe3318508217"
          },
          {
            "name": "Mail Rejected - MM",
            "displayFolder": "Staff Stats\\MM",
            "expression": "SUM('Staff Stats - Physical Mail'[Mortgage Mail-Rej])",
            "formatString": "#,##0",
            "lineageTag": "8c0bacb4-d472-47cd-85b8-d31c50e5800c"
          },
          {
            "name": "Mail Sent Out - MM",
            "displayFolder": "Staff Stats\\MM",
            "expression": "SUM('Staff Stats - Physical Mail'[Mortgage Mail-SO])",
            "formatString": "#,##0",
            "lineageTag": "807f2841-8e5c-411d-b759-91380bb97bf3"
          },
          {
            "name": "Mail Rejected % - MM",
            "displayFolder": "Staff Stats\\MM",
            "expression": "[Mail Rejected - MM] / ([Mail Processed - MM] + [Mail Sent Out - MM])",
            "formatString": "#,##0.00 %",
            "lineageTag": "a1c2e1f1-4d36-4205-b324-84f42c5b6835"
          },
          {
            "name": "Mail Processed - Salvages",
            "displayFolder": "Staff Stats\\Salvages",
            "expression": "SUM('Staff Stats - Physical Mail'[Salvages-Pro])",
            "formatString": "#,##0",
            "lineageTag": "5cb2b5a4-8db6-4718-86d7-441af9d1b3ac"
          },
          {
            "name": "Mail Received - Salvages",
            "displayFolder": "Staff Stats\\Salvages",
            "expression": "SUM('Staff Stats - Physical Mail'[Salvages-Rec])",
            "formatString": "#,##0",
            "lineageTag": "84dd9b48-4a93-4acc-be60-2e35bfbcf449"
          },
          {
            "name": "Mail Rejected - Salvages",
            "displayFolder": "Staff Stats\\Salvages",
            "expression": "SUM('Staff Stats - Physical Mail'[Salvages-Rej])",
            "formatString": "#,##0",
            "lineageTag": "c7c0b30a-3def-432e-87d7-96b1ae628293"
          },
          {
            "name": "Mail Rejected % - Salvages",
            "displayFolder": "Staff Stats\\Salvages",
            "expression": "[Mail Rejected - Salvages] / ([Mail Processed - Salvages] + [Mail Sent Out - Salvages])",
            "formatString": "#,##0.00 %",
            "lineageTag": "8a87865a-2502-4766-8651-b8bde658a59c"
          },
          {
            "name": "Mail Sent Out - Salvages",
            "displayFolder": "Staff Stats\\Salvages",
            "expression": "SUM('Staff Stats - Physical Mail'[Salvages-SO])",
            "formatString": "#,##0",
            "lineageTag": "b8892d89-294e-476e-ad7c-ea77e3c334d5"
          },
          {
            "name": "Total Mail - Received",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Mail Received - Business] + [Mail Received - Renewals] + [Mail Received - MM] + [Mail Received - Salvages]",
            "formatString": "#,##0",
            "lineageTag": "5169d3d9-795b-405e-9761-0ac51706db08"
          },
          {
            "name": "Total Mail - Rejected",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Mail Rejected - Business] + [Mail Rejected - Renewals] + [Mail Rejected - MM] + [Mail Rejected - Salvages]",
            "formatString": "#,##0",
            "lineageTag": "3abf0469-6fc8-4f5a-bbf4-b338ab6dc688"
          },
          {
            "name": "Total Mail - Sent Out",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Mail Sent Out - Renewals] + [Mail Sent Out - MM] + [Mail Sent Out - Salvages]",
            "formatString": "#,##0",
            "lineageTag": "780e5e28-6407-4e9a-997f-d798107b9515"
          },
          {
            "name": "Total Mail - Rejected %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Rejected] / ([Total Mail - Processed] + [Total Mail - Sent Out])",
            "formatString": "#,##0.00 %",
            "lineageTag": "586fc1dc-0577-4dea-8f81-50ee248606ff"
          },
          {
            "name": "Total Mail",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Business] + [Total MM] + [Total Renewals] + [Total Salvages]",
            "formatString": "#,##0",
            "lineageTag": "124bc23a-cb91-42ab-a98e-362c4d3d8a87"
          },
          {
            "name": "Total Business",
            "displayFolder": "Staff Stats\\Business",
            "expression": "[Mail Received - Business] + [Mail Processed - Business] + [Mail Rejected - Business]",
            "formatString": "#,##0",
            "lineageTag": "6e6b07f6-780d-48d3-bdd0-fc8554028f7c"
          },
          {
            "name": "Total MM",
            "displayFolder": "Staff Stats\\MM",
            "expression": [
              "[Mail Received - MM] + [Mail Processed - MM] + [Mail Rejected - MM] + [Mail Sent Out - MM]",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "767d320b-93de-4536-a4ae-36d5540099c5"
          },
          {
            "name": "Total Renewals",
            "displayFolder": "Staff Stats\\Renewals",
            "expression": "[Mail Received - Renewals] + [Mail Processed - Renewals] + [Mail Rejected - Renewals] + [Mail Sent Out - Renewals]",
            "formatString": "#,##0",
            "lineageTag": "e2f13bb9-1372-40c0-b39f-cf3445e4eac1"
          },
          {
            "name": "Total Salvages",
            "displayFolder": "Staff Stats\\Salvages",
            "expression": "[Mail Received - Salvages] + [Mail Processed - Salvages] + [Mail Rejected - Salvages] + [Mail Sent Out - Salvages]",
            "formatString": "#,##0",
            "lineageTag": "e8f19ccd-a327-4109-a48a-0db1b6fcf8cf"
          },
          {
            "name": "Avg Total Response Count",
            "displayFolder": "Your Feedback Matters\\Avg Response Count",
            "expression": [
              "",
              "IF([Total Response Count] = BLANK()",
              "    ,BLANK()",
              "    ,[Total Response Count All] / [All Time No Of Periods]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5290996e-4c14-41a6-80b6-1d8f8f4e0e43"
          },
          {
            "name": "All Time Work Days to Date",
            "displayFolder": "Date",
            "expression": [
              "",
              "CALCULATE(",
              "    count('Date'[DateKey]), ",
              "    FILTER(",
              "        ALL('Date')",
              "        ,'Date'[Is Work Day] = TRUE()",
              "        && 'Date'[Date] <= MAX('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1130360a-4fea-4e14-a6b7-40dde00cc05b"
          },
          {
            "name": "All Time Days to Date",
            "displayFolder": "Date",
            "expression": [
              "",
              "CALCULATE(",
              "    count('Date'[DateKey]), ",
              "    FILTER(",
              "        ALL('Date')",
              "        ,'Date'[Date] <= MAX('Date'[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "4bb9d7a9-aa81-4f32-853a-eff04562eb39"
          },
          {
            "name": "Total Day Count All",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "CALCULATE(DISTINCTCOUNT('YFM - Your Feedback Matters'[FeedbackDate]), ALL())",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e9ce075b-f820-4a0f-842d-eb53249261b8"
          },
          {
            "name": "Total Month Count All",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Your Feedback Matters\\Total Response Count",
            "expression": "IF([Total Response Count] = BLANK(), BLANK(),CALCULATE(DISTINCTCOUNT('YFM - Your Feedback Matters'[YrMth]), ALL('YFM - Your Feedback Matters')))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e621a2ae-08d8-49ce-98e9-7bab099fedff"
          },
          {
            "name": "All Time No Of Periods",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Your Feedback Matters\\Avg Response Count",
            "expression": [
              "",
              "VAR NoOfPeriods = ",
              "//CALCULATE(COUNTROWS('Date'), DATESBETWEEN('Date'[Date],  date(MAX('Date'[Year]),1,1), MAX('Date'[Date])), 'Date'[Is Work Day] = TRUE())",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), ",
              "        CALCULATE(",
              "            COUNT('Date'[Date]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    HASONEFILTER('Date'[FML Week of Year]), ",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Date'[FML Week of Year]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    HASONEFILTER('Date'[Week of Year]), ",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Date'[Week of Year]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    HASONEFILTER('Date'[Week No]), ",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Date'[Week No]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    HASONEFILTER('Date'[Month of Year]), ",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Date'[Month of Year]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    HASONEFILTER('Date'[Month]),         ",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Date'[Month of Year]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    HASONEFILTER('Date'[Quarter of Year]),         ",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Date'[Quarter of Year]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    HASONEFILTER('Date'[Year]), ",
              "        CALCULATE(",
              "            DISTINCTCOUNT('Date'[Year]),",
              "            FILTER(",
              "                ALL('Date'),",
              "                CALCULATE(COUNTROWS('YFM - Your Feedback Matters')) > 0",
              "            )",
              "        ),",
              "    BLANK()",
              ")",
              "",
              "RETURN",
              "IF([Total Response Count] = BLANK(), BLANK(), NoOfPeriods)",
              ""
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1abcdebf-fb9d-4aef-82e1-4d0745a9fec6"
          },
          {
            "name": "No Of Days TD",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Your Feedback Matters\\Avg Response Count",
            "expression": "CALCULATE(DISTINCTCOUNT('YFM - Your Feedback Matters'[FeedbackDate]), DATESYTD('Date'[Date]))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "753b0923-b5e3-4508-82c0-4ccfbea020f8"
          },
          {
            "name": "Total Response Count Avg Var",
            "displayFolder": "Your Feedback Matters\\Avg Response Count",
            "expression": "[Total Response Count] - [Avg Total Response Count]",
            "formatString": "0",
            "lineageTag": "223c3341-a421-46d6-9a74-931aff341621"
          },
          {
            "name": "Total Response Count Avg Var %",
            "displayFolder": "Your Feedback Matters\\Avg Response Count",
            "expression": "([Total Response Count] - [Avg Total Response Count]) / [Avg Total Response Count]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "baeabeb5-4b5a-433c-b978-4aee610872ab"
          },
          {
            "name": "Salvage Rejects Count",
            "displayFolder": "Staff Stats\\Salvage Rejects",
            "expression": "COUNTROWS('Staff Stats - Salvage Rejects')",
            "formatString": "#,##0",
            "lineageTag": "36b7285a-bc06-406a-adb9-c94e197f74b2"
          },
          {
            "name": "Mail Rejects Count",
            "displayFolder": "Staff Stats\\Mail Rejects",
            "expression": "COUNTROWS('Staff Stats - Mail Rejects')",
            "formatString": "#,##0",
            "lineageTag": "faaa4ff4-db60-425c-8ff8-7fb841cab139"
          },
          {
            "name": "Business Mail %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Business] / [Total Mail]",
            "formatString": "#,##0.00 %",
            "lineageTag": "d7ee9280-8afd-4e23-a5fc-ab94e688fca2"
          },
          {
            "name": "Mortgage Mail %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total MM] / [Total Mail]",
            "formatString": "#,##0.00 %",
            "lineageTag": "41e6c8d3-a5e4-4c83-8b99-3fa83f1cfc64"
          },
          {
            "name": "Salvage Mail %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Salvages] / [Total Mail]",
            "formatString": "#,##0.00 %",
            "lineageTag": "f3263b98-a38c-4425-bd92-712955d96d3f"
          },
          {
            "name": "Renewal Mail %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Renewals] / [Total Mail]",
            "formatString": "#,##0.00 %",
            "lineageTag": "34193e4d-fcf0-41bd-a25c-4c903e628608"
          },
          {
            "name": "Total Mail - Processed LP",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Processed], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Processed],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER( 'Date'[Week Year] ), CALCULATE([Total Mail - Processed], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Total Mail - Processed], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Total Mail - Processed], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Total Mail - Processed], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Total Mail - Processed], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Total Mail - Processed], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Total Mail - Processed], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "58fa45fd-86a0-4a05-bf5d-5511669795a0"
          },
          {
            "name": "Total Mail - Processed LP Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Processed] - [Total Mail - Processed LP]",
            "formatString": "#,##0",
            "lineageTag": "65883342-e174-4890-a939-2562f61c21ad"
          },
          {
            "name": "Total Mail - Processed LP Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Processed] - [Total Mail - Processed LP]) / [Total Mail - Processed LP]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "9501152d-b64d-429b-b03c-8cdeada923ee"
          },
          {
            "name": "Total Mail - Processed LY",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Processed], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Processed],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Total Mail - Processed], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "446839c2-105a-4798-8283-c64c18c88145"
          },
          {
            "name": "Total Mail - Processed LY Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Processed] - [Total Mail - Processed LY]) / [Total Mail - Processed LY]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "1f07434b-4a19-4711-8dc9-11586b1eea95"
          },
          {
            "name": "Total Mail - Received LP",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Received], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Received],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER( 'Date'[Week Year] ), CALCULATE([Total Mail - Received], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Total Mail - Received], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Total Mail - Received], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Total Mail - Received], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Total Mail - Received], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Total Mail - Received], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "   HASONEFILTER('Date'[Year]), CALCULATE([Total Mail - Received], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "90e8ce58-9862-40a9-925d-37f0ac85458b"
          },
          {
            "name": "Total Mail - Received LP Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Received] - [Total Mail - Received LP]",
            "formatString": "#,##0",
            "lineageTag": "dbb8c22d-bd9f-4c26-8ea4-e3b007fd6ac7"
          },
          {
            "name": "Total Mail - Received LP Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Received] - [Total Mail - Received LP]) / [Total Mail - Received LP]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "5260cf05-b5e9-44f5-b775-1e45a5ffc482"
          },
          {
            "name": "Total Mail - Received LY",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Received], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Received],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Total Mail - Received], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "57a6d360-c573-46f8-8835-447b5c0ccff0"
          },
          {
            "name": "Total Mail - Received LY Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Received] - [Total Mail - Received LY]) / [Total Mail - Received LY]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "807ab3a9-8b3b-4efa-833b-4ca5a489ca43"
          },
          {
            "name": "Total Mail - Rejected LP",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Rejected], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Rejected],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER( 'Date'[Week Year] ), CALCULATE([Total Mail - Rejected], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Total Mail - Rejected], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Total Mail - Rejected], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Total Mail - Rejected], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Total Mail - Rejected], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Total Mail - Rejected], PARALLELPERIOD('Date'[Date], -3, MONTH)),    ",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Total Mail - Rejected], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "0dd82a42-0380-40dc-8287-528d5ffddc00"
          },
          {
            "name": "Total Mail - Rejected LP Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Rejected] - [Total Mail - Rejected LP]",
            "formatString": "#,##0",
            "lineageTag": "50679a21-3033-4937-b21e-b7b6ddffd920"
          },
          {
            "name": "Total Mail - Rejected LP Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Rejected] - [Total Mail - Rejected LP]) / [Total Mail - Rejected LP]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "eab7e5a8-2537-4567-bc2a-2732f1160769"
          },
          {
            "name": "Total Mail - Rejected LY",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Rejected], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Rejected],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Total Mail - Rejected], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "25663960-ac91-4187-9942-cbe9bafeef8f"
          },
          {
            "name": "Total Mail - Rejected LY Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Rejected] - [Total Mail - Rejected LY]) / [Total Mail - Rejected LY]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "24360014-7f1b-4fdf-86de-c27ed07298d8"
          },
          {
            "name": "Total Mail - Sent Out LP",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Sent Out], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Sent Out],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER( 'Date'[Week Year] ), CALCULATE([Total Mail - Sent Out], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Total Mail - Sent Out], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Total Mail - Sent Out], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Total Mail - Sent Out], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Total Mail - Sent Out], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Total Mail - Sent Out], PARALLELPERIOD('Date'[Date], -3, MONTH)),    ",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Total Mail - Sent Out], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "31045f01-09e9-4fe8-a169-725b97109373"
          },
          {
            "name": "Total Mail - Sent Out LP Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Sent Out] - [Total Mail - Sent Out LP]",
            "formatString": "#,##0",
            "lineageTag": "8f263ccb-710d-4ddf-a8d7-3938ff3e0899"
          },
          {
            "name": "Total Mail - Sent Out LP Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Sent Out] - [Total Mail - Sent Out LP]) / [Total Mail - Sent Out LP]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "bd20a5c0-32ba-4478-9cab-82afde675865"
          },
          {
            "name": "Total Mail - Sent Out LY",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Total Mail - Sent Out], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Total Mail - Sent Out],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Total Mail - Sent Out], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "#,##0",
            "lineageTag": "f664f977-4898-44ce-9059-f22db8ed36a2"
          },
          {
            "name": "Total Mail - Sent Out LY Var %",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": [
              "([Total Mail - Sent Out] - [Total Mail - Sent Out LY]) / [Total Mail - Sent Out LY]",
              ""
            ],
            "formatString": "#,##0.00 %",
            "lineageTag": "327ba6b5-257d-41c3-b0e2-f9d3396e6073"
          },
          {
            "name": "Total Mail - Processed LY Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Processed] - [Total Mail - Processed LY]",
            "formatString": "#,##0",
            "lineageTag": "d0d9418d-a1eb-47aa-8c20-e70eae8e47d2"
          },
          {
            "name": "Total Mail - Received LY Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Received] - [Total Mail - Received LY]",
            "formatString": "#,##0",
            "lineageTag": "072724ff-9c6e-4eef-89ac-57ba4155a862"
          },
          {
            "name": "Total Mail - Rejected LY Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Rejected] - [Total Mail - Rejected LY]",
            "formatString": "#,##0",
            "lineageTag": "1e92ebf8-81fa-4821-b1a4-ed78857d05dd"
          },
          {
            "name": "Total Mail - Sent Out LY Var",
            "displayFolder": "Staff Stats\\Total Mail",
            "expression": "[Total Mail - Sent Out] - [Total Mail - Sent Out LY]",
            "formatString": "#,##0",
            "lineageTag": "b7da0b2f-123b-4f8c-a28f-0f691eee6925"
          },
          {
            "name": "Time on Reports (Min)",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "SUM('Audit and UAT Stats'[DRIVES Reports - Time on Reports (Min)])",
            "formatString": "0",
            "lineageTag": "6107a327-f41a-41f5-904e-607c1108ed6d"
          },
          {
            "name": "Overturned State Rejects",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "SUM('Audit and UAT Stats'[Manager Audits - # Overturned State Rejects])",
            "formatString": "0",
            "lineageTag": "02490649-9184-4c39-823b-8db11a2aa1b8"
          },
          {
            "name": "State Reject Reviews Submitted",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "SUM('Audit and UAT Stats'[Manager Audits - # State Reject Reviews Submitted ])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ef4c7fd2-0e58-4034-b64b-3fe774943fa4"
          },
          {
            "name": "Manager Audits - Approved",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "SUM('Audit and UAT Stats'[Manager Audits - Approved])",
            "formatString": "0",
            "lineageTag": "fe8b0167-6912-40b8-84e3-d7909159c9c0"
          },
          {
            "name": "Manager Audits - Corrected",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "SUM('Audit and UAT Stats'[Manager Audits - Corrected])",
            "formatString": "0",
            "lineageTag": "fe828e91-c1cc-45f7-8b22-c2393a17c1c2"
          },
          {
            "name": "Manager Audits - Rejected",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "SUM('Audit and UAT Stats'[Manager Audits - Rejected])",
            "formatString": "0",
            "lineageTag": "efa1023c-e9aa-4ada-9706-6ce2e762fe2a"
          },
          {
            "name": "Manager Audits - Total",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[Manager Audits - Approved] + [Manager Audits - Corrected] + [Manager Audits - Rejected]",
            "formatString": "0",
            "lineageTag": "81ee04f9-6f91-4942-9ead-9099bf08fec2"
          },
          {
            "name": "# of SQR Scenerios",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "SUM('Audit and UAT Stats'[User Acceptence Testing (SQR) -  # of SQR Scenerios])",
            "formatString": "0",
            "lineageTag": "8ccce812-29c4-44e0-a5d4-ccfb38e21e04"
          },
          {
            "name": "# New SQRs started",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "SUM('Audit and UAT Stats'[User Acceptence Testing (SQR) - # New SQRs started])",
            "formatString": "0",
            "lineageTag": "c00a2be1-13eb-4a88-8541-54757c7edc21"
          },
          {
            "name": "Time on UAT (Min)",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "SUM('Audit and UAT Stats'[User Acceptence Testing (SQR) - Time on UAT (Min)])",
            "formatString": "0",
            "lineageTag": "1f29ef38-9abc-4577-baee-82c0e4f57dda"
          },
          {
            "name": "# New SQRs started LP",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([# New SQRs started], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([# New SQRs started],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([# New SQRs started], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([# New SQRs started], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([# New SQRs started], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([# New SQRs started], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([# New SQRs started], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([# New SQRs started], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([# New SQRs started], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bc72e36d-ed72-4023-bb8f-4a0c6d1c2056"
          },
          {
            "name": "# New SQRs started LP Var",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "[# New SQRs started] - [# New SQRs started LP]",
            "formatString": "0",
            "lineageTag": "e4194db2-6702-484f-821e-1b14b63d3f2b"
          },
          {
            "name": "# New SQRs started LP Var %",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "([# New SQRs started] - [# New SQRs started LP]) / [# New SQRs started LP]",
            "formatString": "0.00 %",
            "lineageTag": "0f889c93-8216-471e-8980-185c0c47a240"
          },
          {
            "name": "# New SQRs started LY",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([# New SQRs started], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([# New SQRs started],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([# New SQRs started], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "4a85cc68-7d76-4d12-8c64-33da6d342270"
          },
          {
            "name": "# New SQRs started LY Var",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "[# New SQRs started] - [# New SQRs started LY]",
            "formatString": "0",
            "lineageTag": "719378b6-9a51-429f-a706-79d056755eff"
          },
          {
            "name": "# New SQRs started LY Var %",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "([# New SQRs started] - [# New SQRs started LY])/ [# New SQRs started LY]",
            "formatString": "0.00 %",
            "lineageTag": "6d0702c8-136d-47bb-a90f-04af6d771c8b"
          },
          {
            "name": "# of SQR Scenerios LY Var %",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "([# of SQR Scenerios] - [# of SQR Scenerios LY])/ [# of SQR Scenerios LY]",
            "formatString": "0.00 %",
            "lineageTag": "fd4c1b18-9daf-481e-9e3b-b57c84bc30e1"
          },
          {
            "name": "# of SQR Scenerios LY Var",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "[# of SQR Scenerios] - [# of SQR Scenerios LY]",
            "formatString": "0",
            "lineageTag": "c82f8f95-119c-41e7-acfb-53cabe084e51"
          },
          {
            "name": "# of SQR Scenerios LY",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([# of SQR Scenerios], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([# of SQR Scenerios],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([# of SQR Scenerios], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "807e68c6-3edd-4be8-b40c-e2e15185be1d"
          },
          {
            "name": "# of SQR Scenerios LP Var %",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "([# of SQR Scenerios] - [# of SQR Scenerios LP]) / [# of SQR Scenerios LP]",
            "formatString": "0.00 %",
            "lineageTag": "4d254049-85dd-4033-b80b-00c77d784f18"
          },
          {
            "name": "# of SQR Scenerios LP Var",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "[# of SQR Scenerios] - [# of SQR Scenerios LP]",
            "formatString": "0",
            "lineageTag": "fc024f6f-64b7-43b6-9705-d5f2f9a994d5"
          },
          {
            "name": "# of SQR Scenerios LP",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([# of SQR Scenerios], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([# of SQR Scenerios],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([# of SQR Scenerios], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([# of SQR Scenerios], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([# of SQR Scenerios], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([# of SQR Scenerios], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([# of SQR Scenerios], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([# of SQR Scenerios], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([# of SQR Scenerios], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a2015e09-04a0-477a-b762-34d45d9567de"
          },
          {
            "name": "Uploaded to Azure LP",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Uploaded to Azure], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Uploaded to Azure],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([Uploaded to Azure], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Uploaded to Azure], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Uploaded to Azure], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Uploaded to Azure], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Uploaded to Azure], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Uploaded to Azure], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Uploaded to Azure], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "66f3dc81-a41d-47e6-a87d-1f618c288761"
          },
          {
            "name": "Uploaded to Azure LP Var",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "[Uploaded to Azure] - [Uploaded to Azure LP]",
            "formatString": "0",
            "lineageTag": "26120cde-7a55-49e3-afb7-2754c5a2b00d"
          },
          {
            "name": "Uploaded to Azure LP Var %",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "([Uploaded to Azure] - [Uploaded to Azure LP]) / [Uploaded to Azure LP]",
            "formatString": "0.00 %",
            "lineageTag": "24ecf846-e3a4-40fc-b036-a6e9ef6ffe77"
          },
          {
            "name": "Uploaded to Azure LY",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Uploaded to Azure], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Uploaded to Azure],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Uploaded to Azure], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "d77cf57d-7221-4ec3-9db2-39846522e58d"
          },
          {
            "name": "Uploaded to Azure LY Var",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "[Uploaded to Azure] - [Uploaded to Azure LY]",
            "formatString": "0",
            "lineageTag": "2a9ab2f1-de25-4612-90b4-6ac0428f83e5"
          },
          {
            "name": "Uploaded to Azure LY Var %",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "([Uploaded to Azure] - [Uploaded to Azure LY])/ [Uploaded to Azure LY]",
            "formatString": "0.00 %",
            "lineageTag": "776ae8a2-a125-45a2-bad1-2f5d46fea639"
          },
          {
            "name": "Time on Reports (Min) LY Var %",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "([Time on Reports (Min)] - [Time on Reports (Min) LY])/ [Time on Reports (Min) LY]",
            "formatString": "0.00 %",
            "lineageTag": "e10b4c73-a6f5-4973-997d-1ec6a60a149a"
          },
          {
            "name": "Time on Reports (Min) LY Var",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "[Time on Reports (Min)] - [Time on Reports (Min) LY]",
            "formatString": "0",
            "lineageTag": "6586b2c0-eec4-4de6-be9c-53daa2611f14"
          },
          {
            "name": "Time on Reports (Min) LY",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Time on Reports (Min)], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Time on Reports (Min)],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Time on Reports (Min)], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "86f5b999-058c-4cc2-9d7d-9808b157df13"
          },
          {
            "name": "Time on Reports (Min) LP Var %",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "([Time on Reports (Min)] - [Time on Reports (Min) LP]) / [Time on Reports (Min) LP]",
            "formatString": "0.00 %",
            "lineageTag": "093dec07-176a-440c-a2b0-c10e7c64f052"
          },
          {
            "name": "Time on Reports (Min) LP Var",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": "[Time on Reports (Min)] - [Time on Reports (Min) LP]",
            "formatString": "0",
            "lineageTag": "596c79af-f00d-43d6-bd69-6a023fbc6b1a"
          },
          {
            "name": "Time on Reports (Min) LP",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Time on Reports (Min)], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Time on Reports (Min)],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([Time on Reports (Min)], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Time on Reports (Min)], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Time on Reports (Min)], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Time on Reports (Min)], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Time on Reports (Min)], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Time on Reports (Min)], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Time on Reports (Min)], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "25b0f3b3-78f8-4ebb-9899-a30e1e9d72bd"
          },
          {
            "name": "Manager Audits - Total LP",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Manager Audits - Total], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Manager Audits - Total],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([Manager Audits - Total], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Manager Audits - Total], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Manager Audits - Total], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Manager Audits - Total], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Manager Audits - Total], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Manager Audits - Total], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Manager Audits - Total], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "17dc99f9-6885-4670-b783-977a611f75be"
          },
          {
            "name": "Manager Audits - Total LP Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[Manager Audits - Total] - [Manager Audits - Total LP]",
            "formatString": "0",
            "lineageTag": "a9df85e3-df57-493a-b466-8925f870dc91"
          },
          {
            "name": "Manager Audits - Total LP Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([Manager Audits - Total] - [Manager Audits - Total LP]) / [Manager Audits - Total LP]",
            "formatString": "0.00 %",
            "lineageTag": "c3bfdd8b-66ef-4ee6-a64b-f63ae859a0de"
          },
          {
            "name": "Manager Audits - Total LY",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Manager Audits - Total], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Manager Audits - Total],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Manager Audits - Total], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "7ce092ca-fd6e-42ec-960d-106d93f3e5dd"
          },
          {
            "name": "Manager Audits - Total LY Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[Manager Audits - Total] - [Manager Audits - Total LY]",
            "formatString": "0",
            "lineageTag": "ec4ea166-0008-46e9-8873-9c10a68f1e5b"
          },
          {
            "name": "Manager Audits - Total LY Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([Manager Audits - Total] - [Manager Audits - Total LY])/ [Manager Audits - Total LY]",
            "formatString": "0.00 %",
            "lineageTag": "31946d23-ba29-4d63-b03b-77da313b5041"
          },
          {
            "name": "Overturned State Rejects LP",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Overturned State Rejects], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Overturned State Rejects],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([Overturned State Rejects], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Overturned State Rejects], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Overturned State Rejects], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Overturned State Rejects], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Overturned State Rejects], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Overturned State Rejects], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Overturned State Rejects], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c69e054b-e330-4b70-8c89-e1b87a91f606"
          },
          {
            "name": "Overturned State Rejects LP Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[Overturned State Rejects] - [Overturned State Rejects LP]",
            "formatString": "0",
            "lineageTag": "e02c816f-9e6b-42b3-b3dd-24945200434e"
          },
          {
            "name": "Overturned State Rejects LP Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([Overturned State Rejects] - [Overturned State Rejects LP]) / [Overturned State Rejects LP]",
            "formatString": "0.00 %",
            "lineageTag": "5b1f6149-977b-42f0-bed8-56c693965d79"
          },
          {
            "name": "Overturned State Rejects LY",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Overturned State Rejects], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Overturned State Rejects],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Overturned State Rejects], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "f1cd5522-16eb-4c49-a309-e925d63cf504"
          },
          {
            "name": "Overturned State Rejects LY Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[Overturned State Rejects] - [Overturned State Rejects LY]",
            "formatString": "0",
            "lineageTag": "d12c35ce-5257-42d5-9012-9bc898c08f37"
          },
          {
            "name": "Overturned State Rejects LY Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([Overturned State Rejects] - [Overturned State Rejects LY])/ [Overturned State Rejects LY]",
            "formatString": "0.00 %",
            "lineageTag": "e2abfd63-2782-4f0b-bf3c-4a003a679aad"
          },
          {
            "name": "State Reject Reviews Submitted LP",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([State Reject Reviews Submitted], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([State Reject Reviews Submitted],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([State Reject Reviews Submitted], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([State Reject Reviews Submitted], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([State Reject Reviews Submitted], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([State Reject Reviews Submitted], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([State Reject Reviews Submitted], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([State Reject Reviews Submitted], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([State Reject Reviews Submitted], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1f66a1cc-3d7d-4b1b-bc02-c6cdd09210a4"
          },
          {
            "name": "State Reject Reviews Submitted LP Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[State Reject Reviews Submitted] - [State Reject Reviews Submitted LP]",
            "formatString": "0",
            "lineageTag": "9a8c58ca-d613-41c3-963f-4de1c97c99e7"
          },
          {
            "name": "State Reject Reviews Submitted LP Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([State Reject Reviews Submitted] - [State Reject Reviews Submitted LP]) / [State Reject Reviews Submitted LP]",
            "formatString": "0.00 %",
            "lineageTag": "b40c3b20-bafe-4a3a-9c0f-4daeb4b66855"
          },
          {
            "name": "State Reject Reviews Submitted LY",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([State Reject Reviews Submitted], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([State Reject Reviews Submitted],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([State Reject Reviews Submitted], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "2bb3f15c-90ec-41e6-aced-91e163487814"
          },
          {
            "name": "State Reject Reviews Submitted LY Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[State Reject Reviews Submitted] - [State Reject Reviews Submitted LY]",
            "formatString": "0",
            "lineageTag": "93305c3a-e992-4e3b-a7dd-b9bac086143f"
          },
          {
            "name": "State Reject Reviews Submitted LY Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([State Reject Reviews Submitted] - [State Reject Reviews Submitted LY])/ [State Reject Reviews Submitted LY]",
            "formatString": "0.00 %",
            "lineageTag": "7ab4a02f-590a-47de-8673-cd4897cc9bc7"
          },
          {
            "name": "Time on Reports (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "VAR Duration = [Time on Reports (Min)] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF ( LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF ( LEN ( Seconds ) = 1, CONCATENATE ( \"0\", Seconds ), CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "cd565ee8-9e2a-4695-8304-2a61e8374fed"
          },
          {
            "name": "Time on Reports LP (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "VAR Duration = [Time on Reports (Min) LP] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "b96d6f87-f86a-42cb-8716-286e06f91fab"
          },
          {
            "name": "Time on Reports LY (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "VAR Duration = [Time on Reports (Min) LY] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (",
              "            H,",
              "            CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) )",
              "        )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "cd00423d-434e-43f2-ab3c-04b352b28103"
          },
          {
            "name": "Time on Reports LP Var (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "VAR Duration = ABS( [Time on Reports (Min) LP Var] ) * 60",
              "VAR Sign = IF([Time on Reports (Min) LP Var] < 0, \"-\", \"\")",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE( Sign, CONCATENATE( H, CONCATENATE( \":\", CONCATENATE( M, CONCATENATE( \":\", S ) ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "b44c1c22-70bb-46b3-8217-97447bb79044"
          },
          {
            "name": "Time on Reports LY Var (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Drives",
            "expression": [
              "VAR Duration = ABS( [Time on Reports (Min) LY Var] ) * 60",
              "VAR Sign = IF([Time on Reports (Min) LY Var] < 0, \"-\", \"\")",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE( Sign, CONCATENATE( H, CONCATENATE( \":\", CONCATENATE( M, CONCATENATE( \":\", S ) ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "398f7af8-f98d-4cdf-bf0a-0888ba152e07"
          },
          {
            "name": "Time on Audits (Min)",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "SUM('Audit and UAT Stats'[Manager Audits - Time on Audits (min)])",
            "formatString": "0",
            "lineageTag": "a355c48f-73ea-4d3d-9988-8c9c7211b362"
          },
          {
            "name": "Time on Audits (Min) LP",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Time on Audits (Min)], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Time on Audits (Min)],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([Time on Audits (Min)], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Time on Audits (Min)], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Time on Audits (Min)], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Time on Audits (Min)], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Time on Audits (Min)], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Time on Audits (Min)], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Time on Audits (Min)], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "af5946ab-40d5-4104-9356-669e66e4ed48"
          },
          {
            "name": "Time on Audits (Min) LP Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[Time on Audits (Min)] - [Time on Audits (Min) LP]",
            "formatString": "0",
            "lineageTag": "b34ea395-ab50-4d01-9de9-32f7f159a791"
          },
          {
            "name": "Time on Audits (Min) LP Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([Time on Audits (Min)] - [Time on Audits (Min) LP]) / [Time on Audits (Min) LP]",
            "formatString": "0.00 %",
            "lineageTag": "ab48d075-43e6-43be-9baf-31e0b191213f"
          },
          {
            "name": "Time on Audits (Min) LY",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Time on Audits (Min)], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Time on Audits (Min)],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Time on Audits (Min)], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "7252478c-cedd-41ec-bf2e-3c7d43fbfa58"
          },
          {
            "name": "Time on Audits (Min) LY Var",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "[Time on Audits (Min)] - [Time on Audits (Min) LY]",
            "formatString": "0",
            "lineageTag": "9f888c64-2f34-43ac-98ce-d246d8254782"
          },
          {
            "name": "Time on Audits (Min) LY Var %",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": "([Time on Audits (Min)] - [Time on Audits (Min) LY])/ [Time on Audits (Min) LY]",
            "formatString": "0.00 %",
            "lineageTag": "ad4293b1-d502-416a-b9ae-ad975816e8f6"
          },
          {
            "name": "Time on Audits (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR Duration = [Time on Audits (Min)] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF ( LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF ( LEN ( Seconds ) = 1, CONCATENATE ( \"0\", Seconds ), CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "81717ff2-311b-4b1b-9c67-5f9cdfbdc9de"
          },
          {
            "name": "Time on Audits LP (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR Duration = [Time on Audits (Min) LP] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "fa5b67fe-c98e-4fb9-ab33-bb18b82cb623"
          },
          {
            "name": "Time on Audits LP Var (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR Duration = ABS( [Time on Audits (Min) LP Var] ) * 60",
              "VAR Sign = IF(Duration < 0, \"-\", \"\")",
              "",
              "VAR Hours = INT ( Duration / 3600)",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE( Sign, CONCATENATE( H, CONCATENATE( \":\", CONCATENATE( M, CONCATENATE( \":\", S ) ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "433bb892-d97f-4ffa-950b-4550c47cac1a"
          },
          {
            "name": "Time on Audits LY (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR Duration = [Time on Audits (Min) LY] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (",
              "            H,",
              "            CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) )",
              "        )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "73e95d9a-1705-4834-8102-52a8f689a409"
          },
          {
            "name": "Time on Audits LY Var (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\Manager Audits",
            "expression": [
              "VAR Duration = ABS( [Time on Audits (Min) LY Var] ) * 60",
              "VAR Sign = IF(Duration < 0, \"-\", \"\")",
              "",
              "VAR Hours = INT ( Duration / 3600)",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE( Sign, CONCATENATE( H, CONCATENATE( \":\", CONCATENATE( M, CONCATENATE( \":\", S ) ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "3e22841f-36b1-47cd-950e-2aec7dda9824"
          },
          {
            "name": "Time on UAT (Min) LP",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "",
              "VAR CurrentFLMNoPrev = ",
              "SWITCH(",
              "    TRUE()",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"11\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"12\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,RIGHT(MAX('Date'[FLM Week of Year Sort]),2) = \"13\",MAX('Date'[FLM Week of Year Sort]) - 890",
              "    ,MAX('Date'[FLM Week of Year Sort]) - 10",
              ")",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Time on UAT (Min)], DATEADD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Time on UAT (Min)],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    HASONEFILTER('Date'[Week of Year]), CALCULATE([Time on UAT (Min)], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Week No]), CALCULATE([Time on UAT (Min)], DATEADD('Date'[Date], -7, DAY)),",
              "    HASONEFILTER('Date'[Month of Year]), CALCULATE([Time on UAT (Min)], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Month]), CALCULATE([Time on UAT (Min)], PARALLELPERIOD('Date'[Date], -1, MONTH)),",
              "    HASONEFILTER('Date'[Quarter]), CALCULATE([Time on UAT (Min)], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Quarter of Year]), CALCULATE([Time on UAT (Min)], PARALLELPERIOD('Date'[Date], -3, MONTH)),",
              "    HASONEFILTER('Date'[Year]), CALCULATE([Time on UAT (Min)], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "RETURN",
              "    PreviousValue",
              ""
            ],
            "formatString": "0",
            "lineageTag": "a7bbf622-0e26-4be7-9125-39bfa57af16e"
          },
          {
            "name": "Time on UAT (Min) LP Var",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "[Time on UAT (Min)] - [Time on UAT (Min) LP]",
            "formatString": "0",
            "lineageTag": "989b1a87-1cba-47fd-92bb-75a29b9fdc4b"
          },
          {
            "name": "Time on UAT (Min) LP Var %",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "([Time on UAT (Min)] - [Time on UAT (Min) LP]) / [Time on UAT (Min) LP]",
            "formatString": "0.00 %",
            "lineageTag": "4743df7e-f82f-4559-82e0-65e8e74cbc8d"
          },
          {
            "name": "Time on UAT (Min) LY",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR CurrentFLMNoPrev = MAX('Date'[FLM Week of Year Sort]) - 1000 /// 2023011 - ",
              "",
              "VAR PreviousValue = ",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER('Date'[Date]), CALCULATE([Time on UAT (Min)], DATEADD('Date'[Date], -1, YEAR)),",
              "    HASONEFILTER('Date'[FML Week of Year]), CALCULATE([Time on UAT (Min)],FILTER(ALL('Date'), 'Date'[FLM Week of Year Sort] = CurrentFLMNoPrev)),",
              "    CALCULATE([Time on UAT (Min)], PARALLELPERIOD('Date'[Date], -1, YEAR))",
              ")",
              "",
              "RETURN",
              "    PreviousValue",
              "",
              "//CALCULATE(COUNTROWS('YFM - Your Feedback Matters'), SAMEPERIODLASTYEAR('Date'[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "df153b1d-d1d6-4a9d-b218-8ebc5c572402"
          },
          {
            "name": "Time on UAT (Min) LY Var",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "[Time on UAT (Min)] - [Time on UAT (Min) LY]",
            "formatString": "0",
            "lineageTag": "030b50f8-408b-4887-8de8-6d7f49d6c7e7"
          },
          {
            "name": "Time on UAT (Min) LY Var %",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": "([Time on UAT (Min)] - [Time on UAT (Min) LY])/ [Time on UAT (Min) LY]",
            "formatString": "0.00 %",
            "lineageTag": "fe7e398c-7bb6-4497-9a0a-9196cf7fa303"
          },
          {
            "name": "Time on UAT (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR Duration = [Time on UAT (Min)] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF ( LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF ( LEN ( Seconds ) = 1, CONCATENATE ( \"0\", Seconds ), CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "a75e622e-d97e-4aed-841c-e9d779a2ee25"
          },
          {
            "name": "Time on UAT LP (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR Duration = [Time on UAT (Min) LP] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes =",
              "    INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds =",
              "    ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H =",
              "    IF ( LEN ( Hours ) = 1, ",
              "        CONCATENATE ( \"0\", Hours ),",
              "        CONCATENATE ( \"\", Hours )",
              "      )",
              "// Minutes with leading zeros",
              "VAR M =",
              "    IF (",
              "        LEN ( Minutes ) = 1,",
              "        CONCATENATE ( \"0\", Minutes ),",
              "        CONCATENATE ( \"\", Minutes )",
              "    )",
              "// Seconds with leading zeros",
              "VAR S =",
              "    IF (",
              "        LEN ( Seconds ) = 1,",
              "        CONCATENATE ( \"0\", Seconds ),",
              "        CONCATENATE ( \"\", Seconds )",
              "    )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (H, CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "8620fd69-3fb4-4e2c-ac1e-005040a990d2"
          },
          {
            "name": "Time on UAT LP Var (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR Duration = ABS( [Time on UAT (Min) LP Var] ) * 60",
              "VAR Sign = IF(Duration < 0, \"-\", \"\")",
              "",
              "VAR Hours = INT ( Duration / 3600)",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE( Sign, CONCATENATE( H, CONCATENATE( \":\", CONCATENATE( M, CONCATENATE( \":\", S ) ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "42caf233-6c36-41e7-a4b4-7cded392df19"
          },
          {
            "name": "Time on UAT LY (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR Duration = [Time on UAT (Min) LY] * 60",
              "",
              "// There are 3,600 seconds in an hour",
              "VAR Hours = INT ( Duration / 3600)",
              "// There are 60 seconds in a minute",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "// Remaining seconds are the remainder of the seconds divided by 60 after subtracting out the hours ",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE (",
              "            H,",
              "            CONCATENATE ( \":\", CONCATENATE ( M, CONCATENATE ( \":\", S ) ) )",
              "        )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "b0256ae0-71ce-4fc8-9c90-7f12c010fda2"
          },
          {
            "name": "Time on UAT LY Var (hh:mm:ss)",
            "displayFolder": "Audit and UAT Stats\\UAT SQRs",
            "expression": [
              "VAR Duration = ABS( [Time on UAT (Min) LY Var] ) * 60",
              "VAR Sign = IF(Duration < 0, \"-\", \"\")",
              "",
              "VAR Hours = INT ( Duration / 3600)",
              "VAR Minutes = INT ( MOD( Duration - ( Hours * 3600 ),3600 ) / 60)",
              "VAR Seconds = ROUNDUP(MOD ( MOD( Duration - ( Hours * 3600 ),3600 ), 60 ),0) // We round up here to get a whole number",
              "",
              "// These intermediate variables ensure that we have leading zero's concatenated onto single digits",
              "// Hours with leading zeros",
              "VAR H = IF ( LEN ( Hours ) = 1, CONCATENATE ( \"0\", Hours ), CONCATENATE ( \"\", Hours ) )",
              "// Minutes with leading zeros",
              "VAR M = IF (LEN ( Minutes ) = 1, CONCATENATE ( \"0\", Minutes ), CONCATENATE ( \"\", Minutes ) )",
              "// Seconds with leading zeros",
              "VAR S = IF (LEN ( Seconds ) = 1,CONCATENATE ( \"0\", Seconds ),CONCATENATE ( \"\", Seconds ) )",
              "// Now return hours, minutes and seconds with leading zeros in the proper format \"hh:mm:ss\"",
              "RETURN",
              "    IF (Duration = BLANK()",
              "        , BLANK()",
              "        , CONCATENATE( Sign, CONCATENATE( H, CONCATENATE( \":\", CONCATENATE( M, CONCATENATE( \":\", S ) ) ) ) )",
              "    )",
              "",
              "",
              "",
              ""
            ],
            "lineageTag": "950d759a-460b-419c-a507-a3c53b181caa"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-3001a133-51a4-4808-b559-d0bb16ffe38e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DC - User",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "DC"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f989ab1-cb53-463b-937d-505323c8efda",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Firstname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0949ae5-f47d-4016-b06b-33c3b4c73933",
            "sourceColumn": "Firstname",
            "summarizeBy": "none"
          },
          {
            "name": "Surname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a60830f-6910-4298-9b01-6c7910c72703",
            "sourceColumn": "Surname",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76aa48f0-dba8-458b-a7ce-c6ece5944b6e",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b707ed80-af2d-4740-b0e2-702b2d1dfb5a",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "09beec5a-f934-4359-929e-e23e17cbed48",
            "sourceColumn": "Manager Name",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6c4c89a9-e176-4666-9a37-bd16be34c6ff",
            "sourceColumn": "Manager Email",
            "summarizeBy": "none"
          },
          {
            "name": "QmaticUserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "da95ec70-ec16-47ff-af94-a40f4e924f84",
            "sourceColumn": "QmaticUserId",
            "summarizeBy": "none"
          },
          {
            "name": "DrivesUserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bffbe071-8413-4b1a-b232-bdda15dd3f9f",
            "sourceColumn": "DrivesUserId",
            "summarizeBy": "none"
          },
          {
            "name": "CallManagerAgentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e777073-5405-4a09-8940-7a56376ffa4f",
            "sourceColumn": "CallManagerAgentId",
            "summarizeBy": "none"
          },
          {
            "name": "SnapengageAgentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3972ef9c-723d-4e3c-a21b-e215f0a0ef11",
            "sourceColumn": "SnapengageAgentId",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'DC - User'[Firstname] & \" \" & 'DC - User'[Surname]",
            "isDataTypeInferred": true,
            "lineageTag": "66536f86-1c7b-41b2-a7a4-0bbcd6b32d72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DrivesFinancialsUserId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "08afd577-ddae-40e6-9c62-20c1af1c384e",
            "sourceColumn": "DrivesFinancialsUserId",
            "summarizeBy": "none"
          },
          {
            "name": "User",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'DC - User'[Firstname] & \" \" & 'DC - User'[Surname]",
            "isDataTypeInferred": true,
            "lineageTag": "04508bdb-bd07-43b9-8964-428a9f22951f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'DC - User'[Firstname] & \" \" & 'DC - User'[Surname]",
            "isDataTypeInferred": true,
            "lineageTag": "01ae2a2c-ab3b-4eeb-bde7-58e15615700f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Latest Pay Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "887108d3-56f6-40d0-a6f7-0d78dcf60d23",
            "sourceColumn": "Latest Pay Status",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2706623d-a1f7-423d-8f1e-75f88a7d57a2",
        "partitions": [
          {
            "name": "DC - User-a9aca1cb-84be-4b8a-83ff-c3a34ca6269f",
            "mode": "import",
            "queryGroup": "DC",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SQLServerName, SQLServerDB, [Query=\"select #(lf)#(tab) mappedAndMVDL.Code#(tab)#(lf)#(tab),mappedAndMVDL.Firstname#(tab)#(lf)#(tab),mappedAndMVDL.Surname#(tab)#(lf)#(tab),mappedAndMVDL.Department#(tab)#(lf)#(tab),mappedAndMVDL.Title#(lf)#(tab),mappedAndMVDL.ManagerName#(tab)#(lf)#(tab),mappedAndMVDL.ManagerEmail#(lf)#(tab),QmaticUserId = Isnull(mappedAndMVDL.QmaticUserId, (RAND() * -1000000) + ROW_NUMBER() OVER ( ORDER BY mappedAndMVDL.Code))#(lf)#(tab),mappedAndMVDL.DrivesUserId #(lf)#(tab),mappedAndMVDL.DrivesFinancialsUserId #(lf)#(tab),mappedAndMVDL.CallManagerAgentId #(lf)#(tab),mappedAndMVDL.SnapengageAgentId #(lf)from (#(lf)select#(lf)#(tab) u.Code#(tab)#(lf)#(tab),u.Firstname#(tab)#(lf)#(tab),u.Surname#(tab)#(lf)#(tab),u.Department#(tab)#(lf)#(tab),u.Title#(lf)#(tab),u.ManagerName#(tab)#(lf)#(tab),u.ManagerEmail#(lf)#(tab),QmaticUserId = q.Code#(lf)#(tab),DrivesUserId = Isnull(d.Code, u.Code )#(lf)#(tab),DrivesFinancialsUserId = Isnull(u.[DrivesFinancialsUser_Code],u.Code)#(lf)#(tab),CallManagerAgentId = Isnull(c.Code, u.Code)#(lf)#(tab),SnapengageAgentId = Isnull(s.Code, u.Code)#(lf)from [mdm].[MVDCUser] u#(lf)#(tab)left join [mdm].[MVQmaticUser] q on u.[QmaticStaff_Code] = q.Code#(lf)#(tab)left join [mdm].[MVDrivesUser] d on u.[DrivesUser_Code] = d.Code#(lf)#(tab)left join mdm.MVCMAgent c on u.CMAgent_Code = c.Code#(lf)#(tab)left join mdm.MVSnapUser s on u.[SnapEngage Agent_Code] = s.Code#(lf)where #(lf)#(tab)[SnapEngage Agent_Code] is not null#(lf)#(tab)or QmaticStaff_Code is not NULL#(lf)#(tab)or DrivesUser_Code is not NULL#(lf)#(tab)or CMAgent_Code is not NULL#(lf)#(tab)or DrivesFinancialsUser_Code is not NULL#(lf)union#(lf)select#(lf)#(tab) u.Code#(tab)#(lf)#(tab),u.Firstname#(tab)#(lf)#(tab),u.Surname#(tab)#(lf)#(tab),u.Department#(tab)#(lf)#(tab),u.Title#(lf)#(tab),u.ManagerName#(tab)#(lf)#(tab),u.ManagerEmail#(lf)#(tab),QmaticUserId = q.Code#(lf)#(tab),DrivesUserId = Isnull(d.Code, u.Code )#(lf)#(tab),DrivesFinancialsUserId = Isnull(u.[DrivesFinancialsUser_Code],u.Code)#(lf)#(tab),CallManagerAgentId = Isnull(c.Code, u.Code)#(lf)#(tab),SnapengageAgentId = Isnull(s.Code, u.Code)#(lf)from [mdm].[MVDCUser] u#(lf)#(tab)left join [mdm].[MVQmaticUser] q on u.[QmaticStaff_Code] = q.Code#(lf)#(tab)left join [mdm].[MVDrivesUser] d on u.[DrivesUser_Code] = d.Code#(lf)#(tab)left join mdm.MVCMAgent c on u.CMAgent_Code = c.Code#(lf)#(tab)left join mdm.MVSnapUser s on u.[SnapEngage Agent_Code] = s.Code#(lf)where #(lf)#(tab)department = 'DRIVERS LICENSE'#(lf)#(tab)or department = 'Drives User'#(lf)#(tab)or department = 'MOTOR VEHICLE'#(lf)) mappedAndMVDL#(lf)--order by 1\", CreateNavigationProperties=false]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"ManagerName\", \"Manager Name\"}, {\"Title\", \"Job Title\"}, {\"ManagerEmail\", \"Manager Email\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"QmaticUserId\", Int64.Type}}),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Changed Type\",{{\"Firstname\", Text.Proper, type text}, {\"Surname\", Text.Proper, type text}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Capitalized Each Word\", {\"Code\"}, #\"Pay Type JDE Latest Status\", {\"Email Address\"}, \"Pay Type JDE Latest Status\", JoinKind.LeftOuter),",
                "    #\"Expanded Pay Type JDE Latest Status\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Pay Type JDE Latest Status\", {\"PayStatus\"}, {\"Pay Type JDE Latest Status.PayStatus\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded Pay Type JDE Latest Status\",{{\"Pay Type JDE Latest Status.PayStatus\", \"Latest Pay Status\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns1\",null,\"Unknown\",Replacer.ReplaceValue,{\"Latest Pay Status\"}),",
                "    #\"Replaced Bot\"= Table.ReplaceValue(#\"Replaced Value\",each [Latest Pay Status],each if [Code] = \"bot:api:d0fbc4ac-a793-4116-a0a9-cdb2bafe66fd:1456312989:routing\" then \"Bot\" else [Latest Pay Status],Replacer.ReplaceValue,{\"Latest Pay Status\"})",
                "in",
                "    #\"Replaced Bot\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MDS - SnapEngage Chat Agent Id",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "936f13b6-700e-4101-a40c-f5be69713d90",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ed1454c5-9787-46ed-af40-a873f8fbdf55",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fc0dd574-d582-4157-8073-4dae76976627",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "EnterDateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "0e7a2af8-fe2d-40c7-9aa6-42c6936d7a91",
            "sourceColumn": "EnterDateTime",
            "summarizeBy": "none"
          },
          {
            "name": "EnterUserName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "68045cdb-3c1f-458a-8362-e3ea0c25fd2b",
            "sourceColumn": "EnterUserName",
            "summarizeBy": "none"
          },
          {
            "name": "LastChgDateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "dc442c03-2f56-43ac-b6af-71262987884e",
            "sourceColumn": "LastChgDateTime",
            "summarizeBy": "none"
          },
          {
            "name": "LastChgUserName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "65ff3854-d5ad-4df2-a485-19ad5a41181e",
            "sourceColumn": "LastChgUserName",
            "summarizeBy": "none"
          },
          {
            "name": "LastChgVersionNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e92a715d-bbd1-4690-bee2-b171763942ff",
            "sourceColumn": "LastChgVersionNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidationStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f37ffd2b-e978-4ada-a2ca-d46b95689b45",
            "sourceColumn": "ValidationStatus",
            "summarizeBy": "none"
          },
          {
            "name": "DC - User.Firstname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6e23ae0c-bf2c-4dd8-8bbe-58b147840fed",
            "sourceColumn": "DC - User.Firstname",
            "summarizeBy": "none"
          },
          {
            "name": "DC - User.Surname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6121c188-453c-4962-917c-5edc003c74c4",
            "sourceColumn": "DC - User.Surname",
            "summarizeBy": "none"
          },
          {
            "name": "DC - User.Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8be0c2cd-2e58-44cc-bda0-49028782d43c",
            "sourceColumn": "DC - User.Department",
            "summarizeBy": "none"
          },
          {
            "name": "DC - User.Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5cff1b68-bfec-4cd4-9626-20e05c7dfb19",
            "sourceColumn": "DC - User.Job Title",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4a8f9613-f79c-4132-a448-7189938313c3",
        "partitions": [
          {
            "name": "MDS - SnapEngage Chat Agent Id-78e4b256-9cdf-43b0-909b-713c0bd975da",
            "mode": "import",
            "queryGroup": "MDS",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SQLServerName, SQLServerDB, [CreateNavigationProperties=false]),",
                "    mdm_MVSnapUser = Source{[Schema=\"mdm\",Item=\"MVSnapUser\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(mdm_MVSnapUser, {\"Code\"}, #\"DC - User\", {\"SnapengageAgentId\"}, \"DC - User\", JoinKind.Inner),",
                "    #\"Expanded DC - User\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DC - User\", {\"Firstname\", \"Surname\", \"Department\", \"Job Title\"}, {\"DC - User.Firstname\", \"DC - User.Surname\", \"DC - User.Department\", \"DC - User.Job Title\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded DC - User\",{\"ID\", \"MUID\", \"VersionName\", \"VersionNumber\", \"Version_ID\", \"VersionFlag\", \"ChangeTrackingMask\", \"EnterVersionNumber\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - Mail Rejects",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "columns": [
          {
            "name": "Date Recieved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "4647e684-616f-46c8-bb44-c3febfc62f33",
            "sourceColumn": "Date Recieved",
            "summarizeBy": "none"
          },
          {
            "name": "Date Rejected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "9ecaba3d-fb84-4d81-9029-1fe5f03a4c12",
            "sourceColumn": "Date Rejected",
            "summarizeBy": "none"
          },
          {
            "name": "Reject #",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd471dd7-5be7-4b64-b0fe-de7bd8da998d",
            "sourceColumn": "Reject #",
            "summarizeBy": "none"
          },
          {
            "name": "Letter ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "573528b8-d74b-4539-9833-1fb9a522b82a",
            "sourceColumn": "Letter ID",
            "summarizeBy": "none"
          },
          {
            "name": "Document",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e06dceeb-87b5-46da-8821-16375328bc11",
            "sourceColumn": "Document",
            "summarizeBy": "none"
          },
          {
            "name": "Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c64cdb0-8511-45f3-8e13-6dd4d0ead7a7",
            "sourceColumn": "Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cac98833-363f-4362-95d5-b1d7d3c59f2c",
            "sourceColumn": "Comments",
            "summarizeBy": "none"
          },
          {
            "name": "Dealer/Lien Holder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0739b7b-a41a-4543-af4a-22e9930ef790",
            "sourceColumn": "Dealer/Lien Holder",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7899090-0f47-46ae-b6bf-007ff262b254",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tables.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b98255c7-6a72-49eb-8334-2048f84adb7c",
            "sourceColumn": "Tables.Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5b7b9664-4252-405f-937a-b0b47ff5e345",
        "measures": [
          {
            "name": "Mail Reject Count",
            "expression": "COUNTROWS('Staff Stats - Mail Rejects')",
            "formatString": "0",
            "lineageTag": "2e0ac947-58b8-4213-a7c0-1beabf0a20c9"
          }
        ],
        "partitions": [
          {
            "name": "Staff Stats - Mail Rejects-57c60de2-4520-454e-8cf1-3c41768d3ef9",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - File Table List\",",
                "    #\"Filtered Rows1\" = Table.SelectRows(Source, each ([Tables.Name] = \"MM Mail Rejects\")),",
                "    #\"Expanded Tables.Data\" = Table.ExpandTableColumn(#\"Filtered Rows1\", \"Tables.Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\"}, {\"Date Recieved\", \"Date Rejected\", \"Reject #\", \"Letter ID\", \"Dealer/Lien Holder\", \"Document\", \"Reason\", \"Comments\"}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Expanded Tables.Data\", each ([Date Recieved] <> null and [Date Recieved] <> \"Date Recieved\")),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows3\",{{\"Date Recieved\", type date}, {\"Date Rejected\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SnapEngageChat",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Snap"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "18ecda57-6a67-4f7a-871c-fc5664da523b",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "40aa7f58-cff8-4e27-ad7b-65eaece77e6e",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Id.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d1a48420-9186-486f-8f02-cdbebf139ed6",
            "sourceColumn": "Id.1",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cbd3040e-2d96-4278-9131-e082c96edfb7",
            "sourceColumn": "Date",
            "summarizeBy": "sum"
          },
          {
            "name": "Date Seconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9d7f2946-b9bc-432d-9766-c6e952dfb60e",
            "sourceColumn": "Date Seconds",
            "summarizeBy": "none"
          },
          {
            "name": "Date Milliseconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9c8be24c-08d8-4e07-a1ef-913174a54758",
            "sourceColumn": "Date Milliseconds",
            "summarizeBy": "none"
          },
          {
            "name": "Alias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "66d56a48-012f-4fc9-804a-ea4d9a7b5c15",
            "sourceColumn": "Alias",
            "summarizeBy": "none"
          },
          {
            "name": "Message",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fc0959ea-6b71-47b6-b585-f75a532593f0",
            "sourceColumn": "Message",
            "summarizeBy": "none"
          },
          {
            "name": "Sender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5640438b-07ac-4158-8a33-88b429974a70",
            "sourceColumn": "Sender",
            "summarizeBy": "none"
          },
          {
            "name": "Whispermessage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f4111ad2-5078-45b2-9efa-5402b115d07b",
            "sourceColumn": "Whispermessage",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "f65754e7-db8c-4dd0-bdbd-42b0b0a36d06",
        "partitions": [
          {
            "name": "SnapEngageChat-0fc85d4c-8528-4010-81ef-9596aa1d081f",
            "mode": "import",
            "queryGroup": "SnapEngage",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/snapengage/integrationApi/\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Extension] = \".json\")),",
                "    #\"Expanded Attributes\" = Table.ExpandRecordColumn(#\"Filtered Rows\", \"Attributes\", {\"Size\"}, {\"Attributes.Size\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Expanded Attributes\", each ([Attributes.Size] <> 45)),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Attributes.Size\", \"Folder Path\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Columns1\", \"SnapBinarytoText\", each SnapBinarytoText([Content])),",
                "    #\"Expanded SnapBinarytoText\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"SnapBinarytoText\", {\"Column1\"}, {\"Column1\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Expanded SnapBinarytoText\",{\"Content\"}),",
                "    #\"Invoked Custom Function1\" = Table.AddColumn(#\"Removed Columns\", \"SnapFileChats\", each SnapFileChats([Column1])),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Invoked Custom Function1\",{\"Column1\"}),",
                "    #\"Expanded SnapFileChats\" = Table.ExpandTableColumn(#\"Removed Columns2\", \"SnapFileChats\", {\"id\", \"id.1\", \"date\", \"date_seconds\", \"date_milliseconds\", \"alias\", \"message\", \"sender\", \"whisperMessage\"}, {\"id\", \"id.1\", \"date\", \"date_seconds\", \"date_milliseconds\", \"alias\", \"message\", \"sender\", \"whisperMessage\"}),",
                "    Underscore = Table.RenameColumns(#\"Expanded SnapFileChats\", List.Transform(Table.ColumnNames(#\"Expanded SnapFileChats\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    Proper = Table.RenameColumns(Underscore, List.Transform(Table.ColumnNames(Underscore), each {_, Text.Proper(_)}))",
                "in",
                "    Proper"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - Appointment",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Appointment Status Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "76af5ada-399e-4387-99ce-55e636fdbc12",
            "sourceColumn": "Appointment Status Key",
            "summarizeBy": "none"
          },
          {
            "name": "Cancelled Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ebacc9d8-550c-4a91-8fe0-4eb458efd4c3",
            "sourceColumn": "Cancelled Date Key",
            "summarizeBy": "count"
          },
          {
            "name": "Waiting Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0d03c27e-b4af-41f4-8288-7e3c9a4c6fdc",
            "sourceColumn": "Waiting Time",
            "summarizeBy": "sum"
          },
          {
            "name": "End Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a383c98b-a92b-425d-a115-f094e7ff19f1",
            "sourceColumn": "End Time Key",
            "summarizeBy": "count"
          },
          {
            "name": "Days Cancelled Before",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5f8b054e-f47d-40bb-9ab2-36fd9f406ae6",
            "sourceColumn": "Days Cancelled Before",
            "summarizeBy": "average"
          },
          {
            "name": "Transaction Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f262bd0f-cc13-4ce6-9e03-f0e9f28d42ae",
            "sourceColumn": "Transaction Time",
            "summarizeBy": "average"
          },
          {
            "name": "Lateness",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a3e650f4-6e4d-4ed1-ac31-ebeff5943eed",
            "sourceColumn": "Lateness",
            "summarizeBy": "average"
          },
          {
            "name": "Branch Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fd99496c-9721-4c13-9db0-9a72446d0e1f",
            "sourceColumn": "Branch Key",
            "summarizeBy": "none"
          },
          {
            "name": "Created At",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "60fff558-3ac2-4d4f-88cb-e22d9bf00424",
            "sourceColumn": "Created At",
            "summarizeBy": "none"
          },
          {
            "name": "Origin Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "24f9c018-b4da-48a1-b6d0-8c1903cb3fa0",
            "sourceColumn": "Origin Id",
            "summarizeBy": "count"
          },
          {
            "name": "Count Services",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fddba26b-6fef-4dc4-aa10-e325b4a23739",
            "sourceColumn": "Count Services",
            "summarizeBy": "sum"
          },
          {
            "name": "Client Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "14354c68-de0b-4e1a-b82d-708b7498ce16",
            "sourceColumn": "Client Key",
            "summarizeBy": "count"
          },
          {
            "name": "Updated Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "083fe738-39cb-4e89-8439-93b4f88fd316",
            "sourceColumn": "Updated Count",
            "summarizeBy": "average"
          },
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3398fbf1-66b2-44b4-bda2-ceaaa7855c1b",
            "sourceColumn": "Date Key",
            "summarizeBy": "count"
          },
          {
            "name": "Arrival Status Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5e10a504-fc93-4212-8004-d8d8dd5795e5",
            "sourceColumn": "Arrival Status Key",
            "summarizeBy": "none"
          },
          {
            "name": "Service Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "08ca8f37-6a93-4939-9c64-7906a6c173d2",
            "sourceColumn": "Service Key",
            "summarizeBy": "count"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "244bca56-5fd6-49f6-9708-8ad5ab0d2f5e",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Created Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2da9206d-ff79-4a70-8e83-a2b6b9498b41",
            "sourceColumn": "Created Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Resource Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fb699f51-0a71-4fac-8b2f-fc453e9b452d",
            "sourceColumn": "Resource Key",
            "summarizeBy": "count"
          },
          {
            "name": "Walking Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "742e9320-8fa5-426b-986d-f498d9d83aa0",
            "sourceColumn": "Walking Time",
            "summarizeBy": "average"
          },
          {
            "name": "Wrapup Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ed83b529-af35-442c-85a8-10cd5f36dcc6",
            "sourceColumn": "Wrapup Time",
            "summarizeBy": "average"
          },
          {
            "name": "Created Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "52458152-8528-4efc-8355-5f623efb54ed",
            "sourceColumn": "Created Time Key",
            "summarizeBy": "count"
          },
          {
            "name": "Days To Appointment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "30927a0b-f02b-4b5c-a5b4-65bfe2543c6e",
            "sourceColumn": "Days To Appointment",
            "summarizeBy": "sum"
          },
          {
            "name": "Appointment Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7d6a8699-5f54-4ed7-90c4-d1c5ed6ab39f",
            "sourceColumn": "Appointment Duration",
            "summarizeBy": "average"
          },
          {
            "name": "Tardiness",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8fcac45e-44da-4d18-8ae1-66fb15deb0fb",
            "sourceColumn": "Tardiness",
            "summarizeBy": "average"
          },
          {
            "name": "Start Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0f86f232-8ccb-422c-a557-a42aa19345a0",
            "sourceColumn": "Start Time Key",
            "summarizeBy": "count"
          }
        ],
        "isHidden": true,
        "lineageTag": "c8e4706e-38ac-4e5a-80e1-fe6524397822",
        "partitions": [
          {
            "name": "Qmatic - Appointment-92fb74fa-d344-4a16-966d-3dd1e22466ef",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"Appointment.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" ))",
                "in",
                "    #\"Camel Cap\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - AppointmentArrivalStatus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Arrival Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "ef715496-6c88-4608-8ca2-ee7b26bcae4e",
            "sourceColumn": "Arrival Status",
            "summarizeBy": "none"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "b4511f7b-c737-4178-b225-12b80c22f1e7",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "fd2beede-820f-49e6-bae5-4218f6dc724a",
        "partitions": [
          {
            "name": "Qmatic - AppointmentArrivalStatus-76618449-3f8a-44e5-b748-467f8fdcee5a",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"AppointmentArrivalStatus.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Camel Cap\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - AppointmentService",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Appointment Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3301755e-80b9-48ab-a174-602edfb3539a",
            "sourceColumn": "Appointment Id",
            "summarizeBy": "none"
          },
          {
            "name": "Served",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "eaadcacc-4aa8-465d-a800-788fa722c0d6",
            "sourceColumn": "Served",
            "summarizeBy": "none"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cb16c89d-8e96-4480-9761-1b2f8a16a395",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "Service Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1bdbdc80-cde7-4d67-a265-3af496220957",
            "sourceColumn": "Service Key",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "05f52a95-975c-4f16-9e71-44a45b63c420",
        "partitions": [
          {
            "name": "Qmatic - AppointmentService-1ced0dc2-fa6c-475a-98c5-f41d2bc23010",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"AppointmentService.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" ))",
                "in",
                "    #\"Camel Cap\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - AppointmentStatus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "isKey": true,
            "lineageTag": "06efa0bc-f6d4-4be2-b534-ab73949bc167",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isDefaultLabel": true,
            "isHidden": true,
            "lineageTag": "95a6ee33-2fd4-48e2-9d5c-411c09442fa1",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4c4d0c0b-25f3-416c-b527-2b3c2794e616",
        "partitions": [
          {
            "name": "Qmatic - AppointmentStatus-6ac21622-5f52-43f1-b8e7-9c0be6a5328f",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"AppointmentStatus.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Removed Duplicates\" = Table.Distinct(Underscore)",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - StaffSession",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Served Count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "897936b9-8054-4bd2-a1b3-ba7cea218570",
            "sourceColumn": "Served Count",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9066a409-1dfd-4305-a472-794839aa58d3",
            "sourceColumn": "Total Time",
            "summarizeBy": "average"
          },
          {
            "name": "Visits Served",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ffad4289-cc63-43e5-a1c0-42cb8b5acb6f",
            "sourceColumn": "Visits Served",
            "summarizeBy": "sum"
          },
          {
            "name": "End Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ce30d089-535a-483b-9d07-b2e92d4fdfba",
            "sourceColumn": "End Time Key",
            "summarizeBy": "count"
          },
          {
            "name": "Serving Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1b6a369-675b-413c-a727-5513ab071b70",
            "sourceColumn": "Serving Time",
            "summarizeBy": "average"
          },
          {
            "name": "Idle Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "65439dd0-6a7b-4fb5-8d7e-7c6101dec81f",
            "sourceColumn": "Idle Time",
            "summarizeBy": "average"
          },
          {
            "name": "Wrapup Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "99917769-9713-4a83-a5bb-8ffc7f5ebf28",
            "sourceColumn": "Wrapup Time",
            "summarizeBy": "average"
          },
          {
            "name": "Branch Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a6a2b63b-82f2-4db5-8421-90da7c2f525f",
            "sourceColumn": "Branch Key",
            "summarizeBy": "none"
          },
          {
            "name": "Created At",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "78b97236-e17f-43b9-ab84-1c9a7007aa06",
            "sourceColumn": "Created At",
            "summarizeBy": "none"
          },
          {
            "name": "Time Seconds",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c6255794-7b84-4996-bc1f-5524aad06fde",
            "sourceColumn": "Time Seconds",
            "summarizeBy": "average"
          },
          {
            "name": "Session Outcome Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cf423978-e435-4286-b12c-185c28baf1af",
            "sourceColumn": "Session Outcome Key",
            "summarizeBy": "none"
          },
          {
            "name": "Staff Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6070339e-eb26-4fe6-848d-d88d61ddf533",
            "sourceColumn": "Staff Key",
            "summarizeBy": "none"
          },
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "46bd4c87-a89b-4487-82ad-bec4fa9c1811",
            "sourceColumn": "Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Store Next Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8bd1c8a-87df-4a93-8be0-ddd8a0425e88",
            "sourceColumn": "Store Next Time",
            "summarizeBy": "average"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "829a332d-41e6-4895-8e6b-a4e070f2dc46",
            "sourceColumn": "Id",
            "summarizeBy": "count"
          },
          {
            "name": "Time Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "91ddf8d0-c025-4135-b544-f8cc6673cbbb",
            "sourceColumn": "Time Key",
            "summarizeBy": "count"
          },
          {
            "name": "End Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f28059f0-0960-499d-aefe-578dd4614e83",
            "sourceColumn": "End Timestamp",
            "summarizeBy": "none"
          },
          {
            "name": "Start Timestamp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c0229b51-3942-4afc-8a48-a166e8bb5b36",
            "sourceColumn": "Start Timestamp",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4edb40a6-9b72-4c39-8400-1fc8c8f7759a",
        "partitions": [
          {
            "name": "Qmatic - StaffSession-9512cdc0-6db5-4939-bf2e-487a1053006e",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"StaffSession.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" ))",
                "in",
                "    #\"Camel Cap\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Qmatic - StaffSessionOutcome",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Qmatic"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "53eff56c-9d69-4f22-8470-3afcfda9d7e1",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d8964084-016f-4a87-b1ce-10187bbc8ed8",
            "sourceColumn": "Id",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "a13200ca-d0fc-4428-a4e9-7f627e2293e4",
        "partitions": [
          {
            "name": "Qmatic - StaffSessionOutcome-b696c0c6-180b-48d9-944f-c2764cef80d2",
            "mode": "import",
            "queryGroup": "Qmatic",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Qmatic - File List\",",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"StaffSessionOutcome.pq\")),",
                "    #\"pq\" = #\"Filtered Rows\"{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\")",
                "in",
                "    #\"Imported Parquet\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Drives - DL Fee Waiver Tracking",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Office",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d04a53fc-df21-448f-a9f4-071ff55d6cb0",
            "sourceColumn": "Office",
            "summarizeBy": "none"
          },
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8818c297-8300-457f-8318-4bb702b5a1df",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "2",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a816daa7-b7fe-455b-a96b-82e253eea872",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Fee Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5f55cd6e-f35a-48ae-a7f3-2574f9719daa",
            "sourceColumn": "Fee Type",
            "summarizeBy": "none"
          },
          {
            "name": "Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f561c630-0bfd-44d1-99a2-2cda5f0e6f6b",
            "sourceColumn": "Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Calculated Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "88f50948-acd7-4109-bde2-006128f14d27",
            "sourceColumn": "Calculated Amount",
            "summarizeBy": "none"
          },
          {
            "name": "Amount Charged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c768b89c-e8bd-48be-b9ab-15f6dda5bbd2",
            "sourceColumn": "Amount Charged",
            "summarizeBy": "none"
          },
          {
            "name": "Waived Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bd110520-14b3-4c51-bbfc-54064d9edbcb",
            "sourceColumn": "Waived Amount",
            "summarizeBy": "none"
          },
          {
            "name": "Cashier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bb5f2562-3206-408e-a32e-0bd3fc0ca56d",
            "sourceColumn": "Cashier",
            "summarizeBy": "none"
          },
          {
            "name": "Date Of Transaction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "403450f5-4b19-4eed-b3e5-87454591cc6b",
            "sourceColumn": "Date Of Transaction",
            "summarizeBy": "none"
          },
          {
            "name": "View Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f3792472-71e9-4262-8c30-03c8d7c14293",
            "sourceColumn": "View Title",
            "summarizeBy": "none"
          },
          {
            "name": "View Title And Registration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "305b4a15-5e22-41c1-bd3f-6de93c969ee6",
            "sourceColumn": "View Title And Registration",
            "summarizeBy": "none"
          },
          {
            "name": "Approver",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ea7e87f2-20b5-4222-a4bd-394d4a73ff2e",
            "sourceColumn": "Approver",
            "summarizeBy": "none"
          },
          {
            "name": "Note",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5f318f38-b1d0-4776-9e2c-54f4524c6243",
            "sourceColumn": "Note",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "71bd24ab-4102-48ae-84c3-9e112a6e5567",
        "partitions": [
          {
            "name": "Drives - DL Fee Waiver Tracking-63bf62c7-c893-493a-9df1-7d6131b8556c",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/drives/Fee Waiver Tracking/\"),",
                "    #\"pq\" = Source{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Camel Cap\" = Table.TransformColumnNames(#\"Imported Parquet\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"A\"..\"Z\"})(_), \" \" )),",
                "    #\"Number Cap\" = Table.TransformColumnNames(#\"Camel Cap\", each Text.Combine(Splitter.SplitTextByCharacterTransition({\"a\"..\"z\"}, {\"0\"..\"9\"}) (_), \" \" )),",
                "    #\"Underscore\" = Table.RenameColumns(#\"Number Cap\", List.Transform(Table.ColumnNames(#\"Number Cap\"), each {_, Text.Replace(_, \"_\", \" \")})),",
                "    #\"Filtered Rows\" = Table.SelectRows(Underscore, each [Office] <> null)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DC - Drives Goals",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "DC"
          }
        ],
        "columns": [
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19410644-72d7-466c-85c6-b57f04a633c3",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "DrivesUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1aa9719a-5a74-402f-9d76-8ae5e5be00a5",
            "sourceColumn": "DrivesUser",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ee8572d0-d814-48e6-b194-bef0e6336b77",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Transaction Type_Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea54302d-0352-4505-a67b-3e466941985c",
            "sourceColumn": "Transaction Type_Code",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Type_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "812eeb52-b1a0-4b5a-9aa7-6d75959f68e6",
            "sourceColumn": "Transaction Type_Name",
            "summarizeBy": "none"
          },
          {
            "name": "GoalPercent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fa87fda5-8260-46aa-8487-7ceafe8a8da0",
            "sourceColumn": "GoalPercent",
            "summarizeBy": "sum"
          },
          {
            "name": "GoalCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d0672c1-95fb-43ad-a3fb-2314f8c86f93",
            "sourceColumn": "GoalCount",
            "summarizeBy": "sum"
          },
          {
            "name": "Goal Avg Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b49ff4db-d614-46da-916e-4527de3bd92a",
            "sourceColumn": "Goal Avg Time",
            "summarizeBy": "sum"
          },
          {
            "name": "EnterDateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a3758d95-84ca-49c3-8c84-67cbf8fe4d3f",
            "sourceColumn": "EnterDateTime",
            "summarizeBy": "none"
          },
          {
            "name": "EnterUserName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ba91473-bf4f-43a4-8be4-42859a4c8d7f",
            "sourceColumn": "EnterUserName",
            "summarizeBy": "none"
          },
          {
            "name": "month_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d594f068-001d-4e1d-92da-b70f06b5f6d0",
            "sourceColumn": "month_name",
            "summarizeBy": "none"
          },
          {
            "name": "month_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "378179ef-ef8b-40ef-b8a3-7bfd613d4e42",
            "sourceColumn": "month_number",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83849f08-4813-4afe-a957-1f34c9113f16",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9cf56b1a-8422-4ca7-9dc0-222003b3c52e",
        "partitions": [
          {
            "name": "DC - Drives Goals-0bc52278-e5e6-41ba-ba9a-e376c46185f8",
            "mode": "import",
            "queryGroup": "DC",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SQLServerName, SQLServerDB, [Query=\"SELECTg.[Code],DrivesUser = u.Code,[Year],[Transaction Type_Code],[Transaction Type_Name],[GoalPercent],[GoalCount],[Goal Avg Time],g.[EnterDateTime],g.[EnterUserName],month_index.month_name,month_index.month_numberFROM [MDS].[mdm].[MVGoal] gcross join mdm.MVDrivesUSer ucross join (SELECT 'January' as month_name, 1 as month_numberUNIONSELECT 'February', 2UNIONSELECT 'March', 3UNIONSELECT 'April', 4UNIONSELECT 'May', 5UNIONSELECT 'June', 6UNIONSELECT 'July', 7UNIONSELECT 'August', 8UNIONSELECT 'September', 9UNIONSELECT 'October', 10UNIONSELECT 'November', 11UNIONSELECT 'December', 12#(lf)) as month_indexwhere g.[Transaction Type_Name] = 'Drives'\", CreateNavigationProperties=false]),",
                "    #\"Added Custom\" = Table.AddColumn(Source, \"Date\", each #date([Year],[month_number],1))",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "YFM - Your_Feedback_Matters_v3",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "YFM"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6fd2c519-9525-4f1c-a2ab-cf9a3004b87b",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f6987f78-7247-4025-b186-bae89ef28f0c",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactWanted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cb8bde26-911a-4a39-b560-4646132f498f",
            "sourceColumn": "ContactWanted",
            "summarizeBy": "none"
          },
          {
            "name": "ContactMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "717f2e64-0bec-4869-9d01-e376783b6fcb",
            "sourceColumn": "ContactMethod",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ddadde4a-c475-4789-b575-8722b574b08d",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f0494316-4489-425f-ad5c-9d64f4b41026",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "FeedbackDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "a67ffa0d-9ff9-45bd-9fe3-e5c06d6c9592",
            "sourceColumn": "FeedbackDate",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceReceived",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "909b2235-15d7-4ea4-9bcd-a28190b5dd42",
            "sourceColumn": "ServiceReceived",
            "summarizeBy": "none"
          },
          {
            "name": "LocationVisited",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4108bcf4-9eb7-4a64-923c-360c61e2d428",
            "sourceColumn": "LocationVisited",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4fe6bb42-07b4-4360-9fb7-a4bd53210df8",
            "sourceColumn": "TransactionCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionNotCompletedReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "dd30aa09-96de-4a21-8d8f-5ea0a23b78f2",
            "sourceColumn": "TransactionNotCompletedReason",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSatisfactionRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "752c338f-2f4d-40b7-b9a2-73bce37056b2",
            "sourceColumn": "OverallSatisfactionRating",
            "summarizeBy": "none"
          },
          {
            "name": "WhoAssistedYou",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4b171a28-418d-43a6-83e4-cf87d4c29372",
            "sourceColumn": "WhoAssistedYou",
            "summarizeBy": "none"
          },
          {
            "name": "OneThingLiked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "12d4435e-ea6f-4381-b7fd-fd3287edd273",
            "sourceColumn": "OneThingLiked",
            "summarizeBy": "none"
          },
          {
            "name": "HasSuggestedImprovement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "48656a43-acf5-4220-80df-27468d3ad607",
            "sourceColumn": "HasSuggestedImprovement",
            "summarizeBy": "none"
          },
          {
            "name": "SuggestedImprovement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5c7c164a-9878-4df0-867e-19e74526c45b",
            "sourceColumn": "SuggestedImprovement",
            "summarizeBy": "none"
          },
          {
            "name": "Entry Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "03eae971-c38a-4018-a54b-7bdf5afb3e9c",
            "sourceColumn": "Entry Date",
            "summarizeBy": "none"
          },
          {
            "name": "FeedbackId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8724f48d-8ed2-4166-b243-46f61663aebc",
            "sourceColumn": "FeedbackId",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "630343c0-c000-4d85-a2ae-6aa8475ba2e1",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "IsPositive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "46df3b5d-ba36-49c9-8dd4-06156bef0ed5",
            "sourceColumn": "IsPositive",
            "summarizeBy": "sum"
          },
          {
            "name": "IsNegative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "72572111-914a-467e-810e-232e45818fca",
            "sourceColumn": "IsNegative",
            "summarizeBy": "sum"
          },
          {
            "name": "OverallSatisfactionRating_Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ae65480b-b60a-4ef9-9c79-1b8cc7a70195",
            "sourceColumn": "OverallSatisfactionRating_Sort",
            "summarizeBy": "none"
          },
          {
            "name": "FakeJoin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5a00009e-9264-427e-aafc-5428d6461965",
            "sourceColumn": "FakeJoin",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "IF('YFM - Your_Feedback_Matters_v3'[Department] = \"DMV\",1,2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2b72bf22-b35f-4ab9-b2d3-149a4d40067a",
            "summarizeBy": "count",
            "type": "calculated"
          }
        ],
        "excludeFromModelRefresh": true,
        "isHidden": true,
        "lineageTag": "376a16b4-ac89-4082-adb7-e18f64bbda5a",
        "partitions": [
          {
            "name": "YFM - Your_Feedback_Matters_v3-abf4aa4d-21ac-4bc9-b0b1-beb5b9632f33",
            "mode": "import",
            "queryGroup": "Your Feedback Matters",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(Feedback_V4_Path & \"data_v3\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform_Your_Feedback_Matters_V3\", each #\"Transform_Your_Feedback_Matters_V3\"([Content])),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Invoke Custom Function1\", {\"Name\", \"Transform_Your_Feedback_Matters_V3\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Other Columns1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Renamed Columns1\", \"Transform_Your_Feedback_Matters_V3\", Table.ColumnNames(#\"Transform_Your_Feedback_Matters_V3\"(#\"Sample V3\"))),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Expanded Table Column1\",{{\"Date of Service:\", \"Date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns2\",{{\"Source.Name\", type text}, {\"Name\", type text}, {\"Do you want to be contacted?\", type text}, {\"Preferred method of contact.\", type text}, {\"Phone\", type text}, {\"Email\", type text}, {\"Date\", type date}, {\"What service did you receive today?\", type text}, {\"Which location did you visit?\", type text}, {\"Were you able to complete your transaction on this visit?\", type text}, {\"If \"\"no\"\", please explain.\", type text}, {\"How would you rate your overall satisfaction with the service you received today?\", type text}, {\"What was the name of the employee who assisted you?\", type text}, {\"What is one thing you liked about your visit?\", type text}, {\"Do you have any suggestions on how we could improve your next visit?\", type text}, {\"If \"\"yes\"\", please explain.\", type text}, {\"Entry Date\", type datetime}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\"),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Removed Duplicates\", \"Index\", 30000, 1),",
                "    ",
                "\t#\"Renamed Columns\" = Table.RenameColumns(#\"Added Index\",{{\"Name\", \"CustomerName\"}, {\"Do you want to be contacted?\", \"ContactWanted\"}, {\"Preferred method of contact.\", \"ContactMethod\"}, {\"What service did you receive today?\", \"ServiceReceived\"}, {\"Which location did you visit?\", \"LocationVisited\"}, {\"Were you able to complete your transaction on this visit?\", \"TransactionCompleted\"}, {\"How would you rate your overall satisfaction with the service you received today?\", \"OverallSatisfactionRating\"}, {\"What was the name of the employee who assisted you?\", \"WhoAssistedYou\"}, {\"What is one thing you liked about your visit?\", \"OneThingLiked\"}, {\"Date\", \"FeedbackDate\"}, {\"Index\", \"FeedbackId\"}, {\"If \"\"no\"\", please explain.\", \"TransactionNotCompletedReason\"}, {\"Do you have any suggestions on how we could improve your next visit?\", \"HasSuggestedImprovement\"}, {\"If \"\"yes\"\", please explain.\", \"SuggestedImprovement\"}}),",
                "    ",
                "\t",
                "\t",
                "\t#\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"FeedbackId\", Int64.Type}}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Changed Type1\", each ([ServiceReceived] = \"Driver's License\" or [ServiceReceived] = \"License plate / Tags/ Title Work\")),",
                "    #\"Added Department\" = Table.AddColumn(#\"Filtered Rows2\", \"Department\", each if [ServiceReceived] = \"Document Recording / Copies\" then \"Recording\" else if [ServiceReceived] = \"Marriage License\" then \"Recording\" else if [ServiceReceived] = \"Passports\" then \"Recording\" else if [ServiceReceived] = \"Driver's License\" then \"DL\" else if [ServiceReceived] = \"License plate / Tags/ Title Work\" then \"DMV\" else if [ServiceReceived] = \"Voter Services\" then \"Elections\" else \"Others\"),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Added Department\",{{\"OverallSatisfactionRating\", Text.Proper, type text}}),",
                "    #\"Add IsPositive\" = Table.AddColumn(#\"Capitalized Each Word\", \"IsPositive\", each if [OverallSatisfactionRating] = \"Very Satisfied\" then 1 else if [OverallSatisfactionRating] = \"Somewhat Satisfied\" then 1 else 0),",
                "    #\"Add IsNegative\" = Table.AddColumn(#\"Add IsPositive\", \"IsNegative\", each if [OverallSatisfactionRating] = \"Not Satisfied At All\" then 1 else if [OverallSatisfactionRating] = \"Not Very Satisfied\" then 1 else 0),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Add IsNegative\",{{\"IsPositive\", Int64.Type}, {\"IsNegative\", Int64.Type}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type2\", \"OverallSatisfactionRating_Sort\", each if [OverallSatisfactionRating] = \"Very Satisfied\" then 1 else if [OverallSatisfactionRating] = \"Somewhat Satisfied\" then 2 else if [OverallSatisfactionRating] = \"Not Very Satisfied\" then 3 else if [OverallSatisfactionRating] = \"Not Satisfied At All\" then 4 else 9),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Conditional Column\", each ([FeedbackDate] <> null)),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Filtered Rows\",{{\"Source.Name\", \"File Name\"}}),",
                "    #\"Removed Duplicates1\" = Table.Distinct(#\"Renamed Columns3\", {\"CustomerName\", \"ContactWanted\", \"ContactMethod\", \"Phone\", \"Email\", \"FeedbackDate\", \"ServiceReceived\", \"LocationVisited\", \"TransactionCompleted\", \"TransactionNotCompletedReason\", \"OverallSatisfactionRating\", \"WhoAssistedYou\", \"OneThingLiked\", \"HasSuggestedImprovement\", \"SuggestedImprovement\", \"Entry Date\", \"FeedbackId\", \"Department\", \"IsPositive\", \"IsNegative\", \"OverallSatisfactionRating_Sort\"}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Removed Duplicates1\", \"FakeJoin\", each 1),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Added Custom1\", each ([Department] = \"DL\" or [Department] = \"DMV\")),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Filtered Rows1\", each [FeedbackDate] > #date(2019, 12, 31) and [FeedbackDate] < #date(Date.Year(DateTime.LocalNow())+1, 1, 1))",
                "in",
                "    #\"Filtered Rows3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "YFM - SearchForTerm",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "YFM"
          }
        ],
        "columns": [
          {
            "name": "WebSearchTerm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b9814d6-11e8-48de-ab27-7cccbfa76063",
            "sourceColumn": "WebSearchTerm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1d632084-7413-442e-be7e-9ae91a59c40f",
        "partitions": [
          {
            "name": "YFM - SearchForTerm-be992f32-49c4-405e-baed-c9fbca8ae227",
            "mode": "import",
            "queryGroup": "Your Feedback Matters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCk9NKkhMT1WK1QGzwXQATCA4swQuUwxje+aVpBblpZaAOf55OZl5QPFYAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [WebSearchTerm = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"WebSearchTerm\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "YFM - StopWords",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "YFM"
          }
        ],
        "columns": [
          {
            "name": "Words",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32d24548-ebd3-4365-af20-468eff545c3b",
            "sourceColumn": "Words",
            "summarizeBy": "none"
          },
          {
            "name": "FakeJoin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52958101-2dd5-466c-b7cc-abdfe9b3789e",
            "sourceColumn": "FakeJoin",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e647eb9d-8291-4d37-9ee6-28deeddd2a5a",
        "partitions": [
          {
            "name": "YFM - StopWords-cfadd4fe-52f4-465a-b2f1-591993921401",
            "mode": "import",
            "queryGroup": "Your Feedback Matters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"VZbBlqUqDEX/pcbvj7p7wNV4ZZWAC/BS/v0DOSdQE7ODEGISgn/+fJmvf//V5ytc\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Words = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Words\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"FakeJoin\", each 1)",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "YFM - Your_Feedback_Matters_v4",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "YFM"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a72e1cc1-9d40-487e-a2fe-0bb1dca66d11",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9cf147be-ae98-4281-ae4a-6820b44bed98",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactWanted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "020fe430-8a23-471e-8ddc-13d44a72a40b",
            "sourceColumn": "ContactWanted",
            "summarizeBy": "none"
          },
          {
            "name": "ContactMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c8c6080d-4cba-4510-84f7-4c515252c9c5",
            "sourceColumn": "ContactMethod",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "af7ff0cb-69d6-4646-a168-aa5b992852ca",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1231d024-1e50-493c-8217-8f5f82b37591",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "FeedbackDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "4d75e004-a7c8-4ea7-a09e-1b8f3094fbc1",
            "sourceColumn": "FeedbackDate",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceReceived",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "42aca5c0-041a-420a-8e2c-5727214a07a9",
            "sourceColumn": "ServiceReceived",
            "summarizeBy": "none"
          },
          {
            "name": "LocationVisited",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9641d6f6-208b-44d5-9ad7-1542a9ba20e7",
            "sourceColumn": "LocationVisited",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3b4e3958-fd0d-4fee-b3df-39d072c8f185",
            "sourceColumn": "TransactionCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionNotCompletedReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "06008c85-1b19-48cc-8fbe-68eb587db934",
            "sourceColumn": "TransactionNotCompletedReason",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSatisfactionRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ffe0ce9b-2b12-42f3-814e-a672bb524d18",
            "sourceColumn": "OverallSatisfactionRating",
            "summarizeBy": "none"
          },
          {
            "name": "WhoAssistedYou",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f18c9fbe-18bc-4f05-a6e3-a04f4607aae0",
            "sourceColumn": "WhoAssistedYou",
            "summarizeBy": "none"
          },
          {
            "name": "HasSuggestedImprovement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8a0c7198-06a3-4745-bea8-b375916d4d44",
            "sourceColumn": "HasSuggestedImprovement",
            "summarizeBy": "none"
          },
          {
            "name": "SuggestedImprovement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "06d7a10a-445b-4a57-9411-3141db919002",
            "sourceColumn": "SuggestedImprovement",
            "summarizeBy": "none"
          },
          {
            "name": "Entry Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0fb9d6cf-0dfb-47f6-a793-ad27ad63e434",
            "sourceColumn": "Entry Date",
            "summarizeBy": "none"
          },
          {
            "name": "ReceiveLandRecords",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6acab646-502a-430c-9f1c-e0ee9a773cf4",
            "sourceColumn": "ReceiveLandRecords",
            "summarizeBy": "none"
          },
          {
            "name": "InformationOnWebsite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a76bc17a-d107-4e34-acbb-227394c949de",
            "sourceColumn": "InformationOnWebsite",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionOtherCompletedReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "543f32c3-206f-4f93-aab1-ebbe7f6e68c8",
            "sourceColumn": "TransactionOtherCompletedReason",
            "summarizeBy": "none"
          },
          {
            "name": "AdditionalComments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a73ec4a6-4866-420d-ab1e-427ca8ee3742",
            "sourceColumn": "AdditionalComments",
            "summarizeBy": "none"
          },
          {
            "name": "OurMissionExperience",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "27d4452e-3579-4bf4-990c-bcf9af7a064d",
            "sourceColumn": "OurMissionExperience",
            "summarizeBy": "none"
          },
          {
            "name": "FeedbackId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88a72d63-2323-4548-97ca-e1bb0aece370",
            "sourceColumn": "FeedbackId",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dea7855-de05-40f1-b2e2-56d885cf557d",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "IsPositive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "caf79990-5702-440c-9258-49825a1b889a",
            "sourceColumn": "IsPositive",
            "summarizeBy": "sum"
          },
          {
            "name": "IsNegative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5eea4ecf-45cc-4c70-9795-fc40e4ccd202",
            "sourceColumn": "IsNegative",
            "summarizeBy": "sum"
          },
          {
            "name": "OverallSatisfactionRating_Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c61dfcac-cde0-422c-b120-20e5af573d83",
            "sourceColumn": "OverallSatisfactionRating_Sort",
            "summarizeBy": "none"
          },
          {
            "name": "FakeJoin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71fbb84c-e765-4b2a-99b3-41b4a55e6bb5",
            "sourceColumn": "FakeJoin",
            "summarizeBy": "none"
          },
          {
            "name": "OneThingLiked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e75758fa-15d8-4d47-8d7e-89ed27d753d9",
            "sourceColumn": "OneThingLiked",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "5b3c0d96-4ca2-4359-b9c2-c2b75d4e6990",
        "partitions": [
          {
            "name": "YFM - Your_Feedback_Matters_v4",
            "mode": "import",
            "queryGroup": "Your Feedback Matters",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(Feedback_V4_Path & \"data_v4\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform_Your_Feedback_Matters_V4\", each #\"Transform_Your_Feedback_Matters_V4\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform_Your_Feedback_Matters_V4\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform_Your_Feedback_Matters_V4\", Table.ColumnNames(#\"Transform_Your_Feedback_Matters_V4\"(#\"Sample File v4\"))),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Expanded Table Column1\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Duplicates\",{",
                "{\"Source.Name\", \"File Name\"}",
                ", {\"Name\", \"CustomerName\"}",
                ", {\"Do you want to be contacted about this visit?\", \"ContactWanted\"}",
                ", {\"Preferred method of contact.\", \"ContactMethod\"}",
                ", {\"Date of Service:\", \"FeedbackDate\"}",
                ", {\"What service did you receive today?\", \"ServiceReceived\"}",
                ", {\"Which location did you visit?\", \"LocationVisited\"}",
                ", {\"Were you able to complete your transaction on this visit?\", \"TransactionCompleted\"}",
                ", {\"If no, what is the reason?\", \"TransactionNotCompletedReason\"}",
                ", {\"How would you rate your overall satisfaction with the service you received?\", \"OverallSatisfactionRating\"}",
                ", {\"What is the name of the employee who assisted you?\", \"WhoAssistedYou\"}",
                ", {\"What did you like about your visit?\", \"OneThingLiked\"}",
                ", {\"Do you have any suggestions on how we can improve your next visit?\", \"HasSuggestedImprovement\"}",
                ", {\"If yes, please explain.\", \"SuggestedImprovement\"}",
                ", {\"How did you receive Land Records  Document Recording/Copies services:\", \"ReceiveLandRecords\"}",
                ", {\"Did you find helpful information about this transaction on Douglas Countys website?\", \"InformationOnWebsite\"}",
                ", {\"Please provide any additional comments about your visit.\", \"AdditionalComments\"}",
                ", {\"Our Mission is to serve all citizens and each other with respect, courtesy, transparency and professionalism  was this your experience today?\"",
                ", \"OurMissionExperience\"}",
                ", {\"If \"\"other\"\", please explain.\", \"TransactionOtherCompletedReason\"}",
                "}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each ([FeedbackDate] <> null)),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Filtered Rows\", \"FeedbackId\", 40000, 1, Int64.Type),",
                "    #\"Capitalized Each Word\" = Table.TransformColumns(#\"Added Index\",{{\"OverallSatisfactionRating\", Text.Proper, type text}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Capitalized Each Word\", each ([ServiceReceived] = \"Driver License\" or [ServiceReceived] = \"Motor Vehicle Services\")),",
                "    #\"Add Department\" = Table.AddColumn(#\"Filtered Rows1\", \"Department\", each if [ServiceReceived] = \"Driver License\" then \"DL\" else if [ServiceReceived] = \"Motor Vehicle Services\" then \"DMV\" else \"Others\"),",
                "    #\"Add IsPositive\" = Table.AddColumn(#\"Add Department\", \"IsPositive\", each if [OverallSatisfactionRating] = \"Very Satisfied\" then 1 else if [OverallSatisfactionRating] = \"Somewhat Satisfied\" then 1 else 0),",
                "    #\"Add IsNegative\" = Table.AddColumn(#\"Add IsPositive\", \"IsNegative\", each if [OverallSatisfactionRating] = \"Not Satisfied At All\" then 1 else if [OverallSatisfactionRating] = \"Not Very Satisfied\" then 1 else 0),",
                "    #\"Add OverallSatisfactionRating_Sort\" = Table.AddColumn(#\"Add IsNegative\", \"OverallSatisfactionRating_Sort\", each if [OverallSatisfactionRating] = \"Very Satisfied\" then 1 else if [OverallSatisfactionRating] = \"Somewhat Satisfied\" then 2 else if [OverallSatisfactionRating] = \"Not Very Satisfied\" then 3 else if [OverallSatisfactionRating] = \"Not Satisfied At All\" then 4 else 9),",
                "    #\"Add FakeJoin\" = Table.AddColumn(#\"Add OverallSatisfactionRating_Sort\", \"FakeJoin\", each 1),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Add FakeJoin\",",
                "{\"File Name\"",
                ", \"CustomerName\"",
                ", \"ContactWanted\"",
                ", \"ContactMethod\"",
                ", \"Phone\"",
                ", \"Email\"",
                ", \"FeedbackDate\"",
                ", \"ServiceReceived\"",
                ", \"LocationVisited\"",
                ", \"TransactionCompleted\"",
                ", \"TransactionNotCompletedReason\"",
                ", \"OverallSatisfactionRating\"",
                ", \"WhoAssistedYou\"",
                ", \"OneThingLiked\", \"HasSuggestedImprovement\", \"SuggestedImprovement\"",
                ", \"Entry Date\", \"FeedbackId\", \"Department\", \"IsPositive\", \"IsNegative\", \"OverallSatisfactionRating_Sort\", \"FakeJoin\"",
                ", \"ReceiveLandRecords\", \"InformationOnWebsite\", \"TransactionOtherCompletedReason\", \"AdditionalComments\", \"OurMissionExperience\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Reordered Columns\",{{\"FeedbackDate\", type date}, {\"IsPositive\", Int64.Type}, {\"IsNegative\", Int64.Type}}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Changed Type\", each [FeedbackDate] > #date(2019, 12, 31) and [FeedbackDate] < #date(Date.Year(DateTime.LocalNow())+1, 1, 1))",
                "in",
                "    #\"Filtered Rows2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "YFM - Your Feedback Matters",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "YFM"
          }
        ],
        "columns": [
          {
            "name": "File Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1b90193-eb70-4740-b664-d1acb3797ac8",
            "sourceColumn": "File Name",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47b1f4f4-da95-43e7-abd2-4d3e90e411db",
            "sourceColumn": "CustomerName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactWanted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c333a56c-84af-4eec-8e09-42012f7c17ad",
            "sourceColumn": "ContactWanted",
            "summarizeBy": "none"
          },
          {
            "name": "ContactMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76b1b6ee-9803-4dbe-b94a-b47a7223d574",
            "sourceColumn": "ContactMethod",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7168fee-1187-42a4-a40b-30c35d8735c9",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c04bcc0a-59af-4481-bb4b-7e47d40d6be1",
            "sourceColumn": "Email",
            "summarizeBy": "none"
          },
          {
            "name": "FeedbackDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "9835a1bd-ca9c-41f7-89b5-9f2a9fa0c517",
            "sourceColumn": "FeedbackDate",
            "summarizeBy": "none"
          },
          {
            "name": "ServiceReceived",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6318be05-60ed-4286-b8c0-ac4899c9c1eb",
            "sourceColumn": "ServiceReceived",
            "summarizeBy": "none"
          },
          {
            "name": "LocationVisited",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab83cebb-1e0c-40a5-bacb-564dfda4bd8c",
            "sourceColumn": "LocationVisited",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2654e4b7-2243-4c3f-a2ed-11d86a45d3f4",
            "sourceColumn": "TransactionCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionNotCompletedReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3bb32528-bfc6-421e-a4d5-d0fe7838738e",
            "sourceColumn": "TransactionNotCompletedReason",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSatisfactionRating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7442c693-deda-42ff-8b64-fcf92cb6cc93",
            "sourceColumn": "OverallSatisfactionRating",
            "summarizeBy": "none"
          },
          {
            "name": "WhoAssistedYou",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "801358e2-becc-4d9b-9a4b-c30fca2981a1",
            "sourceColumn": "WhoAssistedYou",
            "summarizeBy": "none"
          },
          {
            "name": "OneThingLiked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51689c30-2019-4d88-b5a0-c4ffc7dd9dd3",
            "sourceColumn": "OneThingLiked",
            "summarizeBy": "none"
          },
          {
            "name": "HasSuggestedImprovement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07c708c8-0fd7-4c90-a8bc-14655d522baa",
            "sourceColumn": "HasSuggestedImprovement",
            "summarizeBy": "none"
          },
          {
            "name": "SuggestedImprovement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "639b8e26-01fd-48fe-9225-04eb90a5049c",
            "sourceColumn": "SuggestedImprovement",
            "summarizeBy": "none"
          },
          {
            "name": "Entry Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "758c1cfa-7b2a-40e6-af10-cea09385704e",
            "sourceColumn": "Entry Date",
            "summarizeBy": "none"
          },
          {
            "name": "FeedbackId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e58f0337-7a2a-4130-be81-c2cf384b8566",
            "sourceColumn": "FeedbackId",
            "summarizeBy": "count"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e80d9f76-253a-4d89-b865-dd21a51a17e5",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "IsPositive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99f31aed-1439-4fbb-890f-56776b32b07f",
            "sourceColumn": "IsPositive",
            "summarizeBy": "sum"
          },
          {
            "name": "IsNegative",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "375483d4-2608-4f68-9c36-514e8a336a64",
            "sourceColumn": "IsNegative",
            "summarizeBy": "sum"
          },
          {
            "name": "OverallSatisfactionRating_Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38b2795a-17a4-4bfe-a8e2-e31d096d875a",
            "sourceColumn": "OverallSatisfactionRating_Sort",
            "summarizeBy": "none"
          },
          {
            "name": "FakeJoin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51ee2183-0674-478c-998f-6471e92e7f28",
            "sourceColumn": "FakeJoin",
            "summarizeBy": "none"
          },
          {
            "name": "ReceiveLandRecords",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc4e6c18-f6aa-44ee-a344-853759cf8903",
            "sourceColumn": "ReceiveLandRecords",
            "summarizeBy": "none"
          },
          {
            "name": "InformationOnWebsite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40ffdbbc-05d8-48ad-bae8-341e1681cc38",
            "sourceColumn": "InformationOnWebsite",
            "summarizeBy": "none"
          },
          {
            "name": "TransactionOtherCompletedReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d91c36d-724c-4e61-ba4b-ab409dcc77f2",
            "sourceColumn": "TransactionOtherCompletedReason",
            "summarizeBy": "none"
          },
          {
            "name": "AdditionalComments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b70c3ea4-49d7-49b8-bf85-34a80fa8ddc4",
            "sourceColumn": "AdditionalComments",
            "summarizeBy": "none"
          },
          {
            "name": "OurMissionExperience",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75897389-5edd-46cd-b55c-7f480d8e8cee",
            "sourceColumn": "OurMissionExperience",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('YFM - Your Feedback Matters'[Department] = \"DMV\",1,2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8e25a7b7-437d-43a9-8240-7aa17c8fb680",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "823f1e7d-d75e-48be-9ee4-00dcc518e264",
            "sourceColumn": "Version",
            "summarizeBy": "none"
          },
          {
            "name": "YrMth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "(YEAR('YFM - Your Feedback Matters'[FeedbackDate]) * 100) + MONTH('YFM - Your Feedback Matters'[FeedbackDate])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d9a3bab7-b3f9-4b16-9e75-bb88e79e5a54",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "93abc487-e35d-4c33-9934-b84cafdf380b",
        "partitions": [
          {
            "name": "YFM - Your Feedback Matters",
            "mode": "import",
            "queryGroup": "Your Feedback Matters",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({#\"YFM - Your_Feedback_Matters_v3\", #\"YFM - Your_Feedback_Matters_v4\"}),",
                "    #\"Added Custom\" = Table.AddColumn(Source, \"Version\", each 0)",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pay Type JDE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Pay Type"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ba94a8aa-eba7-4c20-90ad-a69c7c97cee9",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Address Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f7dd73b-6ac2-4f70-81a0-77970be4b6bd",
            "sourceColumn": "Address Number",
            "summarizeBy": "none"
          },
          {
            "name": "Alpha Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d4b6500c-aa07-46be-84af-9d8643ca86e2",
            "sourceColumn": "Alpha Name",
            "summarizeBy": "none"
          },
          {
            "name": "Check Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "16691217-5348-4398-9b80-079062241e69",
            "sourceColumn": "Check Date",
            "summarizeBy": "none"
          },
          {
            "name": "Home Business Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "df5198c1-04e8-4e39-bd20-bc947654ea2d",
            "sourceColumn": "Home Business Unit",
            "summarizeBy": "none"
          },
          {
            "name": "OrgId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "IF('Pay Type JDE'[Home Business Unit] = \"12600\",2,1)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4a04352f-d40c-4a30-bc9e-4d4396a02158",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Email Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "708d8c34-5975-4450-bbc3-b52b606ca4b2",
            "sourceColumn": "Email Address",
            "summarizeBy": "none"
          },
          {
            "name": "Co ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "40fb3a81-44d3-4c73-9967-9babdf717da2",
            "sourceColumn": "Co ",
            "summarizeBy": "none"
          },
          {
            "name": "Dept ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "611f6519-b880-427e-89cf-27e5898f92e7",
            "sourceColumn": "Dept ",
            "summarizeBy": "none"
          },
          {
            "name": "Pay Status Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "658ff169-e12c-4733-b6f1-b154275d23d1",
            "sourceColumn": "Pay Status Code",
            "summarizeBy": "none"
          },
          {
            "name": "Hours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "d50af00e-3eb8-4882-8c57-447d7e67e4bc",
            "sourceColumn": "Hours",
            "summarizeBy": "sum"
          },
          {
            "name": "PDBA Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "35740ee1-3967-4cdc-b2fe-b3ace648b52b",
            "sourceColumn": "PDBA Code",
            "summarizeBy": "none"
          },
          {
            "name": "PDBA Code Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "874fcfa0-2508-4271-a1c2-5c7647bafea2",
            "sourceColumn": "PDBA Code Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Home Business Unit Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "32afa7f0-1961-4c1d-97dc-d725d4dfb8ea",
            "sourceColumn": "Home Business Unit Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Pay Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "switch(true",
              "    , 'Pay Type JDE'[Pay Status Code] = \"0\", \"Active\"",
              "    , 'Pay Type JDE'[Pay Status Code] = \"9\", \"Terminated/Last Check\"",
              "    , 'Pay Type JDE'[Pay Status Code] = \"I\", \"Inactive\"",
              "    , 'Pay Type JDE'[Pay Status Code] = \"T\", \"Terminated\"",
              "    , \"Unknown Status\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "eb3cbd5b-0d04-4486-bdb3-10ce12c6b753",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "043ef930-6af0-4100-ad95-025c239c486d",
        "partitions": [
          {
            "name": "Pay Type JDE",
            "mode": "import",
            "queryGroup": "Personal Time",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/consumer/HourlyPayReport/\"),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(Source, \"Transform File\", each #\"Transform Personal File\"([Content])),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Invoke Custom Function1\", {\"Name\", \"Transform File\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Other Columns1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Expanded Transform File\" = Table.ExpandTableColumn(#\"Renamed Columns1\", \"Transform File\", {\"Address Number\", \"Alpha Name\", \"Check Date\", \"Email Address\", \"PDBA Code\", \"PDBA Code Desc\", \"Co \", \"Home Business Unit\", \"Home Business Unit Desc\", \"Dept \", \"Pay St\", \"Hours \"}, {\"Address Number\", \"Alpha Name\", \"Check Date\", \"Email Address\", \"PDBA Code\", \"PDBA Code Desc\", \"Co \", \"Home Business Unit\", \"Home Business Unit Desc\", \"Dept \", \"Pay St\", \"Hours \"}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Expanded Transform File\",{{\"Home Business Unit\", Text.Trim, type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Trimmed Text\",{{\"Pay St\", \"Pay Status Code\"}, {\"Hours \", \"Hours\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Drives - Title Application Errors Castle Rock",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CaseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a50ba39-5b25-48fe-a1cc-9007f9482f6c",
            "sourceColumn": "CaseId",
            "summarizeBy": "none"
          },
          {
            "name": "TitleNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c13780d2-19c9-49b9-92dc-ee4467ea50e8",
            "sourceColumn": "TitleNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Jurisdiction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b4861c87-dc04-4000-be8e-7ee9f42b3133",
            "sourceColumn": "Jurisdiction",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentStage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "75a44661-55ac-4756-a797-7d0c775c7071",
            "sourceColumn": "CurrentStage",
            "summarizeBy": "none"
          },
          {
            "name": "OriginalUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d7ab354f-ef0a-48c1-ac4b-2264ec611b1e",
            "sourceColumn": "OriginalUser",
            "summarizeBy": "none"
          },
          {
            "name": "SubJurisdiction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b82a454a-6716-4e09-8512-dc97b98f4b11",
            "sourceColumn": "SubJurisdiction",
            "summarizeBy": "none"
          },
          {
            "name": "Office",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d77d5106-073e-4f98-bbb3-e902658e4414",
            "sourceColumn": "Office",
            "summarizeBy": "none"
          },
          {
            "name": "OwnershipDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7a6f0677-7847-40bf-af83-9008bb13b247",
            "sourceColumn": "OwnershipDocument",
            "summarizeBy": "none"
          },
          {
            "name": "RejectCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9c12ec43-4f3e-4ef7-b925-16aab348af95",
            "sourceColumn": "RejectCategory",
            "summarizeBy": "none"
          },
          {
            "name": "RejectReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9bcbf35f-daa2-4697-848e-8d521855d976",
            "sourceColumn": "RejectReason",
            "summarizeBy": "none"
          },
          {
            "name": "FileName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "dd761186-d6e7-42ba-9092-4a4e7347efb3",
            "sourceColumn": "FileName",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "37297125-a8a0-420d-b2a1-5cab78b71a21",
        "partitions": [
          {
            "name": "Drives - Title Application Errors Castle Rock",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/drives/Title Application Errors/Castle Rock Office/\"),",
                "    #\"pq\" = Source{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Imported Parquet\", each ([Office] = \"Douglas County - Castle Rock\"))",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Drives - Title Application Errors Highlands Ranch",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Drives"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CaseId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d293e14b-1e47-4ef4-ace5-08fcf1c16800",
            "sourceColumn": "CaseId",
            "summarizeBy": "none"
          },
          {
            "name": "TitleNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0b28ed6f-b4b4-426d-8e22-519475daa040",
            "sourceColumn": "TitleNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Jurisdiction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c9548896-5d29-4f02-b393-287bf40a53a9",
            "sourceColumn": "Jurisdiction",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentStage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "49d09c2e-5e21-441b-9f18-3b5f02f92a2e",
            "sourceColumn": "CurrentStage",
            "summarizeBy": "none"
          },
          {
            "name": "OriginalUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9f243ae7-c8fb-4cc7-9c84-b5f6a727c8c9",
            "sourceColumn": "OriginalUser",
            "summarizeBy": "none"
          },
          {
            "name": "SubJurisdiction",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "16900395-7d67-4478-aa89-b2646bea26b5",
            "sourceColumn": "SubJurisdiction",
            "summarizeBy": "none"
          },
          {
            "name": "Office",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "88175205-bcfa-491f-9a56-b484969ec32f",
            "sourceColumn": "Office",
            "summarizeBy": "none"
          },
          {
            "name": "OwnershipDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f6a21f4-9bdf-4097-9f0a-e47d87c53413",
            "sourceColumn": "OwnershipDocument",
            "summarizeBy": "none"
          },
          {
            "name": "RejectCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "87a59652-b62f-4cab-b26e-c0cca1529dd5",
            "sourceColumn": "RejectCategory",
            "summarizeBy": "none"
          },
          {
            "name": "RejectReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "befba34d-03e3-4464-a8c7-69c0dd946b09",
            "sourceColumn": "RejectReason",
            "summarizeBy": "none"
          },
          {
            "name": "FileName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a71a9931-2b5d-4b1b-8c76-1e15a7f14e7a",
            "sourceColumn": "FileName",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "b28744d9-4d76-452c-8df5-e6190c5de9b8",
        "partitions": [
          {
            "name": "Drives - Title Application Errors Highlands Ranch",
            "mode": "import",
            "queryGroup": "Drives",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/drives/Title%20Application%20Errors/Highlands%20Ranch%20Office/\"),",
                "    #\"pq\" = Source{0}[Content],",
                "    #\"Imported Parquet\" = Parquet.Document(#\"pq\"),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Imported Parquet\", each ([Office] = \"Douglas County - Highlands Ranch\"))",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - Physical Mail Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Tables.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ced16cad-9b6a-4f7f-a73f-d68a29eb0a23",
            "sourceColumn": "Tables.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "12c67f00-c3ae-4679-83b8-26b9b82b18dd",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7bab0f54-24fc-478b-8466-dd69e3efe0f3",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b8e1bdf5-11cd-4f6b-8ec4-00e6c2d97590",
            "sourceColumn": "Column3",
            "summarizeBy": "sum"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dcb0ff26-35bf-40a0-bb00-b882f46b9b3f",
            "sourceColumn": "Column4",
            "summarizeBy": "sum"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cf6884d3-f179-4637-9be8-ae13eec7cda7",
            "sourceColumn": "Column5",
            "summarizeBy": "sum"
          },
          {
            "name": "Column6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "661579ed-9e58-4378-b6fc-21f99b1d999f",
            "sourceColumn": "Column6",
            "summarizeBy": "sum"
          },
          {
            "name": "Column7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "69ea5559-b6a6-4e71-bf64-10dc2915159a",
            "sourceColumn": "Column7",
            "summarizeBy": "sum"
          },
          {
            "name": "Column8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4beb5939-3a20-4ae8-b43d-25c3946a548f",
            "sourceColumn": "Column8",
            "summarizeBy": "sum"
          },
          {
            "name": "Column9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "888fe433-ca78-48af-a980-6eb27e48a607",
            "sourceColumn": "Column9",
            "summarizeBy": "sum"
          },
          {
            "name": "Column10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4c8d7d9c-c9c1-4a7b-923b-b988ed007a66",
            "sourceColumn": "Column10",
            "summarizeBy": "sum"
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8546e564-b962-4a3e-8295-62716b315eeb",
            "sourceColumn": "Column11",
            "summarizeBy": "sum"
          },
          {
            "name": "Column12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "072ba585-8317-4974-bf2b-322d04349b67",
            "sourceColumn": "Column12",
            "summarizeBy": "sum"
          },
          {
            "name": "Column13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f8e4f488-a5cf-4ab8-858a-ca85c19025ce",
            "sourceColumn": "Column13",
            "summarizeBy": "sum"
          },
          {
            "name": "Column14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "df9b73c8-3cf2-4fda-af4f-8194b18c1cfb",
            "sourceColumn": "Column14",
            "summarizeBy": "sum"
          },
          {
            "name": "Column15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ce648542-d010-4f41-8599-c740d7f32cd8",
            "sourceColumn": "Column15",
            "summarizeBy": "sum"
          },
          {
            "name": "Column16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "630e214f-7c61-4376-bad7-4f7ef31e3ed6",
            "sourceColumn": "Column16",
            "summarizeBy": "sum"
          },
          {
            "name": "Column17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dd4a7420-7f04-4890-b7a7-8a985686eefe",
            "sourceColumn": "Column17",
            "summarizeBy": "sum"
          },
          {
            "name": "Column18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f89124e9-8d25-48f7-bc36-4f4ec0858890",
            "sourceColumn": "Column18",
            "summarizeBy": "sum"
          },
          {
            "name": "Column19",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "83bd1b90-b43d-47be-b7e4-11ac862e2f3b",
            "sourceColumn": "Column19",
            "summarizeBy": "sum"
          },
          {
            "name": "Column20",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "86a360d7-13b8-4b00-977e-ad234dc7af79",
            "sourceColumn": "Column20",
            "summarizeBy": "sum"
          },
          {
            "name": "Column21",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fc085dd1-f3ba-477a-9162-1996055a1111",
            "sourceColumn": "Column21",
            "summarizeBy": "sum"
          },
          {
            "name": "Column22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8a928c78-2198-4907-aa8e-d08598240b83",
            "sourceColumn": "Column22",
            "summarizeBy": "sum"
          },
          {
            "name": "Column23",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e593dbe9-bedd-4b94-8c39-9529555bb453",
            "sourceColumn": "Column23",
            "summarizeBy": "sum"
          },
          {
            "name": "Column24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e4c09a59-8b7c-47e8-bdeb-2d1cdf9fafb9",
            "sourceColumn": "Column24",
            "summarizeBy": "sum"
          },
          {
            "name": "Column25",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a9f513d7-769d-49e5-9187-e6a3dec3159e",
            "sourceColumn": "Column25",
            "summarizeBy": "sum"
          },
          {
            "name": "Column26",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "38dc19de-a671-4089-a538-020b471d330d",
            "sourceColumn": "Column26",
            "summarizeBy": "sum"
          },
          {
            "name": "Column27",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5a2fcca9-c484-4388-a421-28919b2ac446",
            "sourceColumn": "Column27",
            "summarizeBy": "sum"
          },
          {
            "name": "Column28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "472f61e5-59a5-4fda-bab2-e68d4cff9e3b",
            "sourceColumn": "Column28",
            "summarizeBy": "sum"
          },
          {
            "name": "Column29",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "60fba59d-e839-4bca-96c2-66021a176d1a",
            "sourceColumn": "Column29",
            "summarizeBy": "sum"
          },
          {
            "name": "Column30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d264248b-826e-4f7b-837c-abd36e67c6b3",
            "sourceColumn": "Column30",
            "summarizeBy": "sum"
          },
          {
            "name": "Column31",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f6b1022c-7b47-4003-9aa4-c702a25c4d41",
            "sourceColumn": "Column31",
            "summarizeBy": "sum"
          },
          {
            "name": "Column32",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3d215815-babd-4000-b902-b6ade74b32e3",
            "sourceColumn": "Column32",
            "summarizeBy": "sum"
          },
          {
            "name": "Column33",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "27e5400c-179b-4fe8-852c-1718cec5eb0e",
            "sourceColumn": "Column33",
            "summarizeBy": "sum"
          },
          {
            "name": "Column34",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cdb42e4d-3086-4299-897d-6e0960b1c1df",
            "sourceColumn": "Column34",
            "summarizeBy": "sum"
          },
          {
            "name": "Column35",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "95938dc1-3873-471f-831d-4030b48e32b4",
            "sourceColumn": "Column35",
            "summarizeBy": "sum"
          },
          {
            "name": "Column36",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "aa50f643-c0bc-4549-8818-24285ec7bc20",
            "sourceColumn": "Column36",
            "summarizeBy": "none"
          },
          {
            "name": "File.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b0c8fd5-1023-4ff4-8c89-d0ae86a11bf0",
            "sourceColumn": "File.Name",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "1e1321e6-6b11-4a85-81fe-246883572ef7",
        "partitions": [
          {
            "name": "Staff Stats - Physical Mail Data",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - Staff Sheets\",",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Name\", \"File.Name\"}}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Renamed Columns\", \"Transform Staff Stats Sheet\", each #\"Transform Staff Stats Sheet 2022\"([Tables.Data], [Tables.Name])),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Invoked Custom Function\",{\"Tables.Data\"}),",
                "    #\"Expanded Transform Staff Stats Sheet\" = Table.ExpandTableColumn(#\"Removed Columns1\", \"Transform Staff Stats Sheet\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Expanded Transform Staff Stats Sheet\", each ([Column1] <> null and [Column1] <> \"End\" and [Column1] <> \"END \" and [Column1] <> \"FINAL\" and [Column1] <> \"FINAL \" and [Column1] <> \"TOTALS\" and [Column1] <> \"Blank\")),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Filtered Rows\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Errors\",{{\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}, {\"Column25\", type text}, {\"Column26\", type text}, {\"Column27\", type text}, {\"Column28\", type text}, {\"Column29\", type text}, {\"Column30\", type text}, {\"Column31\", type text}, {\"Column32\", type text}, {\"Column33\", type text}, {\"Column34\", type text}, {\"Column35\", type text}, {\"Column36\", type text}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type\", \"MergedValues\", each Text.Combine({Text.From([Column3], \"en-US\"), Text.From([Column4], \"en-US\"), Text.From([Column5], \"en-US\"), Text.From([Column6], \"en-US\"), Text.From([Column7], \"en-US\"), Text.From([Column8], \"en-US\"), Text.From([Column9], \"en-US\"), Text.From([Column10], \"en-US\"), Text.From([Column11], \"en-US\"), Text.From([Column12], \"en-US\"), Text.From([Column13], \"en-US\"), Text.From([Column14], \"en-US\"), Text.From([Column15], \"en-US\"), Text.From([Column16], \"en-US\"), Text.From([Column17], \"en-US\"), Text.From([Column18], \"en-US\"), Text.From([Column19], \"en-US\"), Text.From([Column20], \"en-US\"), Text.From([Column21], \"en-US\"), Text.From([Column22], \"en-US\"), Text.From([Column23], \"en-US\"), Text.From([Column24], \"en-US\"), Text.From([Column25], \"en-US\"), Text.From([Column26], \"en-US\"), Text.From([Column27], \"en-US\"), Text.From([Column28], \"en-US\"), Text.From([Column29], \"en-US\"), Text.From([Column30], \"en-US\"), Text.From([Column31], \"en-US\"), Text.From([Column32], \"en-US\"), Text.From([Column33], \"en-US\"), Text.From([Column34], \"en-US\"), Text.From([Column35], \"en-US\"), [Column36]}, \"-\"), type text),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Inserted Merged Column\", each ([MergedValues] <> \"\" and [MergedValues] <> \" \" and [MergedValues] <> \"  \" and [MergedValues] <> \" - \")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"MergedValues\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Column35\", Int64.Type}, {\"Column34\", Int64.Type}, {\"Column33\", Int64.Type}, {\"Column32\", Int64.Type}, {\"Column31\", Int64.Type}, {\"Column30\", Int64.Type}, {\"Column29\", Int64.Type}, {\"Column28\", Int64.Type}, {\"Column27\", Int64.Type}, {\"Column26\", Int64.Type}, {\"Column25\", Int64.Type}, {\"Column24\", Int64.Type}, {\"Column23\", Int64.Type}, {\"Column22\", Int64.Type}, {\"Column21\", Int64.Type}, {\"Column20\", Int64.Type}, {\"Column19\", Int64.Type}, {\"Column18\", Int64.Type}, {\"Column17\", Int64.Type}, {\"Column16\", Int64.Type}, {\"Column15\", Int64.Type}, {\"Column14\", Int64.Type}, {\"Column13\", Int64.Type}, {\"Column12\", Int64.Type}, {\"Column11\", Int64.Type}, {\"Column10\", Int64.Type}, {\"Column9\", Int64.Type}, {\"Column8\", Int64.Type}, {\"Column7\", Int64.Type}, {\"Column6\", Int64.Type}, {\"Column5\", Int64.Type}, {\"Column4\", Int64.Type}, {\"Column3\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pay Type JDE Latest Status",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Pay Type"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Email Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "70319ddc-11ea-4333-83a2-e5b8d66c7bc0",
            "sourceColumn": "Email Address",
            "summarizeBy": "none"
          },
          {
            "name": "MaxCheckDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "9d8773c8-1c81-46d0-aff9-83017f89ebcc",
            "sourceColumn": "MaxCheckDate",
            "summarizeBy": "none"
          },
          {
            "name": "MaxStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d7550d01-898f-4fca-bb8c-36a2c5551ca2",
            "sourceColumn": "MaxStatus",
            "summarizeBy": "none"
          },
          {
            "name": "PayStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "673426d2-a306-424d-9a82-75981daaf977",
            "sourceColumn": "PayStatus",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "3aa329e0-2581-40e3-bd43-6c3055cc00b2",
        "partitions": [
          {
            "name": "Pay Type JDE Latest Status",
            "mode": "import",
            "queryGroup": "Personal Time",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/consumer/HourlyPayReport/\"),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(Source, \"Transform File\", each #\"Transform Personal File\"([Content])),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Invoke Custom Function1\", {\"Name\", \"Transform File\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Other Columns1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Expanded Transform File\" = Table.ExpandTableColumn(#\"Renamed Columns1\", \"Transform File\", {\"Address Number\", \"Alpha Name\", \"Check Date\", \"Email Address\", \"PDBA Code\", \"PDBA Code Desc\", \"Co \", \"Home Business Unit\", \"Home Business Unit Desc\", \"Dept \", \"Pay St\", \"Hours \"}, {\"Address Number\", \"Alpha Name\", \"Check Date\", \"Email Address\", \"PDBA Code\", \"PDBA Code Desc\", \"Co \", \"Home Business Unit\", \"Home Business Unit Desc\", \"Dept \", \"Pay St\", \"Hours \"}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Expanded Transform File\",{{\"Home Business Unit\", Text.Trim, type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Trimmed Text\",{{\"Pay St\", \"Pay Status Code\"}, {\"Hours \", \"Hours\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Source.Name\", \"Address Number\", \"Alpha Name\", \"PDBA Code\", \"PDBA Code Desc\", \"Co \", \"Home Business Unit\", \"Home Business Unit Desc\", \"Dept \", \"Hours\"}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Removed Columns\", {\"Email Address\"}, {{\"MaxCheckDate\", each List.Max([Check Date]), type date}, {\"MaxStatus\", each List.Max([Pay Status Code]), type text}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Grouped Rows\",{{\"Email Address\", Order.Ascending}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Sorted Rows\", \"PayStatus\", each if [MaxStatus] = \"0\" then \"Active\" else if [MaxStatus] = \"9\" then \"Terminated/Last Check\" else if [MaxStatus] = \"I\" then \"Inactive\" else if [MaxStatus] = \"T\" then \"Terminated\" else \"Unknown Status\")",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DC - Closure",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "DC"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b895b204-4f8a-4f3f-ab16-e126574abe52",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "13f9738c-e8f1-401b-8416-ee3192e326c6",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "isHidden": true,
            "lineageTag": "4a7efacc-dd04-4feb-bb2c-5a89ae234bb4",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "(((Year('DC - Closure'[Date]) * 100) + MONTH('DC - Closure'[Date])) * 100) + Day('DC - Closure'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4964cdc2-b009-4600-b750-57792d75fadd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "e7f65294-7def-4c2f-a2b9-d8742a015550",
        "partitions": [
          {
            "name": "DC - Closure",
            "mode": "import",
            "queryGroup": "DC",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SQLServerName, SQLServerDB, [CreateNavigationProperties=false]),",
                "    mdm_MVDCClosure = Source{[Schema=\"mdm\",Item=\"MVDCClosure\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(mdm_MVDCClosure,{\"Name\", \"Code\", \"Date\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - File Table List",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "46f21ab2-6065-4d8f-aef6-b21458e3b153",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tables.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "faf470a4-2386-4631-ba1a-e68538acd787",
            "sourceColumn": "Tables.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tables.Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "af1e7cf1-19d6-4545-b91d-d444652e6308",
            "sourceColumn": "Tables.Data",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "1e94be83-94d4-4f31-805a-b2853f904103",
        "partitions": [
          {
            "name": "Staff Stats - File Table List",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/staffstats/\"),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Content\", \"Name\"}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Removed Other Columns\", each ([Name] <> \"Staff Stats 2021.xlsx\")),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows2\", \"Tables\", each Excel.Workbook([Content])),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom\",{\"Content\"}),",
                "    #\"Expanded Tables\" = Table.ExpandTableColumn(#\"Removed Columns\", \"Tables\", {\"Name\", \"Data\", \"Item\", \"Kind\", \"Hidden\"}, {\"Tables.Name\", \"Tables.Data\", \"Tables.Item\", \"Tables.Kind\", \"Tables.Hidden\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded Tables\",{\"Tables.Item\", \"Tables.Kind\", \"Tables.Hidden\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - Salvage Rejects",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7254ab1a-7521-4e27-8066-e4a3492e3ac5",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tables.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3907e6a2-fe03-47e8-9629-3bd42e67d5e3",
            "sourceColumn": "Tables.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Date Recieved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "4d3f02f0-b167-4bde-9323-0ae32e0f93df",
            "sourceColumn": "Date Recieved",
            "summarizeBy": "none"
          },
          {
            "name": "Date Rejected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "5fcdde28-dc0f-4462-b555-f3f6c07877ef",
            "sourceColumn": "Date Rejected",
            "summarizeBy": "none"
          },
          {
            "name": "Reject #",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01da2d07-2009-4f3c-9ab3-590de1c55a69",
            "sourceColumn": "Reject #",
            "summarizeBy": "none"
          },
          {
            "name": "Letter ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45e76408-63c7-465f-8658-44a8a8d63ed3",
            "sourceColumn": "Letter ID",
            "summarizeBy": "none"
          },
          {
            "name": "Document",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31fcd121-b164-4816-a430-e30474d160b6",
            "sourceColumn": "Document",
            "summarizeBy": "none"
          },
          {
            "name": "Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1ee32cf-f72d-4557-b916-f6f3756d2978",
            "sourceColumn": "Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f92e3bf3-2338-45f6-9b9f-75c6fdced429",
            "sourceColumn": "Comments",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90d7edf5-e9d9-41dd-92eb-39e62acd5043",
        "partitions": [
          {
            "name": "Staff Stats - Salvage Rejects",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - File Table List\",",
                "    #\"Filtered Rows1\" = Table.SelectRows(Source, each ([Tables.Name] = \"Salvage Rejects\")),",
                "    #\"Expanded Tables.Data\" = Table.ExpandTableColumn(#\"Filtered Rows1\", \"Tables.Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\"}, {\"Date Recieved\", \"Date Rejected\", \"Reject #\", \"Letter ID\", \"Document\", \"Reason\", \"Comments\"}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Expanded Tables.Data\", each ([Date Recieved] <> null and [Date Recieved] <> \"Date Recieved\")),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows3\",{{\"Date Recieved\", type date}, {\"Date Rejected\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Audit and UAT Stats Sheets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Audit and UAT Stats"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1c2af70a-f0f0-401e-a64e-264d02728254",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Workbook_Content.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4b866293-dcc3-4311-b238-c23fd4977d28",
            "sourceColumn": "Workbook_Content.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Workbook_Content.Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "551459fc-4d1c-455e-8d56-e9e97ce801e4",
            "sourceColumn": "Workbook_Content.Data",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "c63d2883-5c14-4d7d-9b6a-a07ccfaa6601",
        "partitions": [
          {
            "name": "Audit and UAT Stats Sheets",
            "mode": "import",
            "queryGroup": "Audit and UAT Stats",
            "source": {
              "expression": [
                "let",
                "    Source = AzureStorage.DataLake(Datalake & \"/datalake/\" & datapath & \"consumer/AuditAndUATStats/\"),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Content\", \"Name\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Removed Other Columns\", \"Workbook_Content\", each Excel.Workbook([Content])),",
                "    #\"Expanded Workbook_Content\" = Table.ExpandTableColumn(#\"Added Custom\", \"Workbook_Content\", {\"Name\", \"Data\", \"Item\", \"Kind\", \"Hidden\"}, {\"Workbook_Content.Name\", \"Workbook_Content.Data\", \"Workbook_Content.Item\", \"Workbook_Content.Kind\", \"Workbook_Content.Hidden\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Expanded Workbook_Content\", each Text.EndsWith([Workbook_Content.Item], \"Staff\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Workbook_Content.Item\", \"Workbook_Content.Kind\", \"Workbook_Content.Hidden\", \"Content\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Audit and UAT Stats",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Audit and UAT Stats"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "FileName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5275654-3abe-4561-8026-0ff56d0d651c",
            "sourceColumn": "FileName",
            "summarizeBy": "none"
          },
          {
            "name": "Sheet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f927c16e-c028-4135-ac47-97a07c218024",
            "sourceColumn": "Sheet",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "858d00f5-e4a0-4e98-bfc7-33736ee57c5e",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Staff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "48aac4c0-3792-42a9-bc4e-47ecd57be844",
            "sourceColumn": "Staff",
            "summarizeBy": "none"
          },
          {
            "name": "DRIVES Reports - # Uploaded to Azure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "69c0f1cd-8dcc-4572-9874-fdc3576d0504",
            "sourceColumn": "DRIVES Reports - # Uploaded to Azure",
            "summarizeBy": "sum"
          },
          {
            "name": "Notes - Additional Tasks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc63eb27-59d5-4606-8842-0fad586a5de4",
            "sourceColumn": "Notes - Additional Tasks",
            "summarizeBy": "none"
          },
          {
            "name": "Manager Audits - Approved",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80d4638a-71bf-4c0f-93dc-307f6a27705d",
            "sourceColumn": "Manager Audits - Approved",
            "summarizeBy": "sum"
          },
          {
            "name": "Manager Audits - Corrected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f65030b3-cffa-480b-9a84-6b215dac9ab3",
            "sourceColumn": "Manager Audits - Corrected",
            "summarizeBy": "sum"
          },
          {
            "name": "Manager Audits - Rejected",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c489581d-5c04-4afb-83e9-d32ce98ad6c6",
            "sourceColumn": "Manager Audits - Rejected",
            "summarizeBy": "sum"
          },
          {
            "name": "Manager Audits - # State Reject Reviews Submitted ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ecc6a242-47ad-44c3-a875-6f203fdca45a",
            "sourceColumn": "Manager Audits - # State Reject Reviews Submitted ",
            "summarizeBy": "sum"
          },
          {
            "name": "Manager Audits - # Overturned State Rejects",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c4a36c1-702c-4fe2-a0e4-e633f8cc9a83",
            "sourceColumn": "Manager Audits - # Overturned State Rejects",
            "summarizeBy": "sum"
          },
          {
            "name": "Manager Audits - Time on Audits (min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7f17ad5-25ff-4f2a-9e5e-32cdf77d10d8",
            "sourceColumn": "Manager Audits - Time on Audits (min)",
            "summarizeBy": "sum"
          },
          {
            "name": "User Acceptence Testing (SQR) - # New SQRs started",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "422e1731-b9b4-48e5-8a59-896d66a11719",
            "sourceColumn": "User Acceptence Testing (SQR) - # New SQRs started",
            "summarizeBy": "sum"
          },
          {
            "name": "User Acceptence Testing (SQR) -  # of SQR Scenerios",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f038dfe1-87f7-4019-aaf1-417281838fe5",
            "sourceColumn": "User Acceptence Testing (SQR) -  # of SQR Scenerios",
            "summarizeBy": "sum"
          },
          {
            "name": "User Acceptence Testing (SQR) - Time on UAT (Min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1bad093f-b07d-4fe7-b6ef-00eb733b6ac4",
            "sourceColumn": "User Acceptence Testing (SQR) - Time on UAT (Min)",
            "summarizeBy": "sum"
          },
          {
            "name": "DRIVES Reports - Time on Reports (Min)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2bbdcc0-0bda-4cf6-b12a-7a5a2e5162b2",
            "sourceColumn": "DRIVES Reports - Time on Reports (Min)",
            "summarizeBy": "sum"
          },
          {
            "name": "Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9515cbc8-24ec-4ee3-b252-8f5599b93279",
            "sourceColumn": "Version",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "716a4dd4-63ef-4b17-b7f9-a05c746cf254",
        "partitions": [
          {
            "name": "Audit and UAT Stats",
            "mode": "import",
            "queryGroup": "Audit and UAT Stats",
            "source": {
              "expression": [
                "let",
                "    Source = Table.Combine({#\"Audit and UAT Stats Headers\", #\"Audit and UAT Stats Data\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"FileName\", type text}, {\"Sheet\", type text}, {\"Date\", type date}, {\"Staff\", type text}, {\"Manager Audits - Approved\", Int64.Type}, {\"Manager Audits - Corrected\", Int64.Type}, {\"Manager Audits - Rejected\", Int64.Type}, {\"Manager Audits - # State Reject Reviews Submitted \", Int64.Type}, {\"Manager Audits - # Overturned State Rejects\", Int64.Type}, {\"Manager Audits - Time on Audits (min)\", Int64.Type}, {\"User Acceptence Testing (SQR) - # New SQRs started\", Int64.Type}, {\"User Acceptence Testing (SQR) -  # of SQR Scenerios\", Int64.Type}, {\"User Acceptence Testing (SQR) - Time on UAT (Min)\", Int64.Type}, {\"DRIVES Reports - # Uploaded to Azure\", Int64.Type}, {\"DRIVES Reports - Time on Reports (Min)\", Int64.Type}, {\"Notes - Additional Tasks\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Version\", each 0)",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Audit and UAT Stats Headers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Audit and UAT Stats"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3731e939-6103-48c9-8ae6-0bfb48c8619c",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ce6e7139-82bd-46fd-90fd-b766690f4e2c",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ddb3349d-7c46-46da-a0d5-d3fad73262be",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "be36f0f4-ae46-4c0c-b141-5dcaa2927c8c",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "660d52fd-c1ed-40fb-abca-49548b4d3547",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          },
          {
            "name": "Column6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2226b1be-e018-4847-9b9b-5279d6f69be0",
            "sourceColumn": "Column6",
            "summarizeBy": "none"
          },
          {
            "name": "Column7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cfdc4358-f025-40bc-aca5-4177c770e342",
            "sourceColumn": "Column7",
            "summarizeBy": "none"
          },
          {
            "name": "Column8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e07fae8a-7711-450a-9666-2160e57bdb77",
            "sourceColumn": "Column8",
            "summarizeBy": "none"
          },
          {
            "name": "Column9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1774ff50-503a-4d3e-883a-40637c8a2fc0",
            "sourceColumn": "Column9",
            "summarizeBy": "none"
          },
          {
            "name": "Column10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7021f2b8-2b6e-4843-b6d1-a54d5bc1d79e",
            "sourceColumn": "Column10",
            "summarizeBy": "none"
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6d0e63e9-657f-459b-ae0e-4f7f1412f4df",
            "sourceColumn": "Column11",
            "summarizeBy": "none"
          },
          {
            "name": "Column12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cc8d54b4-b12e-495b-bfa8-971b143315ea",
            "sourceColumn": "Column12",
            "summarizeBy": "none"
          },
          {
            "name": "Column13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "99cb9f23-a16a-459a-a8c3-1a3965e25da7",
            "sourceColumn": "Column13",
            "summarizeBy": "none"
          },
          {
            "name": "Column14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2d70f960-e4d5-4b44-896f-64bb99e017b2",
            "sourceColumn": "Column14",
            "summarizeBy": "none"
          },
          {
            "name": "Column15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a3ee014f-707c-423a-9a57-64d92418551e",
            "sourceColumn": "Column15",
            "summarizeBy": "none"
          },
          {
            "name": "Column16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "84063984-e651-4588-9cf1-e20cc7616487",
            "sourceColumn": "Column16",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "4d80d08f-d450-47aa-adf6-3dfca6b95231",
        "partitions": [
          {
            "name": "Audit and UAT Stats Headers",
            "mode": "import",
            "queryGroup": "Audit and UAT Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Audit and UAT Stats Sheets\",",
                "    #\"Kept First Rows\" = Table.FirstN(Source,1),",
                "    #\"Expanded Workbook_Content.Data\" = Table.ExpandTableColumn(#\"Kept First Rows\", \"Workbook_Content.Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\"}),",
                "    #\"Kept First Rows1\" = Table.FirstN(#\"Expanded Workbook_Content.Data\",2),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Kept First Rows1\",null,\"Notes\",Replacer.ReplaceValue,{\"Column14\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Replaced Value10\",null,\"Date\",Replacer.ReplaceValue,{\"Column1\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",null,\"Staff\",Replacer.ReplaceValue,{\"Column2\"}),",
                "    #\"Transposed Table\" = Table.Transpose(#\"Replaced Value1\"),",
                "    #\"Filled Down\" = Table.FillDown(#\"Transposed Table\",{\"Column1\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filled Down\", \"Custom\", each if [Column1] = [Column2]",
                "then [Column1]",
                "else [Column1] & \" - \" & [Column2]),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Added Custom\",{\"Custom\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Removed Other Columns\",\"1. January Staff\",\"Sheet\",Replacer.ReplaceText,{\"Custom\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"Audit and UAT Stats 2024.xlsx\",\"FileName\",Replacer.ReplaceText,{\"Custom\"}),",
                "    #\"Transposed Table1\" = Table.Transpose(#\"Replaced Value12\")",
                "in",
                "    #\"Transposed Table1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Audit and UAT Stats Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Audit and UAT Stats"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a9221741-80f4-40f6-9aad-33239fd9c37f",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "922d8ce6-80b5-44bd-b607-506218b5f84a",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "72994554-0faf-4788-9bb5-cfbe4c5be23a",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ab5a2dba-f319-418f-b748-eefcf76178c8",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          },
          {
            "name": "Column6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bc6171a2-67e9-4797-9b3f-1d92f1cf21b4",
            "sourceColumn": "Column6",
            "summarizeBy": "none"
          },
          {
            "name": "Column7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ff3d20ae-c7d4-4987-a58d-9eaaf916bf34",
            "sourceColumn": "Column7",
            "summarizeBy": "none"
          },
          {
            "name": "Column8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cc6ef692-f7ea-4e57-a219-57a52f8febd9",
            "sourceColumn": "Column8",
            "summarizeBy": "none"
          },
          {
            "name": "Column9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ecaf7dad-eb2e-4769-a447-fad6f2f7d4fc",
            "sourceColumn": "Column9",
            "summarizeBy": "none"
          },
          {
            "name": "Column10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ac71e9df-b0e6-4570-a048-ce46c357e46b",
            "sourceColumn": "Column10",
            "summarizeBy": "none"
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "167120c8-bdeb-4e39-a11f-fda6b33e2212",
            "sourceColumn": "Column11",
            "summarizeBy": "none"
          },
          {
            "name": "Column12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0ec9b4f7-df38-4be6-9d5f-1fc8b138f748",
            "sourceColumn": "Column12",
            "summarizeBy": "none"
          },
          {
            "name": "Column13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "adac4db3-84cb-4f7d-93dc-d790a95d8dc2",
            "sourceColumn": "Column13",
            "summarizeBy": "none"
          },
          {
            "name": "Column14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3a8511cb-371b-49b1-a7e3-89743bbe638a",
            "sourceColumn": "Column14",
            "summarizeBy": "none"
          },
          {
            "name": "Column15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9aa11116-acb4-47a5-bac9-7e5d77c8b01d",
            "sourceColumn": "Column15",
            "summarizeBy": "none"
          },
          {
            "name": "Column16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2bf9c6b6-f6c0-49ac-ad34-7edfc3ec8241",
            "sourceColumn": "Column16",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a4a86ab7-c815-42bc-8abc-d52d6ff96193",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "a81103e8-d0d4-49c1-853d-1898d3e353fe",
        "partitions": [
          {
            "name": "Audit and UAT Stats Data",
            "mode": "import",
            "queryGroup": "Audit and UAT Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Audit and UAT Stats Sheets\",",
                "    #\"Renamed Columns\" = Table.RenameColumns(Source,{{\"Name\", \"Column1\"}, {\"Workbook_Content.Name\", \"Column2\"}}),",
                "    #\"Expanded Workbook_Content.Data\" = Table.ExpandTableColumn(#\"Renamed Columns\", \"Workbook_Content.Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\"}, {\"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\"}),",
                "    #\"Filled Down\" = Table.FillDown(#\"Expanded Workbook_Content.Data\",{\"Column3\"}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filled Down\", each ([Column3] <> null and [Column3] <> \" \" and [Column3] <> \"Blank\" and [Column3] <> \"Monthly Total\" and [Column3] <> \"Total\" and [Column3] <> \"SubTotal\")),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows2\", \"Custom\", each try Value.Is(Date.From([Column3]), type date) otherwise false),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each true),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Custom\"}),",
                "    #\"Filtered Rows5\" = Table.SelectRows(#\"Removed Columns\", each ([Column4] <> null and [Column4] <> \"Totals\")),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Filtered Rows5\", \"Merged\", each Text.Combine({Text.From([Column5], \"en-US\"), Text.From([Column6], \"en-US\"), Text.From([Column7], \"en-US\"), Text.From([Column8], \"en-US\"), Text.From([Column9], \"en-US\"), Text.From([Column10], \"en-US\"), Text.From([Column11], \"en-US\"), Text.From([Column12], \"en-US\"), Text.From([Column13], \"en-US\"), Text.From([Column14], \"en-US\"), Text.From([Column15], \"en-US\"), [Column16]}, \"\"), type text),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Inserted Merged Column\", each ([Merged] <> \"\")),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"Merged\"}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Removed Columns1\", \"email\", each [Column4] & \"@douglas.co.us\"),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Added Custom1\",{\"Column1\", \"Column2\", \"Column3\", \"email\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\"}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Reordered Columns\",{\"Column4\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns2\",{{\"email\", \"Column4\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - Staff Sheets",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cd37959b-56a0-46e1-82cd-80b5ae3b661f",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tables.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3804029d-5db8-49c4-9dca-e6216a3090be",
            "sourceColumn": "Tables.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tables.Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "86614839-35e6-4ffb-a3a0-db9ba1ffb641",
            "sourceColumn": "Tables.Data",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "a3da3e1b-c122-4b6d-8074-2a186265229f",
        "partitions": [
          {
            "name": "Staff Stats - Staff Sheets",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - File Table List\",",
                "    #\"Filtered Staff\" = Table.SelectRows(Source, each Text.EndsWith([Tables.Name], \"Staff\") or Text.EndsWith([Tables.Name], \"staff\")),",
                "    #\"Filtered Master Staff\" = Table.SelectRows(#\"Filtered Staff\", each ([Tables.Name] <> \"Master Staff\"))",
                "in",
                "    #\"Filtered Master Staff\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - Physical Mail",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "columns": [
          {
            "name": "File.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "961af677-a98f-4827-b3ba-425b70fbd546",
            "sourceColumn": "File.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Tables.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea2659ee-256d-4025-aa74-948a1642a9e5",
            "sourceColumn": "Tables.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Renewals-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87133193-5fbb-4321-b5bc-422b16c21342",
            "sourceColumn": "Renewals-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Renewals-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48bba1bb-a390-46a5-868b-55c049fc4b18",
            "sourceColumn": "Renewals-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Renewals-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "433bf6de-4bef-4ba6-9423-088bf2a96a61",
            "sourceColumn": "Renewals-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Renewals-SO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55d5aeab-bb95-414a-912b-a5d3e28c1d3b",
            "sourceColumn": "Renewals-SO",
            "summarizeBy": "sum"
          },
          {
            "name": "Mortgage Mail-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80b45544-4b7e-430c-abad-8b98d11ab9a1",
            "sourceColumn": "Mortgage Mail-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Mortgage Mail-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f981f2c-44d5-4548-b09f-0d9bc0c4e60c",
            "sourceColumn": "Mortgage Mail-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Mortgage Mail-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c505f1a6-f93b-435f-9e12-2e3b3018bd9f",
            "sourceColumn": "Mortgage Mail-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Mortgage Mail-SO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "830b6a4e-ba6e-4141-b329-82ed66cf8f1c",
            "sourceColumn": "Mortgage Mail-SO",
            "summarizeBy": "sum"
          },
          {
            "name": "Salvages-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03bffa9f-e7b8-42d3-87a7-6366e0160c81",
            "sourceColumn": "Salvages-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Salvages-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c0265ed-b177-401c-921b-ceedf8e5ee9c",
            "sourceColumn": "Salvages-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Salvages-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "565b63f4-5a32-4c99-af14-0c1e078fe7f3",
            "sourceColumn": "Salvages-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Salvages-SO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eff8a5d6-66aa-4699-8250-c5279c9d0d20",
            "sourceColumn": "Salvages-SO",
            "summarizeBy": "sum"
          },
          {
            "name": "Eservices-Duplicate-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "791c5200-7a76-47b3-b92a-1a6a46419791",
            "sourceColumn": "Eservices-Duplicate-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Eservices-Duplicate-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "090a7031-27f1-405d-80e7-550af8f56231",
            "sourceColumn": "Eservices-Duplicate-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Eservices-Duplicate-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6a221589-be5c-4893-97e7-eddf7f1ab13a",
            "sourceColumn": "Eservices-Duplicate-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Enterprise-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe6af67b-fccb-4d98-aa58-1cfb0524f512",
            "sourceColumn": "Enterprise-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Enterprise-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e56c0bd8-1eba-48de-8361-6bcf88dc7dd9",
            "sourceColumn": "Enterprise-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Enterprise-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1eea60a2-bc2d-4394-935c-c5cb37321920",
            "sourceColumn": "Enterprise-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-Renewal-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b67a79b-23b8-4428-97ed-116b223b6099",
            "sourceColumn": "Business-Renewal-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-Renewal-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "83424c8d-68ea-4ccf-aa51-88244fdbdbad",
            "sourceColumn": "Business-Renewal-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-Renewal-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "faa7a7cf-1e46-4e89-93d8-abd4f63ed127",
            "sourceColumn": "Business-Renewal-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-MM-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bd35821f-34fc-4068-a5aa-47b4f66cd61a",
            "sourceColumn": "Business-MM-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-MM-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33dc2540-635c-4b31-ab00-f006487af3d0",
            "sourceColumn": "Business-MM-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-MM-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9eea9d28-d197-4cb0-b419-054d0b3e376f",
            "sourceColumn": "Business-MM-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-Communications-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5f77591-45ab-4b4e-bb9c-5545033e7dd5",
            "sourceColumn": "Business-Communications-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-Communications-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ccc3cb2f-1e07-4839-abc7-66b5d9bd1bbf",
            "sourceColumn": "Business-Communications-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Business-Communications-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "272af59e-e694-4814-85b7-4c8b3f995fb1",
            "sourceColumn": "Business-Communications-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer-Renewal-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "821b56cf-fece-4a1c-ab10-0099c6fa5a10",
            "sourceColumn": "Dealer-Renewal-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer-Renewal-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2f26902-f38d-42de-981c-4bc492e9e54c",
            "sourceColumn": "Dealer-Renewal-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer-Renewal-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c45e8b46-218e-4977-b72b-f0b397b198c8",
            "sourceColumn": "Dealer-Renewal-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer-MM-Rec",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d27f84e1-b87c-4282-b31c-2fd5897b9d68",
            "sourceColumn": "Dealer-MM-Rec",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer-MM-Pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da925897-4e70-4054-85d1-2af4ff51a639",
            "sourceColumn": "Dealer-MM-Pro",
            "summarizeBy": "sum"
          },
          {
            "name": "Dealer-MM-Rej",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "423189f7-d0c4-421e-bf87-49c44b7b51e7",
            "sourceColumn": "Dealer-MM-Rej",
            "summarizeBy": "sum"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "INT(FORMAT('Staff Stats - Physical Mail'[Date],\"YYYYMMDD\"))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d41df6f7-f67b-4058-9510-c6cc9cb2a1eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "c41459a4-de78-431e-aab1-c0bec1f7fe01",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Clerk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03d3c3c9-3346-48a0-ae29-7401ed9750f1",
            "sourceColumn": "Clerk",
            "summarizeBy": "none"
          },
          {
            "name": "Notes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4bccc18-024a-4c75-b0ef-f01011323a30",
            "sourceColumn": "Notes",
            "summarizeBy": "none"
          }
        ],
        "defaultDetailRowsDefinition": {
          "expression": [
            "SUM( 'Staff Stats - Physical Mail'[Renewals-Rec] )",
            ""
          ]
        },
        "lineageTag": "73c1154c-4104-4f87-b72d-adecfafc9b6f",
        "partitions": [
          {
            "name": "Staff Stats - Physical Mail",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - Staff Sheets\",",
                "    #\"Kept First Rows\" = Table.FirstN(Source,1),",
                "    #\"Expanded Tables.Data\" = Table.ExpandTableColumn(#\"Kept First Rows\", \"Tables.Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"}, {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"}),",
                "    #\"Kept First Rows1\" = Table.FirstN(#\"Expanded Tables.Data\",3),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Kept First Rows1\",{\"Name\", \"Tables.Name\"}),",
                "    #\"Transposed Table\" = Table.Transpose(#\"Removed Columns\"),",
                "    #\"Filled Down2\" = Table.FillDown(#\"Transposed Table\",{\"Column1\", \"Column2\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filled Down2\",null,\" \",Replacer.ReplaceValue,{\"Column1\", \"Column2\", \"Column3\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\" \",\"Date\",Replacer.ReplaceValue,{\"Column1\"}),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Replaced Value1\",{\"Column1\", \"Column2\", \"Column3\"},Combiner.CombineTextByDelimiter(\"-\", QuoteStyle.None),\"Merged\"),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Merged Columns\",\"- -\",\"-\",Replacer.ReplaceText,{\"Merged\"}),",
                "    #\"Transposed Table1\" = Table.Transpose(#\"Replaced Value2\"),",
                "    #\"Added Custom3\" = Table.AddColumn(#\"Transposed Table1\", \"Tables.Name\", each \"Tables.Name\"),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Added Custom3\", \"File.Name\", each \"File.Name\"),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Added Custom\",\"-\",\"\",Replacer.ReplaceText,{\"Column1\", \"Column2\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"-MM-\",\"\",Replacer.ReplaceText,{\"Column36\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Replaced Value4\",{\"File.Name\", \"Tables.Name\", \"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\", \"Column8\", \"Column9\", \"Column10\", \"Column11\", \"Column12\", \"Column13\", \"Column14\", \"Column15\", \"Column16\", \"Column17\", \"Column18\", \"Column19\", \"Column20\", \"Column21\", \"Column22\", \"Column23\", \"Column24\", \"Column25\", \"Column26\", \"Column27\", \"Column28\", \"Column29\", \"Column30\", \"Column31\", \"Column32\", \"Column33\", \"Column34\", \"Column35\", \"Column36\"}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Reordered Columns\",{{\"Column1\", Text.Trim, type text}, {\"Column2\", Text.Trim, type text}, {\"Column36\", Text.Trim, type text}}),",
                "    #\"Appended Data\" = Table.Combine({#\"Trimmed Text\", #\"Staff Stats - Physical Mail Data\"}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Appended Data\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"File.Name\", type text}, {\"Tables.Name\", type text}, {\"Date\", type date}, {\"Clerk\", type text}, {\"Renewals-Rec\", Int64.Type}, {\"Renewals-Pro\", Int64.Type}, {\"Renewals-Rej\", Int64.Type}, {\"Renewals-SO\", Int64.Type}, {\"Mortgage Mail-Rec\", type any}, {\"Mortgage Mail-Pro\", Int64.Type}, {\"Mortgage Mail-Rej\", Int64.Type}, {\"Mortgage Mail-SO\", Int64.Type}, {\"Salvages-Rec\", Int64.Type}, {\"Salvages-Pro\", Int64.Type}, {\"Salvages-Rej\", Int64.Type}, {\"Salvages-SO\", Int64.Type}, {\"Eservices-Duplicate-Rec\", Int64.Type}, {\"Eservices-Duplicate-Pro\", Int64.Type}, {\"Eservices-Duplicate-Rej\", Int64.Type}, {\"Enterprise-Duplicate-Rec\", Int64.Type}, {\"Enterprise-Duplicate-Pro\", Int64.Type}, {\"Enterprise-Duplicate-Rej\", type any}, {\"Business-Renewal-Rec\", Int64.Type}, {\"Business-Renewal-Pro\", Int64.Type}, {\"Business-Renewal-Rej\", Int64.Type}, {\"Business-MM-Rec\", Int64.Type}, {\"Business-MM-Pro\", Int64.Type}, {\"Business-MM-Rej\", Int64.Type}, {\"Business-Communications-Rec\", Int64.Type}, {\"Business-Communications-Pro\", Int64.Type}, {\"Business-Communications-Rej\", type any}, {\"Dealer-Renewal-Rec\", Int64.Type}, {\"Dealer-Renewal-Pro\", Int64.Type}, {\"Dealer-Renewal-Rej\", Int64.Type}, {\"Dealer-MM-Rec\", Int64.Type}, {\"Dealer-MM-Pro\", Int64.Type}, {\"Dealer-MM-Rej\", Int64.Type}, {\"Notes\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Enterprise-Duplicate-Rec\", \"Enterprise-Rec\"}, {\"Enterprise-Duplicate-Pro\", \"Enterprise-Pro\"}, {\"Enterprise-Duplicate-Rej\", \"Enterprise-Rej\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - CO Salvages",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "03d08987-1292-4707-bc1a-285d47d28f28",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Received",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9c24644-958b-465a-8066-43c9968b7247",
            "sourceColumn": "Received",
            "summarizeBy": "sum"
          },
          {
            "name": "Processed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f823ba01-9b03-48aa-8d03-79fb109d7a33",
            "sourceColumn": "Processed",
            "summarizeBy": "sum"
          },
          {
            "name": "In to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Salvages'[Received] )",
              "    , ALL ( 'Staff Stats - CO Salvages' ), 'Staff Stats - CO Salvages'[Date] <= EARLIER ( 'Staff Stats - CO Salvages'[Date] )",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "34d92dbb-7e33-4a62-a019-2b4067c8b113",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Out to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Salvages'[Processed] )",
              "    , ALL ( 'Staff Stats - CO Salvages' ), 'Staff Stats - CO Salvages'[Date] <= EARLIER ( 'Staff Stats - CO Salvages'[Date] )",
              ")"
            ],
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "2aba359e-c247-4b70-9dba-1ce86776c41a",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Var to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Staff Stats - CO Salvages'[In to Date] - 'Staff Stats - CO Salvages'[Out to Date]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "d79c886f-0205-4570-ac0d-bfead822bb6d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Var",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "19e4f91c-93ad-4ef6-a411-35c86972723c",
            "sourceColumn": "Var",
            "summarizeBy": "sum"
          },
          {
            "name": "Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66ff329e-cd90-4665-b1f2-0ab83f58fe1a",
            "sourceColumn": "Activity",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4b3f3a36-a594-4a7e-83c3-aa5f60cc6cd0",
        "measures": [
          {
            "name": "Days Out From Received - Salvages",
            "expression": [
              "",
              "VAR OutToDate = MAX('Staff Stats - CO Salvages'[Out to Date])",
              "VAR IsActivity = MAX('Staff Stats - CO Salvages'[Activity])",
              "",
              "VAR res = ",
              "IF( IsActivity <= 0, BLANK(),",
              "    CALCULATE ( ",
              "        COUNTROWS( 'Staff Stats - CO Salvages' )",
              "        , ALL ( 'Staff Stats - CO Salvages' )",
              "        , 'Staff Stats - CO Salvages'[Date] < MAX ( 'Staff Stats - CO Salvages'[Date] ) ",
              "        , 'Staff Stats - CO Salvages'[In to Date] > OutToDate",
              "    ) ",
              ")",
              "RETURN ",
              "    res "
            ],
            "formatString": "0",
            "lineageTag": "1eaae79f-2982-480e-a276-1e6411d23b82"
          }
        ],
        "partitions": [
          {
            "name": "Staff Stats - CO Salvages",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - Physical Mail\",",
                "    #\"Removed Columns2\" = Table.RemoveColumns(Source,{\"Clerk\", \"Renewals-Rec\", \"Renewals-Pro\", \"Renewals-Rej\", \"Renewals-SO\", \"Mortgage Mail-Rec\", \"Mortgage Mail-Pro\", \"Mortgage Mail-Rej\", \"Mortgage Mail-SO\", \"Eservices-Duplicate-Rec\", \"Eservices-Duplicate-Pro\", \"Eservices-Duplicate-Rej\", \"Enterprise-Rec\", \"Enterprise-Pro\", \"Enterprise-Rej\", \"Business-Renewal-Rec\", \"Business-Renewal-Pro\", \"Business-Renewal-Rej\", \"Business-MM-Rec\", \"Business-MM-Pro\", \"Business-MM-Rej\", \"Business-Communications-Rec\", \"Business-Communications-Pro\", \"Business-Communications-Rej\", \"Dealer-Renewal-Rec\", \"Dealer-Renewal-Pro\", \"Dealer-Renewal-Rej\", \"Dealer-MM-Rec\", \"Dealer-MM-Pro\", \"Dealer-MM-Rej\", \"Notes\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns2\",{{\"Salvages-Rec\", \"Received\"}}),",
                "    #\"Inserted Processed\" = Table.AddColumn(#\"Renamed Columns\", \"Processed\", each List.Sum({[#\"Salvages-Pro\"], [#\"Salvages-Rej\"], [#\"Salvages-SO\"]}), Int64.Type),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Inserted Processed\",{\"Date\", \"Received\", \"Processed\"}),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Removed Other Columns\",{{\"Date\", Order.Ascending}}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Sorted Rows1\", {\"Date\"}, {{\"Received\", each List.Sum([Received]), type number}, {\"Processed\", each List.Sum([Processed]), type number}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"Received\", Int64.Type}, {\"Processed\", Int64.Type}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type1\",{{\"Date\", Order.Ascending}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Sorted Rows\", \"Custom\", each [Received] - [Processed]),",
                "    #\"Inserted Sum\" = Table.AddColumn(#\"Added Custom\", \"Addition\", each List.Sum({[Received], [Processed]}), Int64.Type),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Sum\",{{\"Addition\", \"Activity\"}, {\"Custom\", \"Var\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Var\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - CO Renewals",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "5d23525b-ac43-4acc-94e5-12f80357520b",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Received",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ea8f88b-0ea9-42f7-ab9f-a1b9331266fb",
            "sourceColumn": "Received",
            "summarizeBy": "sum"
          },
          {
            "name": "Processed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "543763d3-e690-43bc-bd5e-f45665cecbf9",
            "sourceColumn": "Processed",
            "summarizeBy": "sum"
          },
          {
            "name": "Var",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b43378cd-e077-411f-8137-fa7114431b47",
            "sourceColumn": "Var",
            "summarizeBy": "sum"
          },
          {
            "name": "Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9022fa81-ad7f-4acd-a557-133d0e6bba64",
            "sourceColumn": "Activity",
            "summarizeBy": "sum"
          },
          {
            "name": "In to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Renewals'[Received] )",
              "    , ALL ( 'Staff Stats - CO Renewals' ), 'Staff Stats - CO Renewals'[Date] <= EARLIER ( 'Staff Stats - CO Renewals'[Date] )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "886cebf2-7b47-4e10-89cc-51cd1489563e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Out to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Renewals'[Processed] )",
              "    , ALL ( 'Staff Stats - CO Renewals' ), 'Staff Stats - CO Renewals'[Date] <= EARLIER ( 'Staff Stats - CO Renewals'[Date] )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a8550bfe-4625-4f92-8535-0c639ffde481",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Var to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Staff Stats - CO Renewals'[In to Date] - 'Staff Stats - CO Renewals'[Out to Date]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6ffcf35b-ff53-48ba-96c1-4e13b0b03427",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "96603fb2-e804-4e3c-b4d9-fec8e41d10d6",
        "measures": [
          {
            "name": "Days Out From Received - Renewals",
            "expression": [
              "",
              "VAR OutToDate = MAX('Staff Stats - CO Renewals'[Out to Date])",
              "VAR IsActivity = MAX('Staff Stats - CO Renewals'[Activity])",
              "",
              "VAR res = ",
              "IF( IsActivity <= 0, BLANK(),",
              "    CALCULATE ( ",
              "        COUNTROWS( 'Staff Stats - CO Renewals' )",
              "        , ALL ( 'Staff Stats - CO Renewals' )",
              "        , 'Staff Stats - CO Renewals'[Date] < MAX ( 'Staff Stats - CO Renewals'[Date] ) ",
              "        , 'Staff Stats - CO Renewals'[In to Date] > OutToDate",
              "    ) + 0",
              ")",
              "RETURN ",
              "    res "
            ],
            "formatString": "0",
            "lineageTag": "9f7e8c40-e6f0-4c43-9397-3efe4c94e86d"
          }
        ],
        "partitions": [
          {
            "name": "Staff Stats - CO Renewals",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - Physical Mail\",",
                "    #\"Removed Columns2\" = Table.RemoveColumns(Source,{\"Clerk\", \"Salvages-Rec\", \"Salvages-Pro\", \"Salvages-Rej\", \"Salvages-SO\", \"Mortgage Mail-Rec\", \"Mortgage Mail-Pro\", \"Mortgage Mail-Rej\", \"Mortgage Mail-SO\", \"Eservices-Duplicate-Rec\", \"Eservices-Duplicate-Pro\", \"Eservices-Duplicate-Rej\", \"Enterprise-Rec\", \"Enterprise-Pro\", \"Enterprise-Rej\", \"Business-Renewal-Rec\", \"Business-Renewal-Pro\", \"Business-Renewal-Rej\", \"Business-MM-Rec\", \"Business-MM-Pro\", \"Business-MM-Rej\", \"Business-Communications-Rec\", \"Business-Communications-Pro\", \"Business-Communications-Rej\", \"Dealer-Renewal-Rec\", \"Dealer-Renewal-Pro\", \"Dealer-Renewal-Rej\", \"Dealer-MM-Rec\", \"Dealer-MM-Pro\", \"Dealer-MM-Rej\", \"Notes\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns2\",{{\"Renewals-Rec\", \"Received\"}}),",
                "    #\"Inserted Processed\" = Table.AddColumn(#\"Renamed Columns\", \"Processed\", each List.Sum({[#\"Renewals-Pro\"], [#\"Renewals-Rej\"], [#\"Renewals-SO\"]}), Int64.Type),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Inserted Processed\",{\"Date\", \"Received\", \"Processed\"}),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Removed Other Columns\",{{\"Date\", Order.Ascending}}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Sorted Rows1\", {\"Date\"}, {{\"Received\", each List.Sum([Received]), type number}, {\"Processed\", each List.Sum([Processed]), type number}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"Received\", Int64.Type}, {\"Processed\", Int64.Type}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type1\",{{\"Date\", Order.Ascending}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Sorted Rows\", \"Custom\", each [Received] - [Processed]),",
                "    #\"Inserted Sum\" = Table.AddColumn(#\"Added Custom\", \"Addition\", each List.Sum({[Received], [Processed]}), Int64.Type),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Sum\",{{\"Addition\", \"Activity\"}, {\"Custom\", \"Var\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Var\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - CO Mortgage Mail",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "b66cd58d-a604-4bd3-b026-cf063acc6ed8",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Received",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f448693-83e2-46c5-bedd-66c4180733d8",
            "sourceColumn": "Received",
            "summarizeBy": "sum"
          },
          {
            "name": "Processed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0756b179-6b24-428c-b4ac-89d496d14505",
            "sourceColumn": "Processed",
            "summarizeBy": "sum"
          },
          {
            "name": "Var",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f133eca1-b02c-4c57-9ea2-11e3e1bc17e5",
            "sourceColumn": "Var",
            "summarizeBy": "sum"
          },
          {
            "name": "Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbdcdda7-3d02-4574-87a0-0d4952f043ad",
            "sourceColumn": "Activity",
            "summarizeBy": "sum"
          },
          {
            "name": "In to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Mortgage Mail'[Received] )",
              "    , ALL ( 'Staff Stats - CO Mortgage Mail' ), 'Staff Stats - CO Mortgage Mail'[Date] <= EARLIER ( 'Staff Stats - CO Mortgage Mail'[Date] )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "051eea6a-c1f5-4053-850e-9981ae07aad2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Out to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Mortgage Mail'[Processed] )",
              "    , ALL ( 'Staff Stats - CO Mortgage Mail' ), 'Staff Stats - CO Mortgage Mail'[Date] <= EARLIER ( 'Staff Stats - CO Mortgage Mail'[Date] )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1f33ceaf-b86f-4c35-97a6-dfef574d1a19",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Var to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Staff Stats - CO Mortgage Mail'[In to Date] - 'Staff Stats - CO Mortgage Mail'[Out to Date]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "64df6d91-5634-4682-9ec1-1f27a1bdf8df",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "933db82f-4196-49dc-b4e8-eb96c5e6fbcb",
        "measures": [
          {
            "name": "Days Out From Received - MM",
            "expression": [
              "",
              "VAR OutToDate = MAX('Staff Stats - CO Mortgage Mail'[Out to Date])",
              "VAR IsActivity = MAX('Staff Stats - CO Mortgage Mail'[Activity])",
              "",
              "VAR res = ",
              "IF( IsActivity <= 0, BLANK(),",
              "    CALCULATE ( ",
              "        COUNTROWS( 'Staff Stats - CO Mortgage Mail' )",
              "        , ALL ( 'Staff Stats - CO Mortgage Mail' )",
              "        , 'Staff Stats - CO Mortgage Mail'[Date] < MAX ( 'Staff Stats - CO Mortgage Mail'[Date] ) ",
              "        , 'Staff Stats - CO Mortgage Mail'[In to Date] > OutToDate",
              "    ) + 0",
              ")",
              "RETURN ",
              "    res "
            ],
            "formatString": "0",
            "lineageTag": "e95095c5-dd8c-4c65-abd6-cff9b5268dee"
          }
        ],
        "partitions": [
          {
            "name": "Staff Stats - CO Mortgage Mail",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - Physical Mail\",",
                "    #\"Removed Columns2\" = Table.RemoveColumns(Source,{\"Clerk\", \"Renewals-Rec\", \"Renewals-Pro\", \"Renewals-Rej\", \"Renewals-SO\", \"Salvages-Rec\", \"Salvages-Pro\", \"Salvages-Rej\", \"Salvages-SO\", \"Eservices-Duplicate-Rec\", \"Eservices-Duplicate-Pro\", \"Eservices-Duplicate-Rej\", \"Enterprise-Rec\", \"Enterprise-Pro\", \"Enterprise-Rej\", \"Business-Renewal-Rec\", \"Business-Renewal-Pro\", \"Business-Renewal-Rej\", \"Business-MM-Rec\", \"Business-MM-Pro\", \"Business-MM-Rej\", \"Business-Communications-Rec\", \"Business-Communications-Pro\", \"Business-Communications-Rej\", \"Dealer-Renewal-Rec\", \"Dealer-Renewal-Pro\", \"Dealer-Renewal-Rej\", \"Dealer-MM-Rec\", \"Dealer-MM-Pro\", \"Dealer-MM-Rej\", \"Notes\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns2\",{{\"Mortgage Mail-Rec\", \"Received\"}}),",
                "    #\"Inserted Processed\" = Table.AddColumn(#\"Renamed Columns\", \"Processed\", each List.Sum({[#\"Mortgage Mail-Pro\"], [#\"Mortgage Mail-Rej\"], [#\"Mortgage Mail-SO\"]}), Int64.Type),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Inserted Processed\",{\"Date\", \"Received\", \"Processed\"}),",
                "    #\"Sorted Rows1\" = Table.Sort(#\"Removed Other Columns\",{{\"Date\", Order.Ascending}}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Sorted Rows1\", {\"Date\"}, {{\"Received\", each List.Sum([Received]), type number}, {\"Processed\", each List.Sum([Processed]), type number}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"Received\", Int64.Type}, {\"Processed\", Int64.Type}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type1\",{{\"Date\", Order.Ascending}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Sorted Rows\", \"Custom\", each [Received] - [Processed]),",
                "    #\"Inserted Sum\" = Table.AddColumn(#\"Added Custom\", \"Addition\", each List.Sum({[Received], [Processed]}), Int64.Type),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Sum\",{{\"Addition\", \"Activity\"}, {\"Custom\", \"Var\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Var\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Staff Stats - CO Business",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_TableGroup",
            "value": "Staff Stats"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "2d30da54-bedb-45a2-bc46-19e8c774d52b",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Received",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39525713-2e28-4c98-854c-e77960b868d7",
            "sourceColumn": "Received",
            "summarizeBy": "sum"
          },
          {
            "name": "Processed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "735ac74e-ac4d-4c1f-8fb4-44558b210b51",
            "sourceColumn": "Processed",
            "summarizeBy": "sum"
          },
          {
            "name": "Var",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d652e7b-ad94-4f03-9c41-f8c25fc0f373",
            "sourceColumn": "Var",
            "summarizeBy": "sum"
          },
          {
            "name": "Activity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "335b132a-fe0f-4968-a539-1a7d9f652a03",
            "sourceColumn": "Activity",
            "summarizeBy": "sum"
          },
          {
            "name": "In to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Business'[Received] )",
              "    , ALL ( 'Staff Stats - CO Business' ), 'Staff Stats - CO Business'[Date] <= EARLIER ( 'Staff Stats - CO Business'[Date] )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0a24562d-7237-48c4-a47d-ddbf4de9c95d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Out to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE ( ",
              "    SUM ( 'Staff Stats - CO Business'[Processed] )",
              "    , ALL ( 'Staff Stats - CO Business' ), 'Staff Stats - CO Business'[Date] <= EARLIER ( 'Staff Stats - CO Business'[Date] )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "cfea16ca-789a-4e80-a4c2-8e18528adcd3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Var to Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "'Staff Stats - CO Business'[In to Date] - 'Staff Stats - CO Business'[Out to Date]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "34b5caa4-a1df-4646-b3e9-f9eb3d190ddb",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "86702b27-943b-418b-b0a9-067f5362716b",
        "measures": [
          {
            "name": "Days Out From Received - Business",
            "expression": [
              "",
              "VAR OutToDate = MAX('Staff Stats - CO Business'[Out to Date])",
              "VAR IsActivity = MAX('Staff Stats - CO Business'[Activity])",
              "",
              "VAR res = ",
              "IF( IsActivity <= 0, BLANK(),",
              "    CALCULATE ( ",
              "        COUNTROWS( 'Staff Stats - CO Business' )",
              "        , ALL ( 'Staff Stats - CO Business' )",
              "        , 'Staff Stats - CO Business'[Date] < MAX ( 'Staff Stats - CO Business'[Date] ) ",
              "        , 'Staff Stats - CO Business'[In to Date] > OutToDate",
              "    ) + 0",
              ")",
              "RETURN ",
              "    res "
            ],
            "formatString": "0",
            "lineageTag": "2d6c1361-0124-4e99-aea0-c5e7e4adc598"
          }
        ],
        "partitions": [
          {
            "name": "Staff Stats - CO Business",
            "mode": "import",
            "queryGroup": "Staff Stats",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Staff Stats - Physical Mail\",",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(Source,{\"Date\", \"Enterprise-Rec\", \"Enterprise-Pro\", \"Enterprise-Rej\", \"Business-Renewal-Rec\", \"Business-Renewal-Pro\", \"Business-Renewal-Rej\", \"Business-MM-Rec\", \"Business-MM-Pro\", \"Business-MM-Rej\", \"Business-Communications-Rec\", \"Business-Communications-Pro\", \"Business-Communications-Rej\", \"Dealer-Renewal-Rec\", \"Dealer-Renewal-Pro\", \"Dealer-Renewal-Rej\", \"Dealer-MM-Rec\", \"Dealer-MM-Pro\", \"Dealer-MM-Rej\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns1\",{{\"Business-Communications-Rej\", Int64.Type}, {\"Enterprise-Rej\", Int64.Type}}),",
                "    #\"Inserted Received\" = Table.AddColumn(#\"Changed Type\", \"Received\", each List.Sum({[#\"Enterprise-Rec\"], [#\"Business-Renewal-Rec\"], [#\"Business-MM-Rec\"], [#\"Business-Communications-Rec\"], [#\"Dealer-Renewal-Rec\"], [#\"Dealer-MM-Rec\"]}), Int64.Type),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Inserted Received\",{\"Enterprise-Rec\", \"Business-Renewal-Rec\", \"Business-MM-Rec\", \"Business-Communications-Rec\", \"Dealer-Renewal-Rec\", \"Dealer-MM-Rec\"}),",
                "    #\"Inserted Processed\" = Table.AddColumn(#\"Removed Columns\", \"Processed\", each List.Sum({[#\"Enterprise-Pro\"], [#\"Enterprise-Rej\"], [#\"Business-Renewal-Pro\"], [#\"Business-Renewal-Rej\"], [#\"Business-MM-Pro\"], [#\"Business-MM-Rej\"], [#\"Business-Communications-Pro\"], [#\"Business-Communications-Rej\"], [#\"Dealer-Renewal-Pro\"], [#\"Dealer-Renewal-Rej\"], [#\"Dealer-MM-Pro\"], [#\"Dealer-MM-Rej\"]}), Int64.Type),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Inserted Processed\",{\"Date\", \"Received\", \"Processed\"}),",
                "    #\"Grouped Rows\" = Table.Group(#\"Removed Other Columns\", {\"Date\"}, {{\"Received\", each List.Sum([Received]), type number}, {\"Processed\", each List.Sum([Processed]), type number}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Grouped Rows\",{{\"Received\", Int64.Type}, {\"Processed\", Int64.Type}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type1\",{{\"Date\", Order.Ascending}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Sorted Rows\", \"Custom\", each [Received] - [Processed]),",
                "    #\"Inserted Sum\" = Table.AddColumn(#\"Added Custom\", \"Addition\", each List.Sum({[Received], [Processed]}), Int64.Type),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Sum\",{{\"Addition\", \"Activity\"}, {\"Custom\", \"Var\"}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Var\", Int64.Type}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}